import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('📚 Seeding SG expanded laws...');

  // ============================================================
  // 1. Payment Services Act 2019 (Cap. 286B) - EXPANDED
  // ============================================================
  const psaArticles = [
    {
      articleNum: 'Section 2',
      articleTitle: 'Definitions',
      chapter: 'Part 1 - Preliminary',
      sortOrder: 1,
      content: 'Section 2 of the Payment Services Act 2019 sets out the definitions used throughout the Act. A "digital payment token" (DPT) is defined as any digital representation of value that is expressed as a unit, not denominated in any currency, and is or is intended to be a medium of exchange accepted by the public. "Payment service" covers seven activities including account issuance, domestic money transfer, cross-border money transfer, merchant acquisition, e-money issuance, DPT services, and money-changing. The definitions form the foundation for determining which activities require licensing under the Act.',
      contentEn: 'Section 2 of the Payment Services Act 2019 sets out the definitions used throughout the Act. A "digital payment token" (DPT) is defined as any digital representation of value that is expressed as a unit, not denominated in any currency, and is or is intended to be a medium of exchange accepted by the public. "Payment service" covers seven activities including account issuance, domestic money transfer, cross-border money transfer, merchant acquisition, e-money issuance, DPT services, and money-changing. The definitions form the foundation for determining which activities require licensing under the Act.',
      tags: ['definitions', 'dpt', 'scope'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 3',
      articleTitle: 'Application of Act',
      chapter: 'Part 1 - Preliminary',
      sortOrder: 2,
      content: 'Section 3 establishes the territorial and substantive scope of the Act. The Act applies to any person carrying on a business of providing any payment service in Singapore, regardless of whether the person is incorporated in Singapore. It also applies to overseas persons who solicit Singapore residents. Certain activities are exempt, including central banks, public bodies, and activities incidental to the main business.',
      contentEn: 'Section 3 establishes the territorial and substantive scope of the Act. The Act applies to any person carrying on a business of providing any payment service in Singapore, regardless of whether the person is incorporated in Singapore. It also applies to overseas persons who solicit Singapore residents. Certain activities are exempt, including central banks, public bodies, and activities incidental to the main business.',
      tags: ['scope', 'jurisdiction'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 5',
      articleTitle: 'License Requirements - Standard PI and Major PI',
      chapter: 'Part 2 - Licensing',
      sortOrder: 3,
      content: 'Section 5 requires any person carrying on a business of providing any type of payment service in Singapore to hold a license. Three license classes exist: Money-Changing License (for money-changing only), Standard Payment Institution License (transaction thresholds up to SGD 3M/month per service or SGD 6M/month combined), and Major Payment Institution License (for those exceeding thresholds). DPT service providers must obtain at minimum a Standard PI license. Operating without a license is a criminal offense.',
      contentEn: 'Section 5 requires any person carrying on a business of providing any type of payment service in Singapore to hold a license. Three license classes exist: Money-Changing License (for money-changing only), Standard Payment Institution License (transaction thresholds up to SGD 3M/month per service or SGD 6M/month combined), and Major Payment Institution License (for those exceeding thresholds). DPT service providers must obtain at minimum a Standard PI license. Operating without a license is a criminal offense.',
      tags: ['license', 'dpt'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 6',
      articleTitle: 'Application for License',
      chapter: 'Part 2 - Licensing',
      sortOrder: 4,
      content: 'Section 6 sets out the application process. Applicants must submit prescribed forms to MAS together with information on directors, shareholders, business plans, risk management frameworks, AML/CFT controls, and technology infrastructure. MAS conducts a fit-and-proper assessment of controllers and key personnel. The application fee is non-refundable and review typically takes 4-6 months for DPT service providers.',
      contentEn: 'Section 6 sets out the application process. Applicants must submit prescribed forms to MAS together with information on directors, shareholders, business plans, risk management frameworks, AML/CFT controls, and technology infrastructure. MAS conducts a fit-and-proper assessment of controllers and key personnel. The application fee is non-refundable and review typically takes 4-6 months for DPT service providers.',
      tags: ['license', 'application'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 7',
      articleTitle: 'Grant of License',
      chapter: 'Part 2 - Licensing',
      sortOrder: 5,
      content: 'Section 7 empowers MAS to grant, refuse, or grant with conditions a payment service license. MAS must be satisfied that the applicant is fit and proper, has adequate resources, can comply with the Act, and will conduct business prudently. MAS may consider the applicant\'s track record, financial soundness, and group structure. Refusal may be appealed to the Minister.',
      contentEn: 'Section 7 empowers MAS to grant, refuse, or grant with conditions a payment service license. MAS must be satisfied that the applicant is fit and proper, has adequate resources, can comply with the Act, and will conduct business prudently. MAS may consider the applicant\'s track record, financial soundness, and group structure. Refusal may be appealed to the Minister.',
      tags: ['license', 'fit-and-proper'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Section 8',
      articleTitle: 'Conditions of License',
      chapter: 'Part 2 - Licensing',
      sortOrder: 6,
      content: 'Section 8 allows MAS to impose conditions on licenses and to vary them at any time. Common conditions include restrictions on specific activities, customer categories, geographical scope, risk management requirements, reporting obligations, and cooperation with MAS inspections. Breach of license conditions is an offense carrying fines up to SGD 100,000.',
      contentEn: 'Section 8 allows MAS to impose conditions on licenses and to vary them at any time. Common conditions include restrictions on specific activities, customer categories, geographical scope, risk management requirements, reporting obligations, and cooperation with MAS inspections. Breach of license conditions is an offense carrying fines up to SGD 100,000.',
      tags: ['license', 'conditions'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Section 16',
      articleTitle: 'Capital Requirements',
      chapter: 'Part 2 - Licensing',
      sortOrder: 7,
      content: 'Section 16 prescribes minimum base capital requirements. Standard Payment Institutions must maintain base capital of at least SGD 100,000. Major Payment Institutions must maintain at least SGD 250,000. Base capital must consist of paid-up ordinary share capital and unappropriated profits, net of specified deductions. Licensees must maintain this capital at all times and immediately notify MAS if it falls below the threshold.',
      contentEn: 'Section 16 prescribes minimum base capital requirements. Standard Payment Institutions must maintain base capital of at least SGD 100,000. Major Payment Institutions must maintain at least SGD 250,000. Base capital must consist of paid-up ordinary share capital and unappropriated profits, net of specified deductions. Licensees must maintain this capital at all times and immediately notify MAS if it falls below the threshold.',
      tags: ['capital', 'license'],
      appliesToBiz: ['exchange', 'payment-service', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 22',
      articleTitle: 'AML/CFT Obligations',
      chapter: 'Part 2 - Licensing',
      sortOrder: 8,
      content: 'Section 22 imposes core AML/CFT obligations on licensees. Licensees must implement policies, procedures, and controls to prevent money laundering and terrorism financing, conduct customer due diligence, monitor transactions, file suspicious transaction reports with the Suspicious Transaction Reporting Office, and maintain records for at least 5 years. MAS Notice PSN02 provides detailed requirements for DPT service providers.',
      contentEn: 'Section 22 imposes core AML/CFT obligations on licensees. Licensees must implement policies, procedures, and controls to prevent money laundering and terrorism financing, conduct customer due diligence, monitor transactions, file suspicious transaction reports with the Suspicious Transaction Reporting Office, and maintain records for at least 5 years. MAS Notice PSN02 provides detailed requirements for DPT service providers.',
      tags: ['aml', 'cft', 'kyc'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 23',
      articleTitle: 'Business Conduct Rules',
      chapter: 'Part 3 - Conduct of Business',
      sortOrder: 9,
      content: 'Section 23 establishes general business conduct standards. Licensees must act honestly and fairly, exercise due skill and diligence, communicate clearly with customers, manage conflicts of interest, and treat customers fairly. Specific rules apply to pricing transparency, complaint handling, and product suitability. MAS has issued detailed Guidelines on Fair Dealing that supplement this section.',
      contentEn: 'Section 23 establishes general business conduct standards. Licensees must act honestly and fairly, exercise due skill and diligence, communicate clearly with customers, manage conflicts of interest, and treat customers fairly. Specific rules apply to pricing transparency, complaint handling, and product suitability. MAS has issued detailed Guidelines on Fair Dealing that supplement this section.',
      tags: ['conduct', 'consumer-protection'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 24',
      articleTitle: 'Customer Due Diligence',
      chapter: 'Part 3 - Conduct of Business',
      sortOrder: 10,
      content: 'Section 24 requires licensees to identify and verify customers before establishing business relations or conducting occasional transactions above prescribed thresholds. CDD includes verifying identity through reliable documents, identifying beneficial owners, understanding the purpose of the relationship, and ongoing monitoring. Enhanced CDD applies to high-risk customers, PEPs, and customers from high-risk jurisdictions.',
      contentEn: 'Section 24 requires licensees to identify and verify customers before establishing business relations or conducting occasional transactions above prescribed thresholds. CDD includes verifying identity through reliable documents, identifying beneficial owners, understanding the purpose of the relationship, and ongoing monitoring. Enhanced CDD applies to high-risk customers, PEPs, and customers from high-risk jurisdictions.',
      tags: ['kyc', 'cdd', 'aml'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 25',
      articleTitle: 'Safeguarding of Customer Money',
      chapter: 'Part 3 - Conduct of Business',
      sortOrder: 11,
      content: 'Section 25 requires Major Payment Institutions to safeguard customer money received for e-money issuance or domestic money transfer. Approved safeguarding methods include depositing in a trust account with a Singapore bank, undertaking from a Singapore bank, or guarantee from a safeguarding institution. Safeguarded money must be segregated from operational funds and protected in insolvency.',
      contentEn: 'Section 25 requires Major Payment Institutions to safeguard customer money received for e-money issuance or domestic money transfer. Approved safeguarding methods include depositing in a trust account with a Singapore bank, undertaking from a Singapore bank, or guarantee from a safeguarding institution. Safeguarded money must be segregated from operational funds and protected in insolvency.',
      tags: ['custody', 'safeguarding'],
      appliesToBiz: ['payment-service', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 26',
      articleTitle: 'Risk Management',
      chapter: 'Part 3 - Conduct of Business',
      sortOrder: 12,
      content: 'Section 26 requires licensees to implement risk management systems commensurate with the nature, scale, and complexity of their business. Key risk areas include operational risk, technology risk, cyber security, fraud, credit risk, liquidity risk, and concentration risk. Licensees must maintain a documented risk management framework, conduct periodic risk assessments, and report material incidents to MAS.',
      contentEn: 'Section 26 requires licensees to implement risk management systems commensurate with the nature, scale, and complexity of their business. Key risk areas include operational risk, technology risk, cyber security, fraud, credit risk, liquidity risk, and concentration risk. Licensees must maintain a documented risk management framework, conduct periodic risk assessments, and report material incidents to MAS.',
      tags: ['risk-management', 'cyber'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 28',
      articleTitle: 'DPT Service Provider Definition',
      chapter: 'Part 4 - DPT Provisions',
      sortOrder: 13,
      content: 'Section 28 defines a DPT service as dealing in DPTs (buying/selling) or facilitating the exchange of DPTs. Following the 2021 amendments, the definition was expanded to include custodial services, transfer services, and facilitation of DPT transmission, aligning with FATF Recommendation 15 on Virtual Asset Service Providers. Any entity performing these activities in or from Singapore requires a license.',
      contentEn: 'Section 28 defines a DPT service as dealing in DPTs (buying/selling) or facilitating the exchange of DPTs. Following the 2021 amendments, the definition was expanded to include custodial services, transfer services, and facilitation of DPT transmission, aligning with FATF Recommendation 15 on Virtual Asset Service Providers. Any entity performing these activities in or from Singapore requires a license.',
      tags: ['dpt', 'vasp', 'definitions'],
      appliesToBiz: ['exchange', 'wallet-provider', 'defi-protocol'],
    },
    {
      articleNum: 'Section 30',
      articleTitle: 'Restrictions on DPT Advertising',
      chapter: 'Part 4 - DPT Provisions',
      sortOrder: 14,
      content: 'Section 30, supplemented by MAS Guidelines on Provision of Digital Payment Token Services to the Public (January 2022), prohibits DPT service providers from marketing or advertising DPT services in public areas such as public transport, websites, social media, and broadcast media targeted at the Singapore general public. Advertising is permitted only on the provider\'s own corporate website, mobile app, and official social media accounts. The aim is to discourage cryptocurrency trading by retail investors.',
      contentEn: 'Section 30, supplemented by MAS Guidelines on Provision of Digital Payment Token Services to the Public (January 2022), prohibits DPT service providers from marketing or advertising DPT services in public areas such as public transport, websites, social media, and broadcast media targeted at the Singapore general public. Advertising is permitted only on the provider\'s own corporate website, mobile app, and official social media accounts. The aim is to discourage cryptocurrency trading by retail investors.',
      tags: ['advertising', 'consumer-protection', 'dpt'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 31',
      articleTitle: 'Customer Asset Protection',
      chapter: 'Part 4 - DPT Provisions',
      sortOrder: 15,
      content: 'Section 31, implementing MAS requirements effective 2024, requires DPT service providers to hold customer assets in a statutory trust, segregate customer DPTs from proprietary assets, maintain accurate books and records, reconcile daily, and conduct independent audits. At least 90% of customer DPTs must be held in cold wallets. Providers are prohibited from lending, staking, or otherwise using retail customer DPTs without express consent.',
      contentEn: 'Section 31, implementing MAS requirements effective 2024, requires DPT service providers to hold customer assets in a statutory trust, segregate customer DPTs from proprietary assets, maintain accurate books and records, reconcile daily, and conduct independent audits. At least 90% of customer DPTs must be held in cold wallets. Providers are prohibited from lending, staking, or otherwise using retail customer DPTs without express consent.',
      tags: ['custody', 'segregation', 'consumer-protection'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 35',
      articleTitle: 'Cross-border Money Transfer Service',
      chapter: 'Part 5 - Cross-border',
      sortOrder: 16,
      content: 'Section 35 regulates cross-border money transfer services, including remittances and inbound/outbound transfers involving DPTs. Licensees must comply with FATF Travel Rule requirements, transmitting originator and beneficiary information for transfers exceeding SGD 1,500. Correspondent relationships with foreign VASPs require enhanced due diligence. Sanctions screening against UN and MAS lists is mandatory.',
      contentEn: 'Section 35 regulates cross-border money transfer services, including remittances and inbound/outbound transfers involving DPTs. Licensees must comply with FATF Travel Rule requirements, transmitting originator and beneficiary information for transfers exceeding SGD 1,500. Correspondent relationships with foreign VASPs require enhanced due diligence. Sanctions screening against UN and MAS lists is mandatory.',
      tags: ['cross-border', 'travel-rule', 'aml'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 36',
      articleTitle: 'E-money Issuance',
      chapter: 'Part 5 - Cross-border',
      sortOrder: 17,
      content: 'Section 36 governs e-money issuance, defined as electronically stored monetary value denominated in a currency. E-money issuers must redeem at par on demand, safeguard customer funds, and are prohibited from paying interest. The distinction between e-money (currency-denominated) and DPT (non-currency-denominated) is critical for regulatory classification, with stablecoins generally falling under the DPT regime unless they meet SCS requirements.',
      contentEn: 'Section 36 governs e-money issuance, defined as electronically stored monetary value denominated in a currency. E-money issuers must redeem at par on demand, safeguard customer funds, and are prohibited from paying interest. The distinction between e-money (currency-denominated) and DPT (non-currency-denominated) is critical for regulatory classification, with stablecoins generally falling under the DPT regime unless they meet SCS requirements.',
      tags: ['e-money', 'stablecoin'],
      appliesToBiz: ['payment-service', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 50',
      articleTitle: 'Inspection Powers',
      chapter: 'Part 6 - Enforcement',
      sortOrder: 18,
      content: 'Section 50 empowers MAS to inspect licensees at any time without prior notice. Inspectors may enter premises, examine books and records, take copies, require explanations, and interview officers and employees. Licensees must cooperate fully and provide all requested information. Obstruction of inspection is an offense carrying fines up to SGD 50,000 and/or imprisonment.',
      contentEn: 'Section 50 empowers MAS to inspect licensees at any time without prior notice. Inspectors may enter premises, examine books and records, take copies, require explanations, and interview officers and employees. Licensees must cooperate fully and provide all requested information. Obstruction of inspection is an offense carrying fines up to SGD 50,000 and/or imprisonment.',
      tags: ['enforcement', 'inspection'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 60',
      articleTitle: 'Penalties',
      chapter: 'Part 6 - Enforcement',
      sortOrder: 19,
      content: 'Section 60 sets out penalties for contraventions of the Act. Operating without a license carries fines up to SGD 250,000 and/or imprisonment up to 3 years. For continuing offenses, further fines of up to SGD 25,000 per day apply. MAS may also impose civil penalties, revoke licenses, issue prohibition orders against individuals, and publish enforcement actions. Criminal prosecutions are conducted by the Public Prosecutor.',
      contentEn: 'Section 60 sets out penalties for contraventions of the Act. Operating without a license carries fines up to SGD 250,000 and/or imprisonment up to 3 years. For continuing offenses, further fines of up to SGD 25,000 per day apply. MAS may also impose civil penalties, revoke licenses, issue prohibition orders against individuals, and publish enforcement actions. Criminal prosecutions are conducted by the Public Prosecutor.',
      tags: ['penalties', 'enforcement'],
      appliesToBiz: ['exchange', 'payment-service', 'wallet-provider', 'stablecoin-issuer'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'SG', lawNumber: 'SG-PSA2019-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'SG',
      lawType: 'law',
      regulator: 'MAS (Monetary Authority of Singapore)',
      title: 'Payment Services Act 2019 (Cap. 286B) - Expanded',
      lawNumber: 'SG-PSA2019-EXPANDED',
      status: 'in_force',
      enactedDate: new Date('2019-02-14'),
      effectiveDate: new Date('2020-01-28'),
      lastAmendedDate: new Date('2024-04-04'),
      totalArticles: psaArticles.length,
      articles: { create: psaArticles },
    },
  });

  // ============================================================
  // 2. MAS Notice PSN02 - AML/CFT for DPT Service Providers
  // ============================================================
  const psn02Articles = [
    {
      articleNum: 'Paragraph 4',
      articleTitle: 'Risk Assessment',
      chapter: 'AML/CFT Framework',
      sortOrder: 1,
      content: 'Paragraph 4 requires DPT service providers to conduct and document enterprise-wide money laundering and terrorism financing risk assessments at least annually. The assessment must consider customer risk, product/service risk, geographic risk, and delivery channel risk. Findings must inform the provider\'s AML/CFT policies, and the assessment must be updated when material changes occur in business activities or risk environment.',
      contentEn: 'Paragraph 4 requires DPT service providers to conduct and document enterprise-wide money laundering and terrorism financing risk assessments at least annually. The assessment must consider customer risk, product/service risk, geographic risk, and delivery channel risk. Findings must inform the provider\'s AML/CFT policies, and the assessment must be updated when material changes occur in business activities or risk environment.',
      tags: ['aml', 'risk-assessment'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 5',
      articleTitle: 'Internal Policies and Controls',
      chapter: 'AML/CFT Framework',
      sortOrder: 2,
      content: 'Paragraph 5 mandates that DPT service providers establish, implement, and maintain internal policies, procedures, and controls to manage AML/CFT risks. These must be approved by senior management and cover CDD, ongoing monitoring, suspicious transaction reporting, record keeping, staff screening, and internal controls. Policies must be reviewed regularly and updated to reflect regulatory changes and emerging risks such as DeFi and privacy coins.',
      contentEn: 'Paragraph 5 mandates that DPT service providers establish, implement, and maintain internal policies, procedures, and controls to manage AML/CFT risks. These must be approved by senior management and cover CDD, ongoing monitoring, suspicious transaction reporting, record keeping, staff screening, and internal controls. Policies must be reviewed regularly and updated to reflect regulatory changes and emerging risks such as DeFi and privacy coins.',
      tags: ['aml', 'policies'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 6',
      articleTitle: 'Customer Due Diligence',
      chapter: 'Customer Identification',
      sortOrder: 3,
      content: 'Paragraph 6 sets out standard CDD requirements. Providers must identify the customer, verify identity using reliable independent sources, identify beneficial owners holding 25% or more, understand the purpose and intended nature of the relationship, and conduct ongoing monitoring. For non-face-to-face onboarding (typical for DPT), additional measures such as video verification, liveness checks, and document authentication are required.',
      contentEn: 'Paragraph 6 sets out standard CDD requirements. Providers must identify the customer, verify identity using reliable independent sources, identify beneficial owners holding 25% or more, understand the purpose and intended nature of the relationship, and conduct ongoing monitoring. For non-face-to-face onboarding (typical for DPT), additional measures such as video verification, liveness checks, and document authentication are required.',
      tags: ['cdd', 'kyc', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 7',
      articleTitle: 'Enhanced CDD for High-Risk',
      chapter: 'Customer Identification',
      sortOrder: 4,
      content: 'Paragraph 7 requires enhanced due diligence for high-risk customers, including obtaining senior management approval, gathering additional information on source of wealth and funds, conducting more frequent reviews, and applying enhanced transaction monitoring. High-risk indicators include unusually large or complex transactions, customers from high-risk jurisdictions on FATF lists, and transactions involving privacy-enhancing technologies.',
      contentEn: 'Paragraph 7 requires enhanced due diligence for high-risk customers, including obtaining senior management approval, gathering additional information on source of wealth and funds, conducting more frequent reviews, and applying enhanced transaction monitoring. High-risk indicators include unusually large or complex transactions, customers from high-risk jurisdictions on FATF lists, and transactions involving privacy-enhancing technologies.',
      tags: ['edd', 'high-risk', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 8',
      articleTitle: 'Politically Exposed Persons',
      chapter: 'Customer Identification',
      sortOrder: 5,
      content: 'Paragraph 8 requires providers to implement risk management systems to determine whether customers or beneficial owners are PEPs, including foreign PEPs, domestic PEPs, and international organization PEPs. For foreign PEPs, enhanced measures are mandatory: senior management approval before establishing relationships, establishing source of wealth/funds, and enhanced ongoing monitoring. Family members and close associates of PEPs are also covered.',
      contentEn: 'Paragraph 8 requires providers to implement risk management systems to determine whether customers or beneficial owners are PEPs, including foreign PEPs, domestic PEPs, and international organization PEPs. For foreign PEPs, enhanced measures are mandatory: senior management approval before establishing relationships, establishing source of wealth/funds, and enhanced ongoing monitoring. Family members and close associates of PEPs are also covered.',
      tags: ['pep', 'edd', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 9',
      articleTitle: 'Wire Transfer / Travel Rule',
      chapter: 'Transaction Requirements',
      sortOrder: 6,
      content: 'Paragraph 9 implements the FATF Travel Rule for DPT transfers. For any DPT transfer, providers must obtain, verify, and transmit originator information (name, account number, address or ID) and beneficiary information (name, account number). The threshold is SGD 1,500 equivalent. For transfers to unhosted wallets, providers must collect originator and beneficiary information and conduct risk-based due diligence.',
      contentEn: 'Paragraph 9 implements the FATF Travel Rule for DPT transfers. For any DPT transfer, providers must obtain, verify, and transmit originator information (name, account number, address or ID) and beneficiary information (name, account number). The threshold is SGD 1,500 equivalent. For transfers to unhosted wallets, providers must collect originator and beneficiary information and conduct risk-based due diligence.',
      tags: ['travel-rule', 'wire-transfer', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 10',
      articleTitle: 'Reliance on Third Parties',
      chapter: 'Third Party Reliance',
      sortOrder: 7,
      content: 'Paragraph 10 permits reliance on third parties to perform CDD measures, subject to conditions: immediate access to CDD information, satisfaction that the third party is regulated and supervised, and ultimate responsibility remaining with the DPT service provider. Third-party reliance is generally not permitted for customers from high-risk jurisdictions.',
      contentEn: 'Paragraph 10 permits reliance on third parties to perform CDD measures, subject to conditions: immediate access to CDD information, satisfaction that the third party is regulated and supervised, and ultimate responsibility remaining with the DPT service provider. Third-party reliance is generally not permitted for customers from high-risk jurisdictions.',
      tags: ['third-party', 'cdd', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 11',
      articleTitle: 'Record Keeping',
      chapter: 'Records and Reporting',
      sortOrder: 8,
      content: 'Paragraph 11 requires providers to maintain all CDD records, transaction records, account files, business correspondence, and analysis results for at least 5 years after the business relationship ends or the occasional transaction is completed. Records must be sufficient to permit reconstruction of individual transactions and be readily available to MAS and law enforcement upon request.',
      contentEn: 'Paragraph 11 requires providers to maintain all CDD records, transaction records, account files, business correspondence, and analysis results for at least 5 years after the business relationship ends or the occasional transaction is completed. Records must be sufficient to permit reconstruction of individual transactions and be readily available to MAS and law enforcement upon request.',
      tags: ['record-keeping', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 12',
      articleTitle: 'Suspicious Transaction Reports',
      chapter: 'Records and Reporting',
      sortOrder: 9,
      content: 'Paragraph 12 requires providers to file STRs with the Suspicious Transaction Reporting Office (STRO) as soon as reasonably practicable upon forming suspicion of money laundering or terrorism financing. Tipping off customers about STRs is prohibited. Providers must have systems to detect unusual patterns, structuring, chain-hopping, mixer usage, and other typologies specific to DPT services.',
      contentEn: 'Paragraph 12 requires providers to file STRs with the Suspicious Transaction Reporting Office (STRO) as soon as reasonably practicable upon forming suspicion of money laundering or terrorism financing. Tipping off customers about STRs is prohibited. Providers must have systems to detect unusual patterns, structuring, chain-hopping, mixer usage, and other typologies specific to DPT services.',
      tags: ['str', 'suspicious-transaction', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 13',
      articleTitle: 'Compliance Officer',
      chapter: 'Governance',
      sortOrder: 10,
      content: 'Paragraph 13 requires appointment of a compliance officer at management level with sufficient authority, seniority, and resources. The officer must have timely access to all CDD information, transaction records, and other relevant data. Responsibilities include overseeing AML/CFT compliance, filing STRs, reporting to the board, and liaising with MAS. The officer must be based in Singapore.',
      contentEn: 'Paragraph 13 requires appointment of a compliance officer at management level with sufficient authority, seniority, and resources. The officer must have timely access to all CDD information, transaction records, and other relevant data. Responsibilities include overseeing AML/CFT compliance, filing STRs, reporting to the board, and liaising with MAS. The officer must be based in Singapore.',
      tags: ['compliance-officer', 'governance'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 14',
      articleTitle: 'Independent Audit',
      chapter: 'Governance',
      sortOrder: 11,
      content: 'Paragraph 14 requires independent audits of the AML/CFT framework at least annually. Audits may be conducted by internal audit or external auditors, provided they are independent of the functions audited. Audit reports must be submitted to senior management and the board, with findings and remediation tracked. MAS may request copies of audit reports.',
      contentEn: 'Paragraph 14 requires independent audits of the AML/CFT framework at least annually. Audits may be conducted by internal audit or external auditors, provided they are independent of the functions audited. Audit reports must be submitted to senior management and the board, with findings and remediation tracked. MAS may request copies of audit reports.',
      tags: ['audit', 'governance', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Paragraph 15',
      articleTitle: 'Training',
      chapter: 'Governance',
      sortOrder: 12,
      content: 'Paragraph 15 requires providers to implement ongoing AML/CFT training for directors, senior management, and employees. Training must cover relevant laws and regulations, typologies specific to DPT services, customer identification procedures, red flags, and reporting obligations. Training records must be maintained and training effectiveness evaluated. New employees must receive training before being assigned AML/CFT responsibilities.',
      contentEn: 'Paragraph 15 requires providers to implement ongoing AML/CFT training for directors, senior management, and employees. Training must cover relevant laws and regulations, typologies specific to DPT services, customer identification procedures, red flags, and reporting obligations. Training records must be maintained and training effectiveness evaluated. New employees must receive training before being assigned AML/CFT responsibilities.',
      tags: ['training', 'aml', 'governance'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'SG', lawNumber: 'SG-MAS-PSN02-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'SG',
      lawType: 'guideline',
      regulator: 'MAS',
      title: 'MAS Notice PSN02 - AML/CFT for DPT Service Providers (Expanded)',
      lawNumber: 'SG-MAS-PSN02-EXPANDED',
      status: 'in_force',
      enactedDate: new Date('2020-01-28'),
      effectiveDate: new Date('2020-01-28'),
      totalArticles: psn02Articles.length,
      articles: { create: psn02Articles },
    },
  });

  // ============================================================
  // 3. Securities and Futures Act 2001 (Cap. 289) - EXPANDED
  // ============================================================
  const sfaArticles = [
    {
      articleNum: 'Section 2',
      articleTitle: 'Definitions',
      chapter: 'Part 1 - Preliminary',
      sortOrder: 1,
      content: 'Section 2 defines "securities" to include shares, debentures, units in business trusts, and any other product prescribed as securities. "Capital markets products" encompasses securities, units in collective investment schemes, derivatives contracts, and spot foreign exchange contracts. Tokenized securities and security tokens fall within this definition when they carry rights analogous to traditional securities, bringing them within SFA regulation.',
      contentEn: 'Section 2 defines "securities" to include shares, debentures, units in business trusts, and any other product prescribed as securities. "Capital markets products" encompasses securities, units in collective investment schemes, derivatives contracts, and spot foreign exchange contracts. Tokenized securities and security tokens fall within this definition when they carry rights analogous to traditional securities, bringing them within SFA regulation.',
      tags: ['definitions', 'securities', 'token'],
      appliesToBiz: ['sto-issuer', 'rwa-issuer', 'token-issuer'],
    },
    {
      articleNum: 'Section 4A',
      articleTitle: 'Exempt Status for Specified Persons',
      chapter: 'Part 1 - Preliminary',
      sortOrder: 2,
      content: 'Section 4A provides exempt status for specified persons including banks, merchant banks, finance companies, and insurance companies that conduct regulated activities incidental to their main business. These exempt financial institutions may carry on certain capital markets activities without a separate CMS license, though they remain subject to conduct and prudential requirements.',
      contentEn: 'Section 4A provides exempt status for specified persons including banks, merchant banks, finance companies, and insurance companies that conduct regulated activities incidental to their main business. These exempt financial institutions may carry on certain capital markets activities without a separate CMS license, though they remain subject to conduct and prudential requirements.',
      tags: ['exemption', 'license'],
      appliesToBiz: ['sto-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 82',
      articleTitle: 'Capital Markets Services License',
      chapter: 'Part 4 - Licensing',
      sortOrder: 3,
      content: 'Section 82 requires any person carrying on business in a regulated activity to hold a Capital Markets Services (CMS) license. Regulated activities include dealing in capital markets products, fund management, real estate investment trust management, product financing, providing custodial services, and advising on corporate finance. Security token platforms offering trading or dealing services must obtain CMS licenses.',
      contentEn: 'Section 82 requires any person carrying on business in a regulated activity to hold a Capital Markets Services (CMS) license. Regulated activities include dealing in capital markets products, fund management, real estate investment trust management, product financing, providing custodial services, and advising on corporate finance. Security token platforms offering trading or dealing services must obtain CMS licenses.',
      tags: ['cms', 'license'],
      appliesToBiz: ['sto-issuer', 'rwa-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 86',
      articleTitle: 'Conditions on CMS License',
      chapter: 'Part 4 - Licensing',
      sortOrder: 4,
      content: 'Section 86 empowers MAS to impose conditions on CMS licenses, including restrictions on products offered, customer categories, minimum capital, risk management, and compliance arrangements. Common conditions include base capital of SGD 250,000 to SGD 5 million depending on activities, professional indemnity insurance, and appointment of qualified key personnel. Conditions may be varied at any time.',
      contentEn: 'Section 86 empowers MAS to impose conditions on CMS licenses, including restrictions on products offered, customer categories, minimum capital, risk management, and compliance arrangements. Common conditions include base capital of SGD 250,000 to SGD 5 million depending on activities, professional indemnity insurance, and appointment of qualified key personnel. Conditions may be varied at any time.',
      tags: ['cms', 'license', 'capital'],
      appliesToBiz: ['sto-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 99',
      articleTitle: 'Licensing of Representatives',
      chapter: 'Part 4 - Licensing',
      sortOrder: 5,
      content: 'Section 99 requires individuals conducting regulated activities on behalf of CMS licensees to be appointed representatives. Representatives must meet fit and proper criteria, pass relevant industry examinations (CMFAS), complete continuing education, and be registered in the MAS Register of Representatives. Representatives are personally liable for misconduct and subject to supervisory action.',
      contentEn: 'Section 99 requires individuals conducting regulated activities on behalf of CMS licensees to be appointed representatives. Representatives must meet fit and proper criteria, pass relevant industry examinations (CMFAS), complete continuing education, and be registered in the MAS Register of Representatives. Representatives are personally liable for misconduct and subject to supervisory action.',
      tags: ['representative', 'license'],
      appliesToBiz: ['sto-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 198',
      articleTitle: 'Definition of Derivatives Contracts',
      chapter: 'Part 12 - Derivatives',
      sortOrder: 6,
      content: 'Section 198 defines derivatives contracts to include contracts whose value derives from underlying assets, rates, or indices. Crypto derivatives, perpetual swaps, and tokenized derivative products fall within scope if they meet the criteria. Dealing in derivatives is a regulated activity requiring CMS licensing, and retail offering of crypto derivatives is generally restricted by MAS.',
      contentEn: 'Section 198 defines derivatives contracts to include contracts whose value derives from underlying assets, rates, or indices. Crypto derivatives, perpetual swaps, and tokenized derivative products fall within scope if they meet the criteria. Dealing in derivatives is a regulated activity requiring CMS licensing, and retail offering of crypto derivatives is generally restricted by MAS.',
      tags: ['derivatives', 'definitions'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 201',
      articleTitle: 'Insider Trading Prohibition',
      chapter: 'Part 12 - Market Conduct',
      sortOrder: 7,
      content: 'Section 201 prohibits trading in securities or derivatives while in possession of material non-public information. This applies equally to tokenized securities. Insiders include directors, employees, consultants, and any person who obtains inside information. Penalties include fines up to SGD 250,000 and/or imprisonment up to 7 years, plus civil penalties of up to 3 times the profit gained or loss avoided.',
      contentEn: 'Section 201 prohibits trading in securities or derivatives while in possession of material non-public information. This applies equally to tokenized securities. Insiders include directors, employees, consultants, and any person who obtains inside information. Penalties include fines up to SGD 250,000 and/or imprisonment up to 7 years, plus civil penalties of up to 3 times the profit gained or loss avoided.',
      tags: ['insider-trading', 'market-conduct'],
      appliesToBiz: ['sto-issuer', 'exchange'],
    },
    {
      articleNum: 'Section 203',
      articleTitle: 'Market Manipulation',
      chapter: 'Part 12 - Market Conduct',
      sortOrder: 8,
      content: 'Section 203 prohibits market manipulation including false trading, price rigging, wash trades, matched orders, and dissemination of false information. These prohibitions apply to security token trading on regulated venues. MAS has taken enforcement action against wash trading on crypto platforms where tokens constituted securities. Penalties mirror those for insider trading.',
      contentEn: 'Section 203 prohibits market manipulation including false trading, price rigging, wash trades, matched orders, and dissemination of false information. These prohibitions apply to security token trading on regulated venues. MAS has taken enforcement action against wash trading on crypto platforms where tokens constituted securities. Penalties mirror those for insider trading.',
      tags: ['market-manipulation', 'market-conduct'],
      appliesToBiz: ['sto-issuer', 'exchange'],
    },
    {
      articleNum: 'Section 218',
      articleTitle: 'Continuous Disclosure',
      chapter: 'Part 13 - Disclosure',
      sortOrder: 9,
      content: 'Section 218 imposes continuous disclosure obligations on issuers of listed securities, requiring prompt disclosure of material information that could affect the price. Security token issuers listed on approved exchanges or RMOs are subject to equivalent requirements. Material events include financial results, corporate actions, regulatory developments, and significant contracts.',
      contentEn: 'Section 218 imposes continuous disclosure obligations on issuers of listed securities, requiring prompt disclosure of material information that could affect the price. Security token issuers listed on approved exchanges or RMOs are subject to equivalent requirements. Material events include financial results, corporate actions, regulatory developments, and significant contracts.',
      tags: ['disclosure', 'listing'],
      appliesToBiz: ['sto-issuer', 'rwa-issuer'],
    },
    {
      articleNum: 'Section 232',
      articleTitle: 'Authorised Collective Investment Schemes',
      chapter: 'Part 13 - CIS',
      sortOrder: 10,
      content: 'Section 232 requires collective investment schemes offered to retail investors to be authorised by MAS. Tokenized funds and crypto funds offered to retail must meet authorization criteria including trustee/custodian arrangements, independent valuation, disclosure, and investment restrictions. Restricted schemes offered only to accredited or institutional investors may be recognised instead under Section 305.',
      contentEn: 'Section 232 requires collective investment schemes offered to retail investors to be authorised by MAS. Tokenized funds and crypto funds offered to retail must meet authorization criteria including trustee/custodian arrangements, independent valuation, disclosure, and investment restrictions. Restricted schemes offered only to accredited or institutional investors may be recognised instead under Section 305.',
      tags: ['cis', 'fund'],
      appliesToBiz: ['fund-manager', 'token-issuer'],
    },
    {
      articleNum: 'Section 239',
      articleTitle: 'Prospectus Requirement',
      chapter: 'Part 13 - Offers',
      sortOrder: 11,
      content: 'Section 239 requires any offer of securities in Singapore to be accompanied by a prospectus registered with MAS. The prospectus must disclose all material information to enable informed investment decisions. Security token offerings (STOs) targeting Singapore investors must comply unless an exemption applies. The prospectus must be updated for material changes and is subject to civil and criminal liability for misstatements.',
      contentEn: 'Section 239 requires any offer of securities in Singapore to be accompanied by a prospectus registered with MAS. The prospectus must disclose all material information to enable informed investment decisions. Security token offerings (STOs) targeting Singapore investors must comply unless an exemption applies. The prospectus must be updated for material changes and is subject to civil and criminal liability for misstatements.',
      tags: ['prospectus', 'offer', 'sto'],
      appliesToBiz: ['sto-issuer', 'ico-issuer', 'rwa-issuer'],
    },
    {
      articleNum: 'Section 240',
      articleTitle: 'Prospectus Exemptions',
      chapter: 'Part 13 - Offers',
      sortOrder: 12,
      content: 'Section 240 provides key exemptions from the prospectus requirement: small offers not exceeding SGD 5 million in any 12-month period, private placements to no more than 50 persons, offers to institutional investors, offers to accredited investors, and offers where consideration per investor is at least SGD 200,000. STOs frequently rely on the accredited investor exemption, requiring verification of investor status.',
      contentEn: 'Section 240 provides key exemptions from the prospectus requirement: small offers not exceeding SGD 5 million in any 12-month period, private placements to no more than 50 persons, offers to institutional investors, offers to accredited investors, and offers where consideration per investor is at least SGD 200,000. STOs frequently rely on the accredited investor exemption, requiring verification of investor status.',
      tags: ['exemption', 'prospectus', 'accredited-investor'],
      appliesToBiz: ['sto-issuer', 'ico-issuer', 'rwa-issuer'],
    },
    {
      articleNum: 'Section 272A',
      articleTitle: 'Registered Fund Management Companies',
      chapter: 'Part 14 - Fund Management',
      sortOrder: 13,
      content: 'Section 272A provides a lighter regulatory regime for Registered Fund Management Companies (RFMCs) serving up to 30 accredited or institutional investors with AUM up to SGD 250 million. RFMCs must notify MAS, meet fit and proper requirements, and comply with conduct and AML rules. Crypto fund managers often use the RFMC regime for early-stage operations before graduating to full CMS licensing.',
      contentEn: 'Section 272A provides a lighter regulatory regime for Registered Fund Management Companies (RFMCs) serving up to 30 accredited or institutional investors with AUM up to SGD 250 million. RFMCs must notify MAS, meet fit and proper requirements, and comply with conduct and AML rules. Crypto fund managers often use the RFMC regime for early-stage operations before graduating to full CMS licensing.',
      tags: ['fund-manager', 'rfmc'],
      appliesToBiz: ['fund-manager'],
    },
    {
      articleNum: 'Section 272B',
      articleTitle: 'Approved Exchange',
      chapter: 'Part 15 - Market Operators',
      sortOrder: 14,
      content: 'Section 272B regulates Approved Exchanges (AE), which operate organised markets for capital markets products. AEs must maintain market integrity, orderly trading, investor protection, and effective risk management. Operators of security token exchanges targeting retail investors must obtain AE approval, meeting stringent requirements on capital, governance, surveillance, and business continuity.',
      contentEn: 'Section 272B regulates Approved Exchanges (AE), which operate organised markets for capital markets products. AEs must maintain market integrity, orderly trading, investor protection, and effective risk management. Operators of security token exchanges targeting retail investors must obtain AE approval, meeting stringent requirements on capital, governance, surveillance, and business continuity.',
      tags: ['exchange', 'approved-exchange'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 272C',
      articleTitle: 'Recognised Market Operator',
      chapter: 'Part 15 - Market Operators',
      sortOrder: 15,
      content: 'Section 272C regulates Recognised Market Operators (RMO), a lighter regime for markets serving accredited or institutional investors or with limited retail participation. Several tokenized securities platforms in Singapore operate as RMOs, such as ADDX and iSTOX. RMOs must maintain orderly markets, comply with AML requirements, and report to MAS regularly.',
      contentEn: 'Section 272C regulates Recognised Market Operators (RMO), a lighter regime for markets serving accredited or institutional investors or with limited retail participation. Several tokenized securities platforms in Singapore operate as RMOs, such as ADDX and iSTOX. RMOs must maintain orderly markets, comply with AML requirements, and report to MAS regularly.',
      tags: ['rmo', 'exchange'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 280',
      articleTitle: 'Authorised Clearing House',
      chapter: 'Part 16 - Clearing',
      sortOrder: 16,
      content: 'Section 280 regulates clearing facilities for capital markets products. Tokenized securities settlement on blockchain may qualify as a clearing facility requiring authorization if providing central counterparty or central securities depository services. MAS has issued specific guidance on distributed ledger technology in clearing and settlement contexts.',
      contentEn: 'Section 280 regulates clearing facilities for capital markets products. Tokenized securities settlement on blockchain may qualify as a clearing facility requiring authorization if providing central counterparty or central securities depository services. MAS has issued specific guidance on distributed ledger technology in clearing and settlement contexts.',
      tags: ['clearing', 'settlement'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 290',
      articleTitle: 'Continuous Reporting Obligations',
      chapter: 'Part 17 - Reporting',
      sortOrder: 17,
      content: 'Section 290 imposes continuous reporting obligations on CMS licensees including periodic financial returns, risk reports, AML reports, and material incident notifications. Reports must be submitted via MASNET. Late or inaccurate reporting attracts supervisory action. Security token service providers must report on custody arrangements and customer asset holdings.',
      contentEn: 'Section 290 imposes continuous reporting obligations on CMS licensees including periodic financial returns, risk reports, AML reports, and material incident notifications. Reports must be submitted via MASNET. Late or inaccurate reporting attracts supervisory action. Security token service providers must report on custody arrangements and customer asset holdings.',
      tags: ['reporting', 'compliance'],
      appliesToBiz: ['sto-issuer', 'exchange', 'fund-manager'],
    },
    {
      articleNum: 'Section 295',
      articleTitle: 'Conflict of Interest',
      chapter: 'Part 17 - Conduct',
      sortOrder: 18,
      content: 'Section 295 requires CMS licensees to identify, manage, and disclose conflicts of interest. For crypto and token service providers, key conflicts include proprietary trading against customers, token listing decisions, and related-party transactions. Conflicts must be managed through structural separation, disclosure, or client consent. MAS Guidelines on Conflicts of Interest provide detailed expectations.',
      contentEn: 'Section 295 requires CMS licensees to identify, manage, and disclose conflicts of interest. For crypto and token service providers, key conflicts include proprietary trading against customers, token listing decisions, and related-party transactions. Conflicts must be managed through structural separation, disclosure, or client consent. MAS Guidelines on Conflicts of Interest provide detailed expectations.',
      tags: ['conflict-of-interest', 'conduct'],
      appliesToBiz: ['sto-issuer', 'exchange', 'fund-manager'],
    },
    {
      articleNum: 'Section 339',
      articleTitle: 'Penalties',
      chapter: 'Part 19 - Enforcement',
      sortOrder: 19,
      content: 'Section 339 establishes penalties for SFA contraventions. Most offenses carry fines up to SGD 250,000 and/or imprisonment up to 7 years. Market misconduct offenses (insider trading, manipulation) may attract civil penalties of up to 3 times the profit gained. MAS may also impose administrative penalties, revoke licenses, issue prohibition orders, and publish enforcement outcomes. Corporate liability extends to officers consenting or conniving in offenses.',
      contentEn: 'Section 339 establishes penalties for SFA contraventions. Most offenses carry fines up to SGD 250,000 and/or imprisonment up to 7 years. Market misconduct offenses (insider trading, manipulation) may attract civil penalties of up to 3 times the profit gained. MAS may also impose administrative penalties, revoke licenses, issue prohibition orders, and publish enforcement outcomes. Corporate liability extends to officers consenting or conniving in offenses.',
      tags: ['penalties', 'enforcement'],
      appliesToBiz: ['sto-issuer', 'exchange', 'fund-manager', 'rwa-issuer'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'SG', lawNumber: 'SG-SFA2001-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'SG',
      lawType: 'law',
      regulator: 'MAS',
      title: 'Securities and Futures Act 2001 (Cap. 289) - Expanded',
      lawNumber: 'SG-SFA2001-EXPANDED',
      status: 'in_force',
      enactedDate: new Date('2001-10-12'),
      effectiveDate: new Date('2002-07-01'),
      lastAmendedDate: new Date('2023-11-15'),
      totalArticles: sfaArticles.length,
      articles: { create: sfaArticles },
    },
  });

  // ============================================================
  // 4. MAS Stablecoin Regulatory Framework (2023) - EXPANDED
  // ============================================================
  const scsArticles = [
    {
      articleNum: 'Part 1',
      articleTitle: 'Scope - Single-Currency Stablecoins',
      chapter: 'Part 1 - Scope',
      sortOrder: 1,
      content: 'Part 1 defines the scope of the SCS framework. It applies to Single-Currency Stablecoins pegged to the Singapore Dollar or any G10 currency (USD, EUR, GBP, JPY, CHF, CAD, AUD, NZD, SEK, NOK) that are issued in Singapore and where the issuer exceeds SGD 5 million in circulation. Multi-currency stablecoins, algorithmic stablecoins, and crypto-backed stablecoins are excluded and continue to be regulated as DPTs under the PSA.',
      contentEn: 'Part 1 defines the scope of the SCS framework. It applies to Single-Currency Stablecoins pegged to the Singapore Dollar or any G10 currency (USD, EUR, GBP, JPY, CHF, CAD, AUD, NZD, SEK, NOK) that are issued in Singapore and where the issuer exceeds SGD 5 million in circulation. Multi-currency stablecoins, algorithmic stablecoins, and crypto-backed stablecoins are excluded and continue to be regulated as DPTs under the PSA.',
      tags: ['scope', 'stablecoin', 'scs'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 2',
      articleTitle: 'Issuer Eligibility',
      chapter: 'Part 2 - Eligibility',
      sortOrder: 2,
      content: 'Part 2 restricts SCS issuance to MAS-licensed financial institutions, primarily Major Payment Institutions with a specific SCS issuance approval, banks, and merchant banks. Issuers must maintain minimum base capital of SGD 1 million or 50% of annual operating expenses, whichever is higher. Fit-and-proper requirements apply to directors, shareholders, and key personnel.',
      contentEn: 'Part 2 restricts SCS issuance to MAS-licensed financial institutions, primarily Major Payment Institutions with a specific SCS issuance approval, banks, and merchant banks. Issuers must maintain minimum base capital of SGD 1 million or 50% of annual operating expenses, whichever is higher. Fit-and-proper requirements apply to directors, shareholders, and key personnel.',
      tags: ['eligibility', 'capital', 'license'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 3',
      articleTitle: 'Reserve Backing Requirements',
      chapter: 'Part 3 - Reserves',
      sortOrder: 3,
      content: 'Part 3 requires SCS to be 100% backed by reserve assets denominated in the same currency as the peg. Eligible reserve assets are limited to cash, cash equivalents, and debt securities issued by the central bank or government of the reference currency with residual maturity of 3 months or less. The reserve value must at all times equal or exceed the par value of outstanding SCS.',
      contentEn: 'Part 3 requires SCS to be 100% backed by reserve assets denominated in the same currency as the peg. Eligible reserve assets are limited to cash, cash equivalents, and debt securities issued by the central bank or government of the reference currency with residual maturity of 3 months or less. The reserve value must at all times equal or exceed the par value of outstanding SCS.',
      tags: ['reserve', 'backing', 'stablecoin'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 4',
      articleTitle: 'Daily Reserve Valuation',
      chapter: 'Part 3 - Reserves',
      sortOrder: 4,
      content: 'Part 4 requires daily mark-to-market valuation of reserve assets. Issuers must maintain internal procedures for valuation, engage independent valuation providers where appropriate, and address shortfalls immediately. Daily reserve composition and value must be disclosed on the issuer\'s website and reported to MAS.',
      contentEn: 'Part 4 requires daily mark-to-market valuation of reserve assets. Issuers must maintain internal procedures for valuation, engage independent valuation providers where appropriate, and address shortfalls immediately. Daily reserve composition and value must be disclosed on the issuer\'s website and reported to MAS.',
      tags: ['reserve', 'valuation'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 5',
      articleTitle: 'Reserve Composition Restrictions',
      chapter: 'Part 3 - Reserves',
      sortOrder: 5,
      content: 'Part 5 sets quantitative restrictions on reserve composition. Corporate bonds, commercial paper, repurchase agreements with non-sovereign counterparties, and crypto assets are prohibited as reserves. Concentration limits apply to individual counterparties and issuers. Cross-currency hedging is not permitted as a substitute for same-currency backing.',
      contentEn: 'Part 5 sets quantitative restrictions on reserve composition. Corporate bonds, commercial paper, repurchase agreements with non-sovereign counterparties, and crypto assets are prohibited as reserves. Concentration limits apply to individual counterparties and issuers. Cross-currency hedging is not permitted as a substitute for same-currency backing.',
      tags: ['reserve', 'composition'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 6',
      articleTitle: 'Custody and Segregation',
      chapter: 'Part 4 - Custody',
      sortOrder: 6,
      content: 'Part 6 requires reserve assets to be held with MAS-regulated custodians or banks in Singapore, in segregated accounts separate from the issuer\'s proprietary assets, and held on trust for SCS holders. The trust structure must ensure bankruptcy remoteness. Foreign custodians may be used only with MAS approval and must meet equivalent standards.',
      contentEn: 'Part 6 requires reserve assets to be held with MAS-regulated custodians or banks in Singapore, in segregated accounts separate from the issuer\'s proprietary assets, and held on trust for SCS holders. The trust structure must ensure bankruptcy remoteness. Foreign custodians may be used only with MAS approval and must meet equivalent standards.',
      tags: ['custody', 'segregation', 'trust'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 7',
      articleTitle: 'Redemption at Par',
      chapter: 'Part 5 - Redemption',
      sortOrder: 7,
      content: 'Part 7 guarantees holders the right to redeem SCS at par value, with redemption to be completed within 5 business days of request. Issuers may not impose redemption fees that exceed operational costs or otherwise impair this right. Redemption procedures must be clearly disclosed in the white paper and terms of service.',
      contentEn: 'Part 7 guarantees holders the right to redeem SCS at par value, with redemption to be completed within 5 business days of request. Issuers may not impose redemption fees that exceed operational costs or otherwise impair this right. Redemption procedures must be clearly disclosed in the white paper and terms of service.',
      tags: ['redemption', 'par-value'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 8',
      articleTitle: 'Disclosure Requirements',
      chapter: 'Part 6 - Disclosure',
      sortOrder: 8,
      content: 'Part 8 requires monthly attestation reports disclosing reserve composition, value, custodian, and any breaches. Reports must be published on the issuer\'s website and easily accessible to holders. The white paper must disclose risks, governance, reserve policy, and redemption terms. Material changes must be notified promptly.',
      contentEn: 'Part 8 requires monthly attestation reports disclosing reserve composition, value, custodian, and any breaches. Reports must be published on the issuer\'s website and easily accessible to holders. The white paper must disclose risks, governance, reserve policy, and redemption terms. Material changes must be notified promptly.',
      tags: ['disclosure', 'attestation'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 9',
      articleTitle: 'Audit Requirements',
      chapter: 'Part 6 - Disclosure',
      sortOrder: 9,
      content: 'Part 9 mandates annual audits of reserve assets by independent external auditors registered with ACRA. Audits must verify existence, ownership, valuation, and segregation of reserves, and assess compliance with reserve composition rules. Audit reports must be published and submitted to MAS within 3 months of financial year-end.',
      contentEn: 'Part 9 mandates annual audits of reserve assets by independent external auditors registered with ACRA. Audits must verify existence, ownership, valuation, and segregation of reserves, and assess compliance with reserve composition rules. Audit reports must be published and submitted to MAS within 3 months of financial year-end.',
      tags: ['audit', 'reserve'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 10',
      articleTitle: 'Restriction on Lending Reserves',
      chapter: 'Part 7 - Restrictions',
      sortOrder: 10,
      content: 'Part 10 prohibits issuers from lending, pledging, rehypothecating, or otherwise encumbering reserve assets. Staking or yield-generating activities using reserves are prohibited. This ensures reserves remain available to meet redemption demands at all times, even in stress scenarios.',
      contentEn: 'Part 10 prohibits issuers from lending, pledging, rehypothecating, or otherwise encumbering reserve assets. Staking or yield-generating activities using reserves are prohibited. This ensures reserves remain available to meet redemption demands at all times, even in stress scenarios.',
      tags: ['reserve', 'lending-restriction'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 11',
      articleTitle: 'No Interest Payments',
      chapter: 'Part 7 - Restrictions',
      sortOrder: 11,
      content: 'Part 11 prohibits SCS issuers from paying interest or yield to holders. This preserves the distinction between SCS (payment instrument) and deposit or investment products subject to separate regulation. Marketing SCS as interest-bearing or yield-generating is prohibited.',
      contentEn: 'Part 11 prohibits SCS issuers from paying interest or yield to holders. This preserves the distinction between SCS (payment instrument) and deposit or investment products subject to separate regulation. Marketing SCS as interest-bearing or yield-generating is prohibited.',
      tags: ['interest', 'restriction'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 12',
      articleTitle: 'AML/CFT Obligations',
      chapter: 'Part 8 - AML',
      sortOrder: 12,
      content: 'Part 12 applies full AML/CFT obligations equivalent to those in MAS Notice PSN02 to SCS issuers. Issuers must conduct CDD on direct customers (typically institutional distributors and large holders), monitor on-chain activity where feasible, implement Travel Rule compliance, and file STRs. Risk-based approach must address the pseudonymous nature of on-chain transfers.',
      contentEn: 'Part 12 applies full AML/CFT obligations equivalent to those in MAS Notice PSN02 to SCS issuers. Issuers must conduct CDD on direct customers (typically institutional distributors and large holders), monitor on-chain activity where feasible, implement Travel Rule compliance, and file STRs. Risk-based approach must address the pseudonymous nature of on-chain transfers.',
      tags: ['aml', 'cft', 'travel-rule'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 13',
      articleTitle: 'White Paper Requirements',
      chapter: 'Part 9 - Documentation',
      sortOrder: 13,
      content: 'Part 13 requires issuers to publish a white paper before issuance, disclosing issuer details, governance structure, reserve policy, custody arrangements, redemption rights, risks, technology stack, smart contract audits, and legal treatment of SCS holders. Material updates must be made promptly. MAS may require amendments before approval.',
      contentEn: 'Part 13 requires issuers to publish a white paper before issuance, disclosing issuer details, governance structure, reserve policy, custody arrangements, redemption rights, risks, technology stack, smart contract audits, and legal treatment of SCS holders. Material updates must be made promptly. MAS may require amendments before approval.',
      tags: ['white-paper', 'disclosure'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 14',
      articleTitle: 'Cross-border Issuance',
      chapter: 'Part 10 - Cross-border',
      sortOrder: 14,
      content: 'Part 14 addresses cross-border aspects. SCS issued from Singapore may circulate internationally, but MAS-regulated status applies only to Singapore-issued SCS. Foreign stablecoins marketed in Singapore remain subject to DPT rules unless recognized by MAS. Issuers operating through branches or subsidiaries in multiple jurisdictions must ensure Singapore-issued SCS meet all SCS framework requirements.',
      contentEn: 'Part 14 addresses cross-border aspects. SCS issued from Singapore may circulate internationally, but MAS-regulated status applies only to Singapore-issued SCS. Foreign stablecoins marketed in Singapore remain subject to DPT rules unless recognized by MAS. Issuers operating through branches or subsidiaries in multiple jurisdictions must ensure Singapore-issued SCS meet all SCS framework requirements.',
      tags: ['cross-border', 'stablecoin'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Part 15',
      articleTitle: 'Penalties and Enforcement',
      chapter: 'Part 11 - Enforcement',
      sortOrder: 15,
      content: 'Part 15 sets out penalties for non-compliance. Unauthorised SCS issuance or false claims of MAS-regulated status carries fines up to SGD 250,000 and/or imprisonment up to 3 years. MAS may suspend or revoke SCS issuance approval, order cessation of issuance, require additional reserves, or impose civil penalties. Enforcement actions are published to enhance market discipline.',
      contentEn: 'Part 15 sets out penalties for non-compliance. Unauthorised SCS issuance or false claims of MAS-regulated status carries fines up to SGD 250,000 and/or imprisonment up to 3 years. MAS may suspend or revoke SCS issuance approval, order cessation of issuance, require additional reserves, or impose civil penalties. Enforcement actions are published to enhance market discipline.',
      tags: ['penalties', 'enforcement'],
      appliesToBiz: ['stablecoin-issuer'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'SG', lawNumber: 'SG-MAS-Stablecoin-2023-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'SG',
      lawType: 'regulation',
      regulator: 'MAS',
      title: 'MAS Stablecoin Regulatory Framework 2023 - Expanded',
      lawNumber: 'SG-MAS-Stablecoin-2023-EXPANDED',
      status: 'in_force',
      enactedDate: new Date('2023-08-15'),
      effectiveDate: new Date('2023-08-15'),
      totalArticles: scsArticles.length,
      articles: { create: scsArticles },
    },
  });

  // ============================================================
  // 5. Banking Act 1970 (Singapore)
  // ============================================================
  const bankingArticles = [
    {
      articleNum: 'Section 4',
      articleTitle: 'Banking License Requirement',
      chapter: 'Part 2 - Licensing',
      sortOrder: 1,
      content: 'Section 4 requires any person carrying on banking business in Singapore to hold a banking license from MAS. Banking business is defined as receiving deposits and making loans. Entities providing crypto custody or tokenized deposit products must assess whether their activities fall within banking business, particularly where deposits are redeemable on demand or used for lending activities.',
      contentEn: 'Section 4 requires any person carrying on banking business in Singapore to hold a banking license from MAS. Banking business is defined as receiving deposits and making loans. Entities providing crypto custody or tokenized deposit products must assess whether their activities fall within banking business, particularly where deposits are redeemable on demand or used for lending activities.',
      tags: ['license', 'banking'],
      appliesToBiz: ['payment-service', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 7',
      articleTitle: 'Minimum Paid-up Capital',
      chapter: 'Part 2 - Licensing',
      sortOrder: 2,
      content: 'Section 7 requires full banks to maintain minimum paid-up capital of SGD 1.5 billion. Wholesale banks require SGD 100 million and merchant banks require SGD 100 million. These high capital thresholds make banking licenses inaccessible for most crypto-native firms, which typically operate under the PSA or SFA instead.',
      contentEn: 'Section 7 requires full banks to maintain minimum paid-up capital of SGD 1.5 billion. Wholesale banks require SGD 100 million and merchant banks require SGD 100 million. These high capital thresholds make banking licenses inaccessible for most crypto-native firms, which typically operate under the PSA or SFA instead.',
      tags: ['capital', 'license'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 10',
      articleTitle: 'Wholesale Banks',
      chapter: 'Part 2 - Licensing',
      sortOrder: 3,
      content: 'Section 10 regulates wholesale banks, which may conduct banking business except SGD retail deposit-taking. Wholesale banks may engage in institutional tokenization projects, custody of digital assets for institutional clients, and crypto-related trading with corporate customers, subject to MAS approval and risk management requirements.',
      contentEn: 'Section 10 regulates wholesale banks, which may conduct banking business except SGD retail deposit-taking. Wholesale banks may engage in institutional tokenization projects, custody of digital assets for institutional clients, and crypto-related trading with corporate customers, subject to MAS approval and risk management requirements.',
      tags: ['wholesale-bank', 'license'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 11',
      articleTitle: 'Foreign Banks',
      chapter: 'Part 2 - Licensing',
      sortOrder: 4,
      content: 'Section 11 regulates foreign bank branches operating in Singapore. Foreign banks conducting digital asset activities in Singapore must obtain specific approval from MAS and comply with host country prudential standards in addition to MAS requirements. Home-host coordination is required for cross-border crypto activities.',
      contentEn: 'Section 11 regulates foreign bank branches operating in Singapore. Foreign banks conducting digital asset activities in Singapore must obtain specific approval from MAS and comply with host country prudential standards in addition to MAS requirements. Home-host coordination is required for cross-border crypto activities.',
      tags: ['foreign-bank', 'license'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 29',
      articleTitle: 'Prudential Requirements',
      chapter: 'Part 4 - Prudential',
      sortOrder: 5,
      content: 'Section 29 empowers MAS to impose prudential requirements on banks, including capital adequacy, liquidity, large exposures, leverage, and concentration limits. MAS applies Basel III standards and has issued specific guidance on treatment of crypto-asset exposures following the Basel Committee standard of December 2022.',
      contentEn: 'Section 29 empowers MAS to impose prudential requirements on banks, including capital adequacy, liquidity, large exposures, leverage, and concentration limits. MAS applies Basel III standards and has issued specific guidance on treatment of crypto-asset exposures following the Basel Committee standard of December 2022.',
      tags: ['prudential', 'basel'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 30',
      articleTitle: 'Capital Adequacy Ratio',
      chapter: 'Part 4 - Prudential',
      sortOrder: 6,
      content: 'Section 30 requires banks to maintain capital adequacy ratios in accordance with MAS Notice 637. Minimum CET1 ratio is 6.5%, Tier 1 is 8%, and total capital is 10%, with additional buffers. Crypto exposures attract punitive risk weights: Group 2 crypto assets (unbacked crypto) receive 1250% risk weight, effectively requiring dollar-for-dollar capital backing.',
      contentEn: 'Section 30 requires banks to maintain capital adequacy ratios in accordance with MAS Notice 637. Minimum CET1 ratio is 6.5%, Tier 1 is 8%, and total capital is 10%, with additional buffers. Crypto exposures attract punitive risk weights: Group 2 crypto assets (unbacked crypto) receive 1250% risk weight, effectively requiring dollar-for-dollar capital backing.',
      tags: ['capital', 'car', 'basel'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 35',
      articleTitle: 'Liquidity Ratio',
      chapter: 'Part 4 - Prudential',
      sortOrder: 7,
      content: 'Section 35 imposes liquidity requirements including the Liquidity Coverage Ratio (LCR) of at least 100% and Net Stable Funding Ratio (NSFR) of at least 100%. Banks holding crypto assets must assess liquidity risk, noting that most crypto assets do not qualify as High Quality Liquid Assets under Basel III standards.',
      contentEn: 'Section 35 imposes liquidity requirements including the Liquidity Coverage Ratio (LCR) of at least 100% and Net Stable Funding Ratio (NSFR) of at least 100%. Banks holding crypto assets must assess liquidity risk, noting that most crypto assets do not qualify as High Quality Liquid Assets under Basel III standards.',
      tags: ['liquidity', 'lcr', 'nsfr'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 50A',
      articleTitle: 'Crypto-Asset Risk Weights for Banks',
      chapter: 'Part 5 - Crypto Exposures',
      sortOrder: 8,
      content: 'Section 50A implements the Basel Committee crypto-asset prudential standard. Group 1a crypto (tokenized traditional assets) receives standard risk weights. Group 1b (stablecoins meeting redemption test) receives risk weights of the reference asset. Group 2 (unbacked crypto like Bitcoin) receives 1250% risk weight. Total Group 2 exposures are capped at 1% of Tier 1 capital, rising to 2% with supervisory consequences.',
      contentEn: 'Section 50A implements the Basel Committee crypto-asset prudential standard. Group 1a crypto (tokenized traditional assets) receives standard risk weights. Group 1b (stablecoins meeting redemption test) receives risk weights of the reference asset. Group 2 (unbacked crypto like Bitcoin) receives 1250% risk weight. Total Group 2 exposures are capped at 1% of Tier 1 capital, rising to 2% with supervisory consequences.',
      tags: ['crypto', 'risk-weight', 'basel'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Section 51A',
      articleTitle: 'Bank Custody of Digital Assets',
      chapter: 'Part 5 - Crypto Exposures',
      sortOrder: 9,
      content: 'Section 51A permits banks to provide custody services for digital assets to customers subject to MAS approval. Banks must implement robust key management, cold storage, segregation of customer assets from proprietary holdings, insurance where appropriate, and clear legal treatment of customer claims. Custody activities must be conducted through approved subsidiaries or dedicated business units.',
      contentEn: 'Section 51A permits banks to provide custody services for digital assets to customers subject to MAS approval. Banks must implement robust key management, cold storage, segregation of customer assets from proprietary holdings, insurance where appropriate, and clear legal treatment of customer claims. Custody activities must be conducted through approved subsidiaries or dedicated business units.',
      tags: ['custody', 'crypto'],
      appliesToBiz: ['payment-service', 'wallet-provider'],
    },
    {
      articleNum: 'Section 52A',
      articleTitle: 'Bank Tokenization Activities',
      chapter: 'Part 5 - Crypto Exposures',
      sortOrder: 10,
      content: 'Section 52A governs bank participation in tokenization activities, including issuing tokenized deposits, operating tokenized asset platforms, and participating in MAS Project Guardian initiatives. Banks may issue tokenized deposits representing claims on the bank, subject to prudential and operational risk management. Smart contract code must be audited and legal enforceability must be ensured.',
      contentEn: 'Section 52A governs bank participation in tokenization activities, including issuing tokenized deposits, operating tokenized asset platforms, and participating in MAS Project Guardian initiatives. Banks may issue tokenized deposits representing claims on the bank, subject to prudential and operational risk management. Smart contract code must be audited and legal enforceability must be ensured.',
      tags: ['tokenization', 'tokenized-deposit'],
      appliesToBiz: ['payment-service', 'rwa-issuer'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'SG', lawNumber: 'SG-BankingAct1970-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'SG',
      lawType: 'law',
      regulator: 'MAS',
      title: 'Banking Act 1970 (Singapore) - Expanded for Digital Assets',
      lawNumber: 'SG-BankingAct1970-EXPANDED',
      status: 'in_force',
      enactedDate: new Date('1970-12-31'),
      lastAmendedDate: new Date('2023-04-21'),
      totalArticles: bankingArticles.length,
      articles: { create: bankingArticles },
    },
  });

  const total = psaArticles.length + psn02Articles.length + sfaArticles.length + scsArticles.length + bankingArticles.length;
  console.log(`✅ SG expanded laws seeded (${total} articles across 5 laws)`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
