import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('📚 Seeding KR additional laws (kr3)...');

  // ============================================================
  // 1. 개인정보 보호법 (PIPA)
  // ============================================================
  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'KR', lawNumber: 'KR-PIPA-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'KR',
      lawType: 'law',
      regulator: '개인정보보호위원회 / PIPC',
      title: '개인정보 보호법',
      titleEn: 'Personal Information Protection Act (PIPA)',
      lawNumber: 'KR-PIPA-EXPANDED',
      status: 'enacted',
      enactedDate: new Date('2011-03-29'),
      effectiveDate: new Date('2011-09-30'),
      lastAmendedDate: new Date('2024-03-15'),
      totalArticles: 15,
      articles: {
        create: [
          {
            articleNum: '제2조',
            articleTitle: '정의',
            chapter: '제1장 총칙',
            sortOrder: 1,
            content: '이 법에서 사용하는 용어의 뜻은 다음과 같다. "개인정보"란 살아 있는 개인에 관한 정보로서 성명, 주민등록번호 및 영상 등을 통하여 개인을 알아볼 수 있는 정보를 말한다. "가명정보"란 가명처리함으로써 원래의 상태로 복원하기 위한 추가 정보의 사용·결합 없이는 특정 개인을 알아볼 수 없는 정보를 말한다. "처리"란 개인정보의 수집, 생성, 연계, 연동, 기록, 저장, 보유, 가공, 편집, 검색, 출력, 정정, 복구, 이용, 제공, 공개, 파기 등 그 밖에 이와 유사한 행위를 말한다.',
            contentEn: 'Definitions: "Personal information" means information relating to a living individual that identifies a person. "Pseudonymized information" means information that cannot identify a specific individual without additional information. "Processing" includes collection, generation, recording, storage, use, provision, disclosure, and destruction of personal information.',
            tags: ['privacy', 'definitions'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: '제3조',
            articleTitle: '개인정보 보호 원칙',
            chapter: '제1장 총칙',
            sortOrder: 2,
            content: '개인정보처리자는 개인정보의 처리 목적을 명확하게 하여야 하고 그 목적에 필요한 범위에서 최소한의 개인정보만을 적법하고 정당하게 수집하여야 한다. 개인정보처리자는 개인정보의 처리 목적에 필요한 범위에서 적합하게 개인정보를 처리하여야 하며, 그 목적 외의 용도로 활용하여서는 아니 된다. 개인정보처리자는 개인정보의 정확성, 완전성 및 최신성이 보장되도록 하여야 한다.',
            contentEn: 'Personal information controllers must clearly specify purposes, collect only the minimum necessary information lawfully and fairly, ensure data accuracy, and not use data beyond specified purposes.',
            tags: ['privacy', 'principles'],
            appliesToBiz: ['exchange', 'wallet-provider', 'defi-protocol', 'nft-platform'],
          },
          {
            articleNum: '제15조',
            articleTitle: '개인정보의 수집·이용',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 3,
            content: '개인정보처리자는 정보주체의 동의를 받은 경우, 법률에 특별한 규정이 있거나 법령상 의무를 준수하기 위하여 불가피한 경우, 공공기관이 법령 등에서 정하는 소관 업무의 수행을 위하여 불가피한 경우 개인정보를 수집할 수 있으며 그 수집 목적의 범위에서 이용할 수 있다. 개인정보처리자는 정보주체의 동의를 받을 때 수집·이용 목적, 수집하려는 개인정보의 항목, 보유 및 이용 기간, 동의를 거부할 권리가 있다는 사실을 알려야 한다.',
            contentEn: 'Controllers may collect personal data with consent, under legal obligations, or for public duties. When obtaining consent, controllers must inform data subjects of purpose, items, retention period, and right to refuse.',
            tags: ['privacy', 'consent', 'kyc'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
          },
          {
            articleNum: '제17조',
            articleTitle: '개인정보의 제공',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 4,
            content: '개인정보처리자는 정보주체의 동의를 받은 경우 및 제15조제1항제2호·제3호 및 제5호부터 제7호까지에 해당하는 경우에 정보주체의 개인정보를 제3자에게 제공할 수 있다. 개인정보처리자는 정보주체의 동의를 받을 때 개인정보를 제공받는 자, 제공받는 자의 이용 목적, 제공하는 개인정보의 항목, 보유 및 이용 기간을 알려야 한다.',
            contentEn: 'Controllers may provide personal data to third parties with consent. Data subjects must be informed of the recipient, purpose of use, data items provided, and retention period.',
            tags: ['privacy', 'third-party'],
            appliesToBiz: ['exchange', 'wallet-provider', 'defi-protocol'],
          },
          {
            articleNum: '제18조',
            articleTitle: '개인정보의 목적 외 이용·제공 제한',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 5,
            content: '개인정보처리자는 개인정보를 제15조제1항에 따른 범위를 초과하여 이용하거나 제17조제1항 및 제28조의8제1항에 따른 범위를 초과하여 제3자에게 제공하여서는 아니 된다. 다만, 정보주체로부터 별도의 동의를 받은 경우, 다른 법률에 특별한 규정이 있는 경우 등 예외적으로 허용된다. 공공기관은 범죄의 수사와 공소의 제기 및 유지를 위하여 필요한 경우에는 예외를 둘 수 있다.',
            contentEn: 'Controllers shall not use or provide personal data beyond the original purpose, except with separate consent or specific legal provisions. Public institutions may have exceptions for criminal investigation and prosecution.',
            tags: ['privacy', 'purpose-limitation'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
          },
          {
            articleNum: '제22조',
            articleTitle: '동의를 받는 방법',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 6,
            content: '개인정보처리자는 이 법에 따른 개인정보의 처리에 대하여 정보주체의 동의를 받을 때에는 각각의 동의 사항을 구분하여 정보주체가 이를 명확하게 인지할 수 있도록 알리고 각각 동의를 받아야 한다. 개인정보처리자는 정보주체의 동의 없이 처리할 수 있는 개인정보와 정보주체의 동의가 필요한 개인정보를 구분하여야 한다. 만 14세 미만 아동의 개인정보를 처리하기 위하여 동의가 필요한 경우 그 법정대리인의 동의를 받아야 한다.',
            contentEn: 'Consent must be obtained separately for each matter with clear notification. Controllers must distinguish between data requiring consent and data processable without consent. Legal guardian consent is required for children under 14.',
            tags: ['privacy', 'consent'],
            appliesToBiz: ['exchange', 'nft-platform', 'wallet-provider'],
          },
          {
            articleNum: '제24조',
            articleTitle: '고유식별정보의 처리 제한',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 7,
            content: '개인정보처리자는 법령에서 구체적으로 고유식별정보의 처리를 요구하거나 허용하는 경우, 정보주체에게 제15조제2항 각 호 또는 제17조제2항 각 호의 사항을 알리고 다른 개인정보의 처리에 대한 동의와 별도로 동의를 받은 경우를 제외하고는 고유식별정보를 처리할 수 없다. 개인정보처리자가 고유식별정보를 처리하는 경우에는 그 고유식별정보가 분실·도난·유출·위조·변조 또는 훼손되지 아니하도록 암호화 등 안전성 확보에 필요한 조치를 하여야 한다.',
            contentEn: 'Unique identifying information may only be processed with specific legal authorization or separate consent. Encryption and safety measures are mandatory to prevent loss, theft, leakage, or alteration.',
            tags: ['privacy', 'kyc'],
            appliesToBiz: ['exchange', 'payment-service', 'stablecoin-issuer'],
          },
          {
            articleNum: '제24조의2',
            articleTitle: '주민등록번호 처리 제한',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 8,
            content: '개인정보처리자는 법률·대통령령·국회규칙·대법원규칙·헌법재판소규칙·중앙선거관리위원회규칙 및 감사원규칙에서 구체적으로 주민등록번호의 처리를 요구하거나 허용한 경우 외에는 주민등록번호를 처리할 수 없다. 개인정보처리자는 주민등록번호가 분실·도난·유출·위조·변조 또는 훼손되지 아니하도록 암호화 조치를 통하여 안전하게 보관하여야 한다.',
            contentEn: 'Resident registration numbers may only be processed when specifically required by law. They must be stored securely with encryption to prevent loss, theft, or leakage.',
            tags: ['privacy', 'kyc'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제25조',
            articleTitle: '영상정보처리기기 운영 제한',
            chapter: '제3장 개인정보의 처리',
            sortOrder: 9,
            content: '누구든지 다음 각 호의 경우를 제외하고는 공개된 장소에 영상정보처리기기를 설치·운영하여서는 아니 된다. 법령에서 구체적으로 허용한 경우, 범죄의 예방 및 수사를 위하여 필요한 경우, 시설안전 및 화재 예방을 위하여 필요한 경우 등. 영상정보처리기기운영자는 정보주체가 쉽게 인식할 수 있도록 안내판 설치 등 필요한 조치를 하여야 한다.',
            contentEn: 'CCTV installation in public areas is restricted except for specific legal purposes such as crime prevention, facility safety, and fire prevention. Operators must install notice signs.',
            tags: ['privacy', 'cctv'],
            appliesToBiz: ['exchange'],
          },
          {
            articleNum: '제29조',
            articleTitle: '안전조치 의무',
            chapter: '제4장 개인정보의 안전한 관리',
            sortOrder: 10,
            content: '개인정보처리자는 개인정보가 분실·도난·유출·위조·변조 또는 훼손되지 아니하도록 내부 관리계획 수립, 접속기록 보관 등 대통령령으로 정하는 바에 따라 안전성 확보에 필요한 기술적·관리적 및 물리적 조치를 하여야 한다. 이는 암호화, 접근통제, 침입방지시스템 설치, 보안 프로그램 설치 등을 포함한다. 개인정보 안전성 확보조치 기준 고시를 준수하여야 한다.',
            contentEn: 'Controllers must implement technical, administrative, and physical safeguards including internal management plans, access logs, encryption, access control, intrusion prevention, and security programs to prevent loss, theft, or alteration.',
            tags: ['privacy', 'iso', 'data-protection'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: '제30조',
            articleTitle: '개인정보 처리방침의 수립 및 공개',
            chapter: '제4장 개인정보의 안전한 관리',
            sortOrder: 11,
            content: '개인정보처리자는 개인정보의 처리 목적, 개인정보의 처리 및 보유 기간, 개인정보의 제3자 제공에 관한 사항, 개인정보처리의 위탁에 관한 사항, 정보주체와 법정대리인의 권리·의무 및 그 행사방법에 관한 사항이 포함된 개인정보 처리방침을 정하여야 한다. 개인정보처리자는 개인정보 처리방침을 수립하거나 변경하는 경우에는 정보주체가 쉽게 확인할 수 있도록 대통령령으로 정하는 방법에 따라 공개하여야 한다.',
            contentEn: 'Controllers must establish and publicly disclose a privacy policy covering processing purposes, retention periods, third-party provisions, processing delegation, and data subject rights.',
            tags: ['privacy', 'policy'],
            appliesToBiz: ['exchange', 'wallet-provider', 'nft-platform', 'defi-protocol'],
          },
          {
            articleNum: '제34조',
            articleTitle: '개인정보 유출 통지',
            chapter: '제4장 개인정보의 안전한 관리',
            sortOrder: 12,
            content: '개인정보처리자는 개인정보가 유출되었음을 알게 되었을 때에는 지체 없이 해당 정보주체에게 유출된 개인정보의 항목, 유출된 시점과 그 경위, 유출로 인하여 발생할 수 있는 피해를 최소화하기 위하여 정보주체가 할 수 있는 방법 등에 관한 사항을 알려야 한다. 개인정보처리자는 대통령령으로 정하는 규모 이상의 개인정보가 유출된 경우에는 72시간 이내에 보호위원회 또는 한국인터넷진흥원에 신고하여야 한다.',
            contentEn: 'Upon discovering a data breach, controllers must promptly notify affected data subjects of breached items, timing, cause, and mitigation measures. Large-scale breaches must be reported to PIPC or KISA within 72 hours.',
            tags: ['privacy', 'breach-notification'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: '제39조',
            articleTitle: '손해배상책임',
            chapter: '제8장 손해배상책임',
            sortOrder: 13,
            content: '정보주체는 개인정보처리자가 이 법을 위반한 행위로 손해를 입으면 개인정보처리자에게 손해배상을 청구할 수 있다. 이 경우 그 개인정보처리자는 고의 또는 과실이 없음을 입증하지 아니하면 책임을 면할 수 없다. 개인정보처리자의 고의 또는 중대한 과실로 인하여 개인정보가 분실·도난·유출·위조·변조 또는 훼손된 경우로서 정보주체에게 손해가 발생한 때에는 법원은 그 손해액의 3배를 넘지 아니하는 범위에서 손해배상액을 정할 수 있다.',
            contentEn: 'Data subjects may claim damages for PIPA violations. Controllers bear burden of proof for absence of fault. For willful or gross negligence causing data breach, courts may award punitive damages up to triple the actual damages.',
            tags: ['privacy', 'liability'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제39조의2',
            articleTitle: '법정손해배상',
            chapter: '제8장 손해배상책임',
            sortOrder: 14,
            content: '정보주체는 개인정보처리자의 고의 또는 과실로 인하여 개인정보가 분실·도난·유출·위조·변조 또는 훼손된 경우에는 300만원 이하의 범위에서 상당한 금액을 손해액으로 하여 배상을 청구할 수 있다. 이 경우 해당 개인정보처리자는 고의 또는 과실이 없음을 입증하지 아니하면 책임을 면할 수 없다. 법원은 변론 전체의 취지와 증거조사의 결과를 고려하여 손해액을 정할 수 있다.',
            contentEn: 'Statutory damages up to KRW 3 million per data subject may be claimed for breaches without proving actual damages. Controllers must prove absence of willful or negligent conduct to avoid liability.',
            tags: ['privacy', 'liability'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제71조',
            articleTitle: '벌칙',
            chapter: '제9장 벌칙',
            sortOrder: 15,
            content: '다음 각 호의 어느 하나에 해당하는 자는 5년 이하의 징역 또는 5천만원 이하의 벌금에 처한다. 제17조제1항제2호에 해당하지 아니함에도 같은 항 제1호를 위반하여 정보주체의 동의를 받지 아니하고 개인정보를 제3자에게 제공한 자 및 그 사정을 알고 개인정보를 제공받은 자. 제18조제1항·제2항, 제27조제3항 또는 제28조의2를 위반하여 개인정보를 이용하거나 제3자에게 제공한 자 및 그 사정을 알고 개인정보를 제공받은 자.',
            contentEn: 'Violations including unauthorized third-party provision or misuse beyond specified purposes are punishable by up to 5 years imprisonment or KRW 50 million fine. Recipients with knowledge are equally liable.',
            tags: ['privacy', 'penalties'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer'],
          },
        ],
      },
    },
  });

  // ============================================================
  // 2. 전자상거래법
  // ============================================================
  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'KR', lawNumber: 'KR-ECommerce-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'KR',
      lawType: 'law',
      regulator: '공정거래위원회 / KFTC',
      title: '전자상거래 등에서의 소비자보호에 관한 법률',
      titleEn: 'Act on Consumer Protection in Electronic Commerce',
      lawNumber: 'KR-ECommerce-EXPANDED',
      status: 'enacted',
      enactedDate: new Date('2002-03-30'),
      effectiveDate: new Date('2002-07-01'),
      lastAmendedDate: new Date('2024-02-06'),
      totalArticles: 12,
      articles: {
        create: [
          {
            articleNum: '제2조',
            articleTitle: '정의',
            chapter: '제1장 총칙',
            sortOrder: 1,
            content: '"전자상거래"란 전자거래의 방법으로 상행위를 하는 것을 말한다. "통신판매"란 우편·전기통신, 그 밖에 총리령으로 정하는 방법에 따라 재화 또는 용역의 판매에 관한 정보를 제공하고 소비자의 청약을 받아 재화 또는 용역을 판매하는 것을 말한다. "통신판매중개"란 사이버몰의 이용을 허락하거나 그 밖에 총리령으로 정하는 방법으로 거래 당사자 간의 통신판매를 알선하는 행위를 말한다.',
            contentEn: '"E-commerce" means commercial activity via electronic transactions. "Mail-order sales" means selling goods/services after providing information and receiving orders. "Mail-order brokerage" includes providing a cybermall platform.',
            tags: ['consumer-protection', 'definitions'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제8조',
            articleTitle: '조작 실수 등의 방지',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 2,
            content: '사업자는 전자상거래에서 소비자의 조작 실수 등으로 인한 의사표시의 착오 등으로 발생하는 피해를 예방할 수 있도록 거래대금이 부과되는 시점이나 청약 직전에 그 재화등의 내용, 가격, 배송료 등 확인이나 정정에 필요한 절차를 마련하여야 한다. 화면 확인 및 정정 기능을 제공하여야 한다.',
            contentEn: 'Businesses must provide confirmation and correction procedures before charging to prevent consumer errors. A review and correction interface must be provided before order submission.',
            tags: ['consumer-protection'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제13조',
            articleTitle: '신원 및 거래조건에 대한 정보의 제공',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 3,
            content: '통신판매업자는 재화등의 거래에 관한 청약을 받을 때까지 상호 및 대표자 성명, 주소·전화번호·전자우편주소, 재화의 명칭·종류 및 내용, 가격과 지급방법, 공급방법·시기, 청약철회의 기한·행사방법·효과에 관한 사항 등을 소비자가 쉽게 알 수 있도록 표시·광고 또는 고지하여야 한다. 소비자는 이러한 정보를 언제든지 확인할 수 있어야 한다.',
            contentEn: 'Mail-order businesses must clearly disclose company name, representative, contact information, product details, price, payment, delivery terms, and withdrawal rights before accepting orders.',
            tags: ['consumer-protection', 'disclosure'],
            appliesToBiz: ['exchange', 'nft-platform', 'ico-issuer'],
          },
          {
            articleNum: '제15조',
            articleTitle: '재화등의 공급',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 4,
            content: '통신판매업자는 소비자가 청약을 한 날부터 7일 이내에 재화등의 공급에 필요한 조치를 하여야 하고, 소비자가 재화등을 공급받기 전에 미리 재화등의 대금을 전부 또는 일부 지급하는 통신판매의 경우에는 소비자가 그 대금을 전부 또는 일부 지급한 날부터 3영업일 이내에 재화등의 공급을 위하여 필요한 조치를 하여야 한다.',
            contentEn: 'Mail-order businesses must take supply measures within 7 days of order, or within 3 business days of payment for prepaid transactions.',
            tags: ['consumer-protection'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제17조',
            articleTitle: '청약철회',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 5,
            content: '통신판매업자와 재화등의 구매에 관한 계약을 체결한 소비자는 계약내용에 관한 서면을 받은 날부터 7일 이내에 청약철회등을 할 수 있다. 그 서면을 받은 때보다 재화등의 공급이 늦게 이루어진 경우에는 재화등을 공급받거나 재화등의 공급이 시작된 날부터 7일 이내에 철회할 수 있다. 다만, 디지털 콘텐츠 등 일부 재화는 철회가 제한될 수 있다.',
            contentEn: 'Consumers may withdraw orders within 7 days of receiving contract documentation or goods delivery. Digital content and certain goods may have withdrawal restrictions.',
            tags: ['consumer-protection', 'withdrawal'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제18조',
            articleTitle: '청약철회의 효과',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 6,
            content: '소비자는 청약철회등을 한 경우에는 이미 공급받은 재화등을 반환하여야 한다. 통신판매업자는 재화등을 반환받은 날부터 3영업일 이내에 이미 지급받은 재화등의 대금을 환급하여야 한다. 통신판매업자가 환급을 지연한 때에는 그 지연기간에 대하여 연 100분의 15 이내의 지연이자를 함께 환급하여야 한다.',
            contentEn: 'Upon withdrawal, consumers must return goods and businesses must refund within 3 business days of receipt. Delayed refunds incur interest up to 15% annually.',
            tags: ['consumer-protection', 'refund'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제19조',
            articleTitle: '손해배상청구금액의 제한',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 7,
            content: '소비자에게 책임이 있는 사유로 재화등이 멸실되거나 훼손된 경우 또는 소비자의 사용 또는 일부 소비에 의하여 재화등의 가치가 현저히 감소한 경우 등에는 통신판매업자가 소비자에게 청구하는 손해배상액은 일정한 금액을 초과할 수 없다. 그 기준은 재화등이 반환되거나 그 반환이 요청된 시점에서의 재화등의 판매가격의 한도 내에서 정한다.',
            contentEn: 'Damages claimed by businesses for consumer-caused loss or damage are capped and cannot exceed the sale price of the returned goods.',
            tags: ['consumer-protection'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제20조',
            articleTitle: '통신판매중개업자의 책임',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 8,
            content: '통신판매중개자는 자신이 통신판매의 당사자가 아니라는 사실을 소비자가 쉽게 알 수 있도록 미리 고지하여야 한다. 고지하지 아니한 경우에는 통신판매중개의뢰자의 고의 또는 과실로 소비자에게 발생한 재산상 손해에 대하여 통신판매중개의뢰자와 연대하여 배상할 책임을 진다. NFT 마켓플레이스 등 중개 플랫폼에 중요한 조항이다.',
            contentEn: 'Mail-order brokers must clearly disclose they are not a party to transactions. Without such disclosure, brokers are jointly liable with sellers for damages. Critical for NFT marketplaces and exchange platforms.',
            tags: ['consumer-protection', 'broker-liability'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제20조의2',
            articleTitle: '통신판매중개업자의 의무',
            chapter: '제2장 전자상거래 및 통신판매',
            sortOrder: 9,
            content: '통신판매중개업자는 통신판매중개의뢰자의 신원정보를 확인하고 소비자에게 제공할 의무를 부담하며, 소비자 피해 발생 시 적절한 조치를 취해야 한다. 중개업자는 판매자의 성명, 주소, 전화번호 등을 소비자의 요청이 있는 경우 신속하게 제공해야 한다. 분쟁 해결 절차를 마련하여야 한다.',
            contentEn: 'Brokers must verify seller identity information and provide it to consumers upon request. They must establish dispute resolution procedures and take appropriate action for consumer complaints.',
            tags: ['consumer-protection'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제21조',
            articleTitle: '금지행위',
            chapter: '제3장 소비자권익의 보호',
            sortOrder: 10,
            content: '전자상거래를 하는 사업자 또는 통신판매업자는 거짓 또는 과장된 사실을 알리거나 기만적 방법을 사용하여 소비자를 유인 또는 거래하거나 청약철회등 또는 계약의 해지를 방해하는 행위를 하여서는 아니 된다. 주소·전화번호·인터넷도메인 이름 등의 정확한 사실을 알 수 있는 사항을 표시하지 아니하거나 허위로 표시하는 행위도 금지된다.',
            contentEn: 'Businesses are prohibited from making false or exaggerated representations, using deceptive methods, obstructing withdrawal rights, or providing false contact information.',
            tags: ['consumer-protection', 'prohibited-acts'],
            appliesToBiz: ['exchange', 'nft-platform', 'ico-issuer'],
          },
          {
            articleNum: '제24조',
            articleTitle: '시정조치',
            chapter: '제4장 조사 및 감독',
            sortOrder: 11,
            content: '공정거래위원회는 사업자가 이 법을 위반한 경우 해당 위반행위의 중지, 이 법에 규정된 의무의 이행, 시정조치를 받은 사실의 공표, 소비자피해 예방 및 구제에 필요한 조치 등을 명할 수 있다. 또한 위반행위에 대하여 관련 매출액의 100분의 5를 곱한 금액을 초과하지 아니하는 범위에서 과징금을 부과할 수 있다.',
            contentEn: 'The KFTC may order cessation of violations, compliance, public disclosure of violations, consumer protection measures, and impose penalties up to 5% of related revenue.',
            tags: ['consumer-protection', 'enforcement'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
          {
            articleNum: '제40조',
            articleTitle: '벌칙',
            chapter: '제5장 벌칙',
            sortOrder: 12,
            content: '제21조제1항을 위반하여 거짓 또는 과장된 사실을 알리거나 기만적 방법을 사용하여 소비자를 유인 또는 거래한 자는 3년 이하의 징역 또는 1억원 이하의 벌금에 처한다. 청약철회등을 방해하거나 중요 사항을 표시하지 아니한 자도 처벌 대상이 된다. 법인의 대표자나 법인 또는 개인의 대리인, 사용인, 그 밖의 종업원이 그 법인 또는 개인의 업무에 관하여 위반행위를 하면 양벌규정이 적용된다.',
            contentEn: 'False advertising or deceptive consumer inducement is punishable by up to 3 years imprisonment or KRW 100 million fine. Joint liability applies to corporations and their representatives.',
            tags: ['consumer-protection', 'penalties'],
            appliesToBiz: ['exchange', 'nft-platform'],
          },
        ],
      },
    },
  });

  // ============================================================
  // 3. 외국환거래법
  // ============================================================
  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'KR', lawNumber: 'KR-FETA-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'KR',
      lawType: 'law',
      regulator: '기획재정부 / 한국은행',
      title: '외국환거래법',
      titleEn: 'Foreign Exchange Transactions Act',
      lawNumber: 'KR-FETA-EXPANDED',
      status: 'enacted',
      enactedDate: new Date('1998-09-16'),
      effectiveDate: new Date('1999-04-01'),
      lastAmendedDate: new Date('2024-08-30'),
      totalArticles: 12,
      articles: {
        create: [
          {
            articleNum: '제3조',
            articleTitle: '정의',
            chapter: '제1장 총칙',
            sortOrder: 1,
            content: '이 법에서 사용하는 용어의 뜻은 다음과 같다. "외국환"이란 대외지급수단, 외화증권, 외화파생상품 및 외화채권을 말한다. "지급수단"이란 정부지폐, 은행권, 주화, 수표, 우편환, 신용장 등을 말한다. "대외지급수단"이란 외국통화, 외국통화로 표시된 지급수단, 그 밖에 표시통화에 관계없이 외국에서 사용할 수 있는 지급수단을 말한다. 최근 개정으로 가상자산 또한 일부 외환거래 규제 대상이 되었다.',
            contentEn: 'Definitions include foreign exchange (foreign currency, securities, derivatives, bonds), payment instruments, and external payment means. Recent amendments bring virtual assets partially under FX regulation scope.',
            tags: ['foreign-exchange', 'definitions'],
            appliesToBiz: ['exchange', 'stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: '제8조',
            articleTitle: '외국환업무의 등록 등',
            chapter: '제2장 외국환업무 취급기관 등',
            sortOrder: 2,
            content: '외국환업무를 업으로 하려는 자는 대통령령으로 정하는 바에 따라 기획재정부장관에게 등록하여야 한다. 금융회사등이 아닌 자가 외국환업무를 업으로 하려는 경우에는 외국환업무에 필요한 자본·시설 및 전문인력을 갖추어야 한다. 등록한 외국환업무 취급기관은 외국환거래에 관한 기록을 보관하여야 한다.',
            contentEn: 'Persons conducting foreign exchange business must register with the Ministry of Economy and Finance, meeting capital, facility, and personnel requirements. Registered institutions must maintain FX transaction records.',
            tags: ['foreign-exchange', 'licensing'],
            appliesToBiz: ['exchange', 'stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: '제9조',
            articleTitle: '외국환중개업무 등',
            chapter: '제2장 외국환업무 취급기관 등',
            sortOrder: 3,
            content: '외국통화 간의 매매, 외국통화와 내국통화 간의 매매 및 그 중개·대리·매매의 위탁·수탁 등의 업무를 하려는 자는 대통령령으로 정하는 자본·시설 및 전문인력 등의 요건을 갖추어 기획재정부장관의 인가를 받아야 한다. 외국환중개회사는 기획재정부장관의 승인을 받아 외국환중개업무 외의 업무를 할 수 있다.',
            contentEn: 'FX brokerage between currencies requires authorization from the Ministry of Economy and Finance with required capital, facilities, and personnel. Brokers may conduct additional business with approval.',
            tags: ['foreign-exchange', 'brokerage'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제15조',
            articleTitle: '지급 등의 절차',
            chapter: '제3장 외국환평형기금',
            sortOrder: 4,
            content: '기획재정부장관은 이 법의 실효성을 확보하기 위하여 필요하다고 인정하여 대통령령으로 정하는 경우에는 지급 또는 수령을 하려는 자로 하여금 그 지급 또는 수령을 할 때 지급 또는 수령의 사유와 금액을 확인하도록 하거나 외국환업무취급기관에 신고하도록 할 수 있다. 크립토 거래소를 통한 송금에도 적용된다.',
            contentEn: 'The Ministry may require persons making payments to verify purposes and amounts or report to FX business institutions. Applicable to crypto exchange remittances.',
            tags: ['foreign-exchange', 'reporting'],
            appliesToBiz: ['exchange', 'payment-service', 'stablecoin-issuer'],
          },
          {
            articleNum: '제16조',
            articleTitle: '지급 또는 수령의 방법',
            chapter: '제4장 지급과 거래',
            sortOrder: 5,
            content: '거주자 간, 거주자와 비거주자 간 또는 비거주자 상호 간의 거래나 행위에 따른 채권·채무를 결제할 때 거주자가 상계 등의 방법으로 채권·채무를 소멸시키거나 상쇄시키는 방법, 기획재정부장관이 정하는 기간을 넘겨 결제하는 방법, 거주자가 해당 거래의 당사자가 아닌 자와 지급 또는 수령을 하거나 해당 거래의 당사자가 아닌 거주자가 그 거래의 당사자인 거주자를 갈음하여 지급 또는 수령을 하는 방법에 해당하면 신고하여야 한다.',
            contentEn: 'Residents must report payment methods involving offsetting, delayed settlement beyond prescribed periods, or payments through non-parties to the transaction.',
            tags: ['foreign-exchange', 'settlement'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제17조',
            articleTitle: '지급수단등의 수출입',
            chapter: '제4장 지급과 거래',
            sortOrder: 6,
            content: '기획재정부장관은 이 법의 실효성을 확보하기 위하여 필요하다고 인정되어 대통령령으로 정하는 경우에는 지급수단 또는 증권을 수출 또는 수입하려는 거주자나 비거주자로 하여금 그 지급수단 또는 증권을 수출 또는 수입할 때 신고하게 할 수 있다. USD 1만 이상의 지급수단 휴대 반출입은 세관에 신고가 필요하다.',
            contentEn: 'The Ministry may require reporting of import/export of payment instruments and securities. Carrying payment instruments over USD 10,000 requires customs declaration.',
            tags: ['foreign-exchange', 'customs'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제18조',
            articleTitle: '자본거래의 신고 등',
            chapter: '제4장 지급과 거래',
            sortOrder: 7,
            content: '자본거래를 하려는 자는 기획재정부장관에게 신고하여야 한다. 다만, 경미하거나 정형화된 자본거래로서 대통령령으로 정하는 자본거래는 사후 보고하거나 신고하지 아니할 수 있다. 해외투자, 해외부동산 취득, 해외예금 등이 포함되며, 해외 가상자산 투자의 경우에도 신고 의무가 발생할 수 있다.',
            contentEn: 'Capital transactions must be reported to the Ministry of Economy and Finance, with exceptions for minor or standardized transactions. Includes overseas investments, real estate, deposits, and potentially overseas virtual asset investments.',
            tags: ['foreign-exchange', 'capital-transactions'],
            appliesToBiz: ['exchange', 'fund-manager', 'stablecoin-issuer'],
          },
          {
            articleNum: '제19조',
            articleTitle: '외환거래 정보의 보관·관리',
            chapter: '제5장 외국환거래 정보',
            sortOrder: 8,
            content: '외국환업무취급기관은 외국환거래에 관한 장부 및 서류를 5년간 보관하여야 한다. 기획재정부장관 또는 한국은행 총재는 필요한 경우 자료 제출을 요구할 수 있으며 요구를 받은 자는 이에 응하여야 한다. 자금세탁방지 및 공중협박자금조달금지를 위한 기록 보관 의무도 병행된다.',
            contentEn: 'FX business institutions must retain transaction books and records for 5 years. The Ministry and Bank of Korea may request data. Parallel AML/CFT record-keeping obligations apply.',
            tags: ['foreign-exchange', 'recordkeeping', 'aml'],
            appliesToBiz: ['exchange', 'payment-service', 'stablecoin-issuer'],
          },
          {
            articleNum: '제20조',
            articleTitle: '사후관리',
            chapter: '제5장 외국환거래 정보',
            sortOrder: 9,
            content: '기획재정부장관은 이 법의 시행을 위하여 필요하다고 인정할 때에는 외국환업무취급기관등에 대하여 필요한 명령을 하거나 그 업무에 관하여 검사를 할 수 있다. 검사 결과 위반사항이 발견된 때에는 시정명령이나 업무정지, 등록취소 등의 처분을 할 수 있다. 한국은행 및 금융감독원이 검사 업무를 위탁받아 수행한다.',
            contentEn: 'The Ministry may issue orders or conduct inspections. Violations may result in corrective orders, business suspension, or registration cancellation. The Bank of Korea and FSS may conduct inspections.',
            tags: ['foreign-exchange', 'supervision'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제21조',
            articleTitle: '외국환거래의 정지 등',
            chapter: '제6장 보칙',
            sortOrder: 10,
            content: '기획재정부장관은 천재지변, 전시·사변, 국내외 경제사정의 중대하고도 급격한 변동, 그 밖에 이에 준하는 사태가 발생하여 부득이하다고 인정되는 경우에는 외국환거래의 전부 또는 일부에 대한 일시 정지, 지급수단·귀금속의 지정 거래소에서의 매매, 외화채권을 보유한 자의 신고 등의 조치를 할 수 있다. 국가 비상시 외환통제 수단이다.',
            contentEn: 'During emergencies such as war, natural disasters, or severe economic disturbances, the Ministry may suspend FX transactions, designate trading venues, or require reporting of foreign currency holdings.',
            tags: ['foreign-exchange', 'emergency'],
            appliesToBiz: ['exchange', 'stablecoin-issuer'],
          },
          {
            articleNum: '제27조',
            articleTitle: '벌칙',
            chapter: '제7장 벌칙',
            sortOrder: 11,
            content: '제15조제2항, 제16조, 제17조, 제18조제1항, 제21조에 따른 허가를 받지 아니하거나 신고를 하지 아니하고 지급 등 또는 자본거래를 한 자는 5년 이하의 징역 또는 거래금액의 3배 이하의 벌금에 처한다. 다만, 해당 거래금액의 3배가 5천만원 이하인 경우에는 벌금의 상한액을 5천만원으로 한다. 미등록 외국환업무는 더 엄중히 처벌된다.',
            contentEn: 'Unauthorized payments, capital transactions, or unregistered FX business are punishable by up to 5 years imprisonment or fine up to triple the transaction value (minimum KRW 50 million cap).',
            tags: ['foreign-exchange', 'penalties'],
            appliesToBiz: ['exchange', 'payment-service', 'stablecoin-issuer'],
          },
          {
            articleNum: '제29조',
            articleTitle: '양벌규정',
            chapter: '제7장 벌칙',
            sortOrder: 12,
            content: '법인의 대표자나 법인 또는 개인의 대리인, 사용인, 그 밖의 종업원이 그 법인 또는 개인의 업무에 관하여 제27조, 제27조의2 또는 제28조의 어느 하나에 해당하는 위반행위를 하면 그 행위자를 벌하는 외에 그 법인 또는 개인에게도 해당 조문의 벌금형을 과한다. 다만, 법인 또는 개인이 그 위반행위를 방지하기 위하여 해당 업무에 관하여 상당한 주의와 감독을 게을리하지 아니한 경우에는 그러하지 아니하다.',
            contentEn: 'Joint liability provision: corporations and individuals are liable for violations by representatives, agents, employees, unless they proved due diligence in supervision.',
            tags: ['foreign-exchange', 'penalties'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
        ],
      },
    },
  });

  // ============================================================
  // 4. 정보통신망법
  // ============================================================
  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'KR', lawNumber: 'KR-NetworkAct-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'KR',
      lawType: 'law',
      regulator: '방송통신위원회 / KISA',
      title: '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
      titleEn: 'Act on Promotion of Information and Communications Network Utilization and Information Protection',
      lawNumber: 'KR-NetworkAct-EXPANDED',
      status: 'enacted',
      enactedDate: new Date('2001-01-16'),
      effectiveDate: new Date('2001-07-01'),
      lastAmendedDate: new Date('2024-01-23'),
      totalArticles: 12,
      articles: {
        create: [
          {
            articleNum: '제2조',
            articleTitle: '정의',
            chapter: '제1장 총칙',
            sortOrder: 1,
            content: '"정보통신망"이란 전기통신설비를 이용하거나 전기통신설비와 컴퓨터 및 컴퓨터의 이용기술을 활용하여 정보를 수집·가공·저장·검색·송신 또는 수신하는 정보통신체제를 말한다. "정보통신서비스 제공자"란 전기통신사업자와 영리를 목적으로 전기통신사업자의 전기통신역무를 이용하여 정보를 제공하거나 정보의 제공을 매개하는 자를 말한다. 암호화폐 거래소는 전형적인 정보통신서비스 제공자에 해당된다.',
            contentEn: 'Definitions: "Information and communications network" means ICT systems; "Service provider" includes telecom operators and commercial information service providers. Crypto exchanges are typical ICT service providers.',
            tags: ['privacy', 'definitions'],
            appliesToBiz: ['exchange', 'wallet-provider', 'nft-platform'],
          },
          {
            articleNum: '제22조',
            articleTitle: '개인정보의 수집·이용 동의',
            chapter: '제4장 개인정보의 보호',
            sortOrder: 2,
            content: '정보통신서비스 제공자는 이용자의 개인정보를 이용하려고 수집하는 경우 이용자에게 개인정보의 수집·이용 목적, 수집하는 개인정보의 항목, 개인정보의 보유·이용 기간을 알리고 동의를 받아야 한다. 이용자가 필요한 최소한의 개인정보 외의 개인정보를 제공하지 아니한다는 이유로 그 서비스의 제공을 거부하여서는 아니 된다.',
            contentEn: 'ICT service providers must obtain user consent after disclosing purpose, items, and retention period. They cannot refuse service for users declining non-essential data collection.',
            tags: ['privacy', 'consent'],
            appliesToBiz: ['exchange', 'wallet-provider', 'nft-platform'],
          },
          {
            articleNum: '제23조',
            articleTitle: '개인정보의 수집 제한',
            chapter: '제4장 개인정보의 보호',
            sortOrder: 3,
            content: '정보통신서비스 제공자는 사상, 신념, 가족 및 친인척관계, 학력·병력, 기타 사회활동 경력 등 개인의 권리·이익이나 사생활을 뚜렷하게 침해할 우려가 있는 개인정보를 수집하여서는 아니 된다. 다만, 이용자의 동의를 받거나 다른 법률에 따라 특별히 수집 대상 개인정보로 허용된 경우에는 그러하지 아니하다.',
            contentEn: 'ICT providers shall not collect sensitive personal information such as ideology, beliefs, family relations, or medical history without explicit consent or legal authorization.',
            tags: ['privacy', 'sensitive-data'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제25조',
            articleTitle: '개인정보의 위탁',
            chapter: '제4장 개인정보의 보호',
            sortOrder: 4,
            content: '정보통신서비스 제공자는 제3자에게 이용자의 개인정보를 수집·보관·처리·이용·제공·관리·파기 등을 할 수 있도록 업무를 위탁하는 경우에는 위탁하는 업무의 내용과 수탁자를 이용자에게 알리고 동의를 받아야 한다. 다만, 정보통신서비스의 제공에 관한 계약을 이행하기 위하여 필요한 경우로서 이용자의 편의 증진 등을 위하여 필요한 경우에는 일정한 방법에 따라 이를 이용자에게 알리거나 공개함으로써 고지절차와 동의절차를 거치지 아니할 수 있다.',
            contentEn: 'When delegating personal data processing to third parties, ICT providers must disclose the delegated tasks and delegatees and obtain consent, except for service contract fulfillment where notification/disclosure may substitute.',
            tags: ['privacy', 'delegation'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제27조의2',
            articleTitle: '개인정보 유출등의 통지·신고',
            chapter: '제4장 개인정보의 보호',
            sortOrder: 5,
            content: '정보통신서비스 제공자는 개인정보의 분실·도난·누출 사실을 안 때에는 지체 없이 해당 이용자에게 유출된 개인정보의 항목, 유출된 시점과 그 경위, 유출로 인하여 발생할 수 있는 피해를 최소화하기 위하여 이용자가 할 수 있는 방법 등에 관한 사항을 알리고 방송통신위원회 또는 한국인터넷진흥원에 신고하여야 한다. 24시간 이내 신고가 원칙이다.',
            contentEn: 'Upon discovering data breach, ICT providers must promptly notify users of breached items, timing, cause, and mitigation measures, and report to KCC or KISA within 24 hours.',
            tags: ['privacy', 'breach-notification'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
          },
          {
            articleNum: '제28조',
            articleTitle: '개인정보의 보호조치',
            chapter: '제4장 개인정보의 보호',
            sortOrder: 6,
            content: '정보통신서비스 제공자는 이용자의 개인정보를 취급할 때에는 개인정보의 분실·도난·누출·변조 또는 훼손을 방지하기 위하여 개인정보 보호조치 기준에 따른 기술적·관리적 조치를 하여야 한다. 개인정보에 대한 불법적인 접근을 차단하기 위한 침입차단시스템 등 접근 통제장치의 설치·운영, 접속기록의 위조·변조 방지를 위한 조치, 개인정보를 안전하게 저장·전송할 수 있는 암호화 기술의 적용 등이 포함된다.',
            contentEn: 'ICT providers must implement technical and managerial measures including firewalls, access control, log integrity protection, and encryption to prevent loss, theft, leakage, or alteration of personal data.',
            tags: ['privacy', 'iso', 'data-protection'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
          },
          {
            articleNum: '제29조',
            articleTitle: '개인정보의 파기',
            chapter: '제4장 개인정보의 보호',
            sortOrder: 7,
            content: '정보통신서비스 제공자는 수집한 개인정보의 이용목적을 달성하였거나 이용자가 동의를 철회한 경우에는 지체 없이 해당 개인정보를 복구·재생할 수 없도록 파기하여야 한다. 다만, 다른 법률에 따라 보존하여야 할 의무가 있는 경우에는 그 보존기간 동안 해당 개인정보를 보존할 수 있다. 1년간 서비스를 이용하지 아니한 이용자의 개인정보는 별도 저장·관리하여야 한다.',
            contentEn: 'ICT providers must irrecoverably destroy personal data upon purpose fulfillment or consent withdrawal. Data of inactive users (1+ year) must be separately stored, with exceptions for legal retention obligations.',
            tags: ['privacy', 'retention'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제45조',
            articleTitle: '정보보호조치',
            chapter: '제6장 정보통신망의 안정성 확보',
            sortOrder: 8,
            content: '정보통신서비스 제공자는 정보통신서비스의 제공에 사용되는 정보통신망의 안정성 및 정보의 신뢰성을 확보하기 위한 보호조치를 하여야 한다. 과학기술정보통신부장관은 정보보호조치에 관한 지침을 정하여 고시하고 정보통신서비스 제공자에게 이를 지키도록 권고할 수 있다. 보호조치는 침해사고 예방 및 대응조치를 포함한다.',
            contentEn: 'ICT providers must implement information security measures for network stability and data reliability. MSIT may issue guidelines and recommend compliance. Measures include incident prevention and response.',
            tags: ['iso', 'cybersecurity'],
            appliesToBiz: ['exchange', 'wallet-provider', 'nft-platform'],
          },
          {
            articleNum: '제45조의2',
            articleTitle: '정보보호 사전점검',
            chapter: '제6장 정보통신망의 안정성 확보',
            sortOrder: 9,
            content: '정보통신서비스 제공자는 정보통신망의 설계·구축 등 정보통신망에 중대한 변경이 발생할 때에 대통령령으로 정하는 바에 따라 사전에 정보보호에 관한 점검을 하여야 한다. 과학기술정보통신부장관은 정보보호 사전점검의 기준·방법·절차 등을 정하여 고시할 수 있다. 신규 서비스 출시 전 보안 취약점 점검이 의무화된다.',
            contentEn: 'ICT providers must conduct pre-security assessments when making significant network changes. MSIT may prescribe assessment standards. Security vulnerability checks are mandatory before new service launches.',
            tags: ['iso', 'cybersecurity'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제45조의3',
            articleTitle: '정보보호 최고책임자의 지정',
            chapter: '제6장 정보통신망의 안정성 확보',
            sortOrder: 10,
            content: '정보통신서비스 제공자는 정보통신시스템 등에 대한 보안 및 정보의 안전한 관리를 위하여 임원급의 정보보호 최고책임자(CISO)를 지정하여 과학기술정보통신부장관에게 신고하여야 한다. CISO는 정보보호관리체계의 수립 및 관리·운영, 정보보호 취약점 분석·평가 및 개선, 침해사고의 예방 및 대응 등의 업무를 수행한다. 일정 규모 이상의 사업자는 CISO의 겸직이 제한된다.',
            contentEn: 'ICT providers must designate an executive-level Chief Information Security Officer (CISO) and report to MSIT. CISOs oversee ISMS, vulnerability assessment, and incident response. Large providers face CISO concurrent position restrictions.',
            tags: ['iso', 'ciso', 'governance'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer'],
          },
          {
            articleNum: '제46조',
            articleTitle: '집적정보통신시설의 보호',
            chapter: '제6장 정보통신망의 안정성 확보',
            sortOrder: 11,
            content: '타인의 정보통신서비스 제공을 위하여 집적된 정보통신시설을 운영·관리하는 사업자는 정보통신시설을 안정적으로 운영하기 위하여 대통령령으로 정하는 바에 따라 물리적·기술적 보호조치를 하여야 한다. 집적정보통신시설 사업자는 그가 관리하는 집적정보통신시설의 멸실, 훼손 또는 그 밖의 운영장애로 발생한 피해를 보상하기 위하여 보험에 가입하여야 한다. 데이터센터 운영자의 보험 가입이 의무화된다.',
            contentEn: 'Operators of integrated ICT facilities (data centers) must implement physical and technical protection measures, and must maintain insurance for damages from facility loss, damage, or operational failures.',
            tags: ['iso', 'cybersecurity'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: '제74조',
            articleTitle: '벌칙',
            chapter: '제9장 벌칙',
            sortOrder: 12,
            content: '다음 각 호의 어느 하나에 해당하는 자는 1년 이하의 징역 또는 1천만원 이하의 벌금에 처한다. 음란한 부호·문언·음향·화상 또는 영상을 배포·판매·임대하거나 공공연하게 전시한 자, 공포심이나 불안감을 유발하는 부호·문언·음향·화상 또는 영상을 반복적으로 상대방에게 도달하게 한 자, 정당한 사유 없이 정보통신시스템 등의 운용을 방해할 수 있는 프로그램을 전달 또는 유포한 자. 개인정보보호조치 위반은 별도의 벌칙 조항이 적용된다.',
            contentEn: 'Penalties up to 1 year imprisonment or KRW 10 million fine for distributing obscene content, repeated harassment, or unauthorized malicious programs. Separate penalty provisions apply to personal data protection violations.',
            tags: ['penalties'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
        ],
      },
    },
  });

  // ============================================================
  // 5. 신용정보법
  // ============================================================
  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'KR', lawNumber: 'KR-CIA-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'KR',
      lawType: 'law',
      regulator: '금융위원회 / 금융감독원',
      title: '신용정보의 이용 및 보호에 관한 법률',
      titleEn: 'Credit Information Use and Protection Act',
      lawNumber: 'KR-CIA-EXPANDED',
      status: 'enacted',
      enactedDate: new Date('1995-01-05'),
      effectiveDate: new Date('1995-07-06'),
      lastAmendedDate: new Date('2024-08-14'),
      totalArticles: 10,
      articles: {
        create: [
          {
            articleNum: '제2조',
            articleTitle: '정의',
            chapter: '제1장 총칙',
            sortOrder: 1,
            content: '"신용정보"란 금융거래 등 상거래에서 거래 상대방의 신용을 판단할 때 필요한 정보로서 특정 신용정보주체를 식별할 수 있는 정보, 신용정보주체의 거래내용을 판단할 수 있는 정보, 신용정보주체의 신용도를 판단할 수 있는 정보 등을 말한다. "개인신용정보"란 기업 및 법인에 관한 정보를 제외한 살아 있는 개인에 관한 신용정보를 말한다. "가명정보"도 포함된다.',
            contentEn: 'Definitions: "Credit information" includes data needed to judge counterparty creditworthiness in financial transactions. "Personal credit information" excludes corporate data. Pseudonymized information is also included.',
            tags: ['credit', 'definitions'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제15조',
            articleTitle: '수집 및 처리의 원칙',
            chapter: '제3장 신용정보의 수집·조사 및 처리',
            sortOrder: 2,
            content: '신용정보회사등은 신용정보를 수집하고 이를 처리할 수 있다. 이 경우 이 법 또는 정관으로 정한 업무 범위에서 수집 및 처리의 목적을 명확히 하여야 하며, 그 목적에 필요한 범위에서 합리적이고 공정한 수단을 사용하여야 한다. 신용정보회사등은 개인신용정보를 수집하는 때에는 해당 신용정보주체의 동의를 받아야 한다.',
            contentEn: 'Credit information companies must clarify collection purposes within business scope and use reasonable and fair means. Personal credit information collection requires data subject consent.',
            tags: ['credit', 'principles'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제16조',
            articleTitle: '수집·조사 및 처리의 제한',
            chapter: '제3장 신용정보의 수집·조사 및 처리',
            sortOrder: 3,
            content: '신용정보회사등은 국가의 안보 및 기밀에 관한 정보, 기업의 영업비밀 또는 독창적인 연구개발정보, 개인의 정치적 사상, 종교적 신념, 그 밖에 신용정보와 관계없는 사생활에 관한 정보, 확실하지 아니한 개인신용정보 등을 수집·조사하여서는 아니 된다. 범죄경력정보도 원칙적으로 수집이 제한된다.',
            contentEn: 'Credit information companies may not collect national security data, trade secrets, political/religious beliefs, unrelated privacy data, uncertain personal credit data, or criminal records in principle.',
            tags: ['credit', 'restrictions'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제17조',
            articleTitle: '처리위탁',
            chapter: '제3장 신용정보의 수집·조사 및 처리',
            sortOrder: 4,
            content: '신용정보회사등은 제3자에게 신용정보의 처리 업무를 위탁할 수 있다. 다만, 대통령령으로 정하는 신용정보의 처리 위탁에 대해서는 금융위원회에 미리 신고하여야 한다. 신용정보회사등은 신용정보의 처리를 위탁하는 경우 제3자의 안전한 신용정보 처리를 위하여 관리적·기술적 보호조치 등을 문서에 포함하여야 한다.',
            contentEn: 'Credit information companies may delegate processing to third parties but must report certain delegations to the Financial Services Commission in advance and include protective measures in contracts.',
            tags: ['credit', 'delegation'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제18조',
            articleTitle: '제3자 제공',
            chapter: '제3장 신용정보의 수집·조사 및 처리',
            sortOrder: 5,
            content: '신용정보회사등은 신용정보를 타인에게 제공하는 경우 신용정보주체의 동의를 받아야 한다. 신용정보회사등은 개인신용정보를 타인에게 제공하는 경우에는 제공할 때마다 미리 개별적으로 동의를 받아야 한다. 다만, 개인신용정보를 제공받는 자가 해당 개인신용정보를 제공받은 사유에 따른 목적으로만 사용하는 경우에는 그러하지 아니할 수 있다.',
            contentEn: 'Credit information providers must obtain data subject consent for third-party provision. Personal credit information requires individual consent per provision, with exceptions for recipients using data only for original purposes.',
            tags: ['credit', 'third-party'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제19조',
            articleTitle: '개인신용정보의 활용에 관한 동의',
            chapter: '제3장 신용정보의 수집·조사 및 처리',
            sortOrder: 6,
            content: '신용정보제공·이용자가 개인신용정보를 수집하여 신용정보회사, 신용정보집중기관 및 개인신용평가회사에 제공하는 경우에는 해당 개인으로부터 서면, 전자적 형태 등의 방법으로 동의를 받아야 한다. 동의 사항은 개인신용정보를 제공받는 자, 제공받는 자의 이용 목적, 제공할 개인신용정보의 내용, 제공받는 자의 개인신용정보 보유기간 및 이용기간 등을 포함한다.',
            contentEn: 'Credit information providers must obtain written or electronic consent when providing personal credit data to credit companies, bureaus, or scoring agencies, disclosing recipient, purpose, content, and retention period.',
            tags: ['credit', 'consent'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제20조',
            articleTitle: '신용정보활용체제 공시',
            chapter: '제3장 신용정보의 수집·조사 및 처리',
            sortOrder: 7,
            content: '신용정보회사등은 관리하는 신용정보의 종류, 이용 목적, 제공 대상 및 신용정보주체의 권리 등에 관한 사항을 대통령령으로 정하는 바에 따라 공시하여야 한다. 또한 개인정보보호책임자의 성명과 연락처, 개인신용정보의 열람, 정정청구, 삭제요구 등의 권리 행사에 관한 사항도 공시에 포함되어야 한다.',
            contentEn: 'Credit information companies must publicly disclose information types, usage purposes, recipients, data subject rights, privacy officer contact, and procedures for inspection, correction, and deletion requests.',
            tags: ['credit', 'disclosure'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제32조',
            articleTitle: '개인신용정보의 제공·활용에 대한 동의',
            chapter: '제5장 신용정보주체의 보호',
            sortOrder: 8,
            content: '신용정보제공·이용자가 대통령령으로 정하는 바에 따라 개인신용정보를 타인에게 제공하려는 경우에는 해당 개인으로부터 개인신용정보를 제공받는 자, 개인신용정보를 제공받는 자의 이용 목적, 제공하는 개인신용정보의 내용, 개인신용정보를 제공받는 자의 개인신용정보 보유 및 이용 기간 등을 알리고 동의를 받아야 한다. 동의 방식은 서면, 공인전자서명, 녹취 등 안전한 방법으로 하여야 한다.',
            contentEn: 'Credit information providers must obtain informed consent from data subjects before sharing personal credit information, using secure methods such as written consent, certified electronic signature, or recording.',
            tags: ['credit', 'consent'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제33조',
            articleTitle: '개인신용정보의 이용',
            chapter: '제5장 신용정보주체의 보호',
            sortOrder: 9,
            content: '신용정보회사등은 개인신용정보를 금융거래 등 상거래관계의 설정 및 유지 여부 등의 판단 목적, 개인이 동의한 목적, 개인정보 보호법에 따라 정보주체의 동의 없이 처리할 수 있는 개인정보를 기존 목적의 범위 내에서 이용하는 경우 등으로만 이용하여야 한다. 상업적 마케팅 이용은 별도 동의를 요구한다.',
            contentEn: 'Personal credit information may only be used for commerce-related creditworthiness assessment, purposes consented to by the individual, or permitted uses under PIPA. Commercial marketing requires separate consent.',
            tags: ['credit', 'use-limitation'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: '제42조',
            articleTitle: '영리목적 수집·이용의 제한',
            chapter: '제6장 신용정보 관련 산업',
            sortOrder: 10,
            content: '신용정보회사등과 그로부터 신용정보를 제공받은 자는 신용정보를 영리 목적 또는 부정한 목적으로 사용하여서는 아니 된다. 신용정보회사등과 그 소속 임직원은 업무상 알게 된 신용정보주체의 비밀을 업무 목적 외에 누설하거나 이용하여서는 아니 된다. 위반 시 형사처벌 및 손해배상책임이 부과된다.',
            contentEn: 'Credit information companies and recipients shall not use credit data for profit-seeking or illicit purposes. Officers and employees must maintain confidentiality beyond business purposes. Violations result in criminal penalties and liability.',
            tags: ['credit', 'confidentiality'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
        ],
      },
    },
  });

  console.log('✅ KR additional laws seeded');
}

main().catch(console.error).finally(() => prisma.$disconnect());
