import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding HK expanded laws...');

  // ============================================================
  // 1. Cap 615 - AMLO (VASP Regime)
  // ============================================================
  const cap615Articles = [
    // Part 1: Preliminary
    {
      articleNum: 'Section 1',
      articleTitle: 'Short title and commencement',
      content: 'Anti-Money Laundering and Counter-Terrorist Financing Ordinance (Cap. 615), short title and commencement provisions.',
      contentEn: 'This Ordinance may be cited as the Anti-Money Laundering and Counter-Terrorist Financing Ordinance. The Ordinance came into force on 1 April 2012, with the VASP licensing regime added by the 2022 Amendment Ordinance taking effect on 1 June 2023. It establishes the legal framework for AML/CFT compliance for financial institutions, designated non-financial businesses and professions (DNFBPs), and from 2023, virtual asset service providers operating in or from Hong Kong.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 1,
      tags: ['amlo', 'preliminary', 'commencement'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider', 'token-issuer'],
    },
    {
      articleNum: 'Section 2',
      articleTitle: 'Interpretation',
      content: 'Definitions of key terms including "financial institution", "specified financial institution", "customer due diligence", "beneficial owner", and following the 2022 amendment, "virtual asset", "VA service" and "licensed provider of VA service".',
      contentEn: 'Section 2 provides comprehensive definitions used throughout the Ordinance. "Virtual asset" is defined as a cryptographically secured digital representation of value that is used as a medium of exchange or for investment purposes and can be transferred, stored or traded electronically. "Beneficial owner" generally means a natural person who ultimately owns or controls 25% or more of the customer or who exercises ultimate effective control. These definitions form the basis for determining the scope of regulated activities and persons.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 2,
      tags: ['definitions', 'virtual-asset', 'beneficial-owner'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider'],
    },
    {
      articleNum: 'Section 3',
      articleTitle: 'Application of Ordinance',
      content: 'The Ordinance applies to specified financial institutions, designated non-financial businesses and professions, and licensed virtual asset service providers carrying on business in Hong Kong.',
      contentEn: 'Section 3 sets out the territorial and personal scope of application. The Ordinance binds the Government and applies to all specified financial institutions including authorized institutions under the Banking Ordinance, licensed corporations under the SFO, money service operators, and trust or company service providers. From June 2023, all VASPs providing services in Hong Kong or actively marketing to Hong Kong investors fall within scope regardless of where they are incorporated.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 3,
      tags: ['application', 'scope', 'jurisdiction'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider', 'fund-manager'],
    },
    {
      articleNum: 'Section 4',
      articleTitle: 'Relevant authorities',
      content: 'Designation of relevant authorities responsible for supervising compliance: HKMA for authorized institutions, SFC for licensed corporations and VASPs, IA for insurers, and C&ED for money service operators.',
      contentEn: 'Section 4 designates the supervisory authorities for different categories of regulated entities. The Securities and Futures Commission supervises licensed corporations and, under Part 5B/5A as amended, licensed virtual asset service providers. The Hong Kong Monetary Authority supervises authorized institutions including any crypto-related activities they conduct. Each authority has the power to issue guidelines, conduct inspections, and take enforcement action within its remit.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 4,
      tags: ['authorities', 'sfc', 'hkma', 'supervision'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider'],
    },

    // Part 2: CDD
    {
      articleNum: 'Section 5',
      articleTitle: 'General requirements for customer due diligence',
      content: 'A financial institution must carry out customer due diligence measures before establishing a business relationship, before carrying out an occasional transaction of HK$120,000 or more, when there is suspicion of ML/TF, or when there are doubts about the veracity of previously obtained information.',
      contentEn: 'Section 5 establishes the cornerstone CDD obligation. Required CDD measures include: (a) identifying the customer and verifying identity using reliable, independent source documents; (b) where there is a beneficial owner, identifying and taking reasonable measures to verify the beneficial owner; (c) obtaining information on the purpose and intended nature of the business relationship; and (d) conducting ongoing monitoring of the business relationship. For VASPs, the threshold for occasional transactions is HK$8,000 under the Travel Rule provisions.',
      chapter: 'Part 2: CDD',
      sortOrder: 5,
      tags: ['cdd', 'kyc', 'customer-due-diligence'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Section 6',
      articleTitle: 'Simplified due diligence',
      content: 'A financial institution may apply simplified due diligence measures where the ML/TF risk is assessed to be low, subject to documentation of the risk assessment and ongoing monitoring.',
      contentEn: 'Section 6 permits simplified CDD only in specifically defined low-risk situations, such as where the customer is a listed company subject to disclosure requirements, a financial institution from an equivalent jurisdiction, or a public body. The institution must still document the basis for determining low risk and cannot omit ongoing monitoring. Simplified CDD is generally not available for VASP customers given the inherent ML/TF risks of virtual assets identified by FATF.',
      chapter: 'Part 2: CDD',
      sortOrder: 6,
      tags: ['simplified-dd', 'low-risk'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Section 7',
      articleTitle: 'Enhanced due diligence for high-risk situations',
      content: 'Enhanced customer due diligence must be applied in high-risk situations including where the customer is from a high-risk jurisdiction, in non-face-to-face transactions, for politically exposed persons, and other situations of higher ML/TF risk.',
      contentEn: 'Section 7 mandates enhanced CDD measures including obtaining additional information about the customer and beneficial owner, the source of funds and source of wealth, the reasons for the intended or performed transaction, and senior management approval to establish or continue the business relationship. For VASPs, EDD is generally required for transactions involving privacy coins, mixers, tumblers, or unhosted wallets above the de minimis threshold.',
      chapter: 'Part 2: CDD',
      sortOrder: 7,
      tags: ['edd', 'high-risk', 'enhanced-dd'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider'],
    },
    {
      articleNum: 'Section 8',
      articleTitle: 'Politically exposed persons',
      content: 'Specific enhanced measures apply to politically exposed persons (PEPs), their family members and close associates, including senior management approval, source of wealth verification, and enhanced ongoing monitoring.',
      contentEn: 'Section 8 requires institutions to put in place appropriate risk-based systems to determine whether a customer or beneficial owner is a PEP. For foreign PEPs, enhanced measures are mandatory; for domestic PEPs and international organization PEPs, enhanced measures apply when the business relationship is assessed as higher risk. The 2018 amendments introduced the concept of "former PEPs" requiring continued enhanced scrutiny for at least 12-18 months after leaving office.',
      chapter: 'Part 2: CDD',
      sortOrder: 8,
      tags: ['pep', 'politically-exposed', 'edd'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 9',
      articleTitle: 'Non-face-to-face customer relationships',
      content: 'Where customer onboarding is conducted on a non-face-to-face basis, additional measures must be applied to mitigate the higher risk of identity fraud and impersonation.',
      contentEn: 'Section 9 is particularly relevant to VASPs which typically onboard customers entirely online. Acceptable mitigation measures include certified copies of identification documents, electronic identity verification systems with liveness detection, video conference verification, and confirmation through independent channels. The HKMA and SFC have issued guidance permitting fully digital onboarding subject to robust technology controls and ongoing transaction monitoring.',
      chapter: 'Part 2: CDD',
      sortOrder: 9,
      tags: ['non-face-to-face', 'digital-onboarding', 'ekyc'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Section 10',
      articleTitle: 'Record-keeping obligations',
      content: 'Records of customer due diligence and transactions must be kept for at least 5 years after the end of the business relationship or completion of the transaction, in a form that allows reconstruction of individual transactions.',
      contentEn: 'Section 10 requires comprehensive record-keeping covering: identification documents and CDD information, account files and business correspondence, transaction records sufficient to permit reconstruction, and risk assessment documentation. For VASPs, this includes blockchain transaction hashes, wallet addresses, counterparty VASP information collected under the Travel Rule, and any analysis used to determine the ML/TF risk of transactions. Records must be readily retrievable and producible to the relevant authority on request.',
      chapter: 'Part 2: CDD',
      sortOrder: 10,
      tags: ['record-keeping', 'retention', '5-years'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider', 'fund-manager'],
    },

    // Part 5A: VASP Regulation
    {
      articleNum: 'Section 53ZRA',
      articleTitle: 'Definition of VA service',
      content: 'A VA service means operating a virtual asset exchange, namely the provision of services through means of electronic facilities whereby offers to sell or purchase virtual assets are regularly made or accepted in a way that forms or results in a binding transaction.',
      contentEn: 'Section 53ZRA defines the regulated activity of providing VA services. The current definition focuses on centralized virtual asset exchanges that match buyers and sellers through an order book or similar mechanism and where client assets come into possession of the operator. The definition explicitly excludes peer-to-peer platforms that merely facilitate introductions, but the Financial Secretary has power to expand the definition by gazette notice to cover additional activities such as VA custody, VA transfer services, and VA lending or borrowing.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 11,
      tags: ['vasp', 'va-service', 'exchange', 'definition'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 53ZRB',
      articleTitle: 'VASP license requirement',
      content: 'No person shall carry on a business of providing any VA service in Hong Kong, or hold themselves out as carrying on such a business, unless the person is a licensed provider of VA services.',
      contentEn: 'Section 53ZRB establishes the core licensing requirement effective 1 June 2023. Operating a VA exchange without a license, or actively marketing such services to the Hong Kong public, is a criminal offence punishable by a fine of HK$5,000,000 and imprisonment for 7 years on conviction on indictment, with daily default fines of HK$100,000. The "actively market" concept captures offshore exchanges that target Hong Kong investors regardless of where they are incorporated or operated.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 12,
      tags: ['vasp', 'license', 'requirement', 'offence'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Section 53ZRD',
      articleTitle: 'Application for VASP license',
      content: 'Application for a VASP license must be made to the SFC in the specified form, accompanied by the prescribed fee and supporting documents demonstrating the applicant meets all licensing criteria.',
      contentEn: 'Section 53ZRD sets out the application process. Applicants must submit detailed information about corporate structure, ultimate beneficial owners, proposed business model, target customer base, IT and cybersecurity infrastructure, AML/CFT systems, custody arrangements, insurance coverage, and the fitness and properness of all directors, responsible officers and licensed representatives. Only Hong Kong incorporated companies (or non-Hong Kong companies registered under the Companies Ordinance) with a permanent place of business in Hong Kong may apply.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 13,
      tags: ['vasp', 'application', 'sfc'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Section 53ZRG',
      articleTitle: 'Fit and proper criteria',
      content: 'The SFC may grant a VASP license only if it is satisfied that the applicant and each of its responsible officers, directors and ultimate owners is a fit and proper person.',
      contentEn: 'Section 53ZRG applies the same fit and proper standards used for SFO licensed corporations. The SFC considers financial status, educational and professional qualifications, experience and reputation, character and integrity, criminal record, regulatory history, and ability to perform regulated functions competently and honestly. At least two responsible officers are required, and at least one must be an executive director who is available to supervise the conduct of the regulated activity at all times.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 14,
      tags: ['fit-and-proper', 'vasp', 'responsible-officer'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Section 53ZRK',
      articleTitle: 'Conditions of VASP license',
      content: 'The SFC may impose any conditions on a VASP license that it considers appropriate, and may amend or revoke conditions at any time. Standard conditions cover the scope of permitted activities, eligible clients, custody arrangements, and reporting obligations.',
      contentEn: 'Section 53ZRK gives the SFC broad discretion to tailor license conditions to the specific business model and risk profile of each VASP. Standard conditions issued by the SFC restrict licensed VASPs to serving only professional investors initially (although this is being relaxed for retail under the 2024 framework), prohibit the offering of certain high-risk tokens such as privacy coins, require minimum paid-up capital of HK$5 million, and impose detailed token admission and review processes before any virtual asset can be made available for trading.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 15,
      tags: ['vasp', 'conditions', 'license'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Section 53ZRM',
      articleTitle: 'Operation requirements for VASPs',
      content: 'Licensed VASPs must comply with detailed operating requirements covering governance, internal controls, risk management, conflicts of interest, complaints handling, cybersecurity, and business continuity.',
      contentEn: 'Section 53ZRM requires VASPs to maintain a robust operational framework comparable to that of SFO licensed corporations. This includes a three-lines-of-defence model with independent risk management and compliance functions, comprehensive cybersecurity measures aligned with international standards such as NIST and ISO 27001, regular penetration testing and vulnerability assessments, segregation of duties for sensitive operations, and detailed business continuity and disaster recovery plans tested at least annually.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 16,
      tags: ['vasp', 'operations', 'governance', 'cybersecurity'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 53ZRP',
      articleTitle: 'Safe custody of client assets',
      content: 'A licensed VASP must hold client virtual assets and client money on trust through an associated entity in segregated accounts, separately from the VASPs own assets.',
      contentEn: 'Section 53ZRP imposes strict client asset segregation requirements. Client money must be held in segregated trust accounts with authorized institutions in Hong Kong. Client virtual assets must be held by an associated entity that is a Hong Kong incorporated company wholly owned by the VASP, holds a Trust or Company Service Provider license, and exists solely for the purpose of holding client VAs. These structures ensure client assets are protected and ring-fenced in the event of insolvency of the VASP.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 17,
      tags: ['custody', 'client-assets', 'segregation', 'trust'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 53ZRQ',
      articleTitle: 'Cold storage requirements',
      content: 'A licensed VASP must store at least 98% of client virtual assets in cold wallets, with no more than 2% held in hot wallets for operational liquidity purposes.',
      contentEn: 'Section 53ZRQ implements one of the strictest cold storage requirements globally. Cold wallets must be true offline storage with private keys generated and stored on devices that have never been connected to the internet, with geographically distributed backups and multi-signature controls requiring multiple authorized personnel to effect any movement. Movements between cold and hot wallets must be approved by senior management and logged in detail. The 2% hot wallet limit must be calculated daily and breaches reported to the SFC immediately.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 18,
      tags: ['cold-storage', 'hot-wallet', '98-percent', 'custody'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 53ZRR',
      articleTitle: 'Insurance requirements',
      content: 'A licensed VASP must maintain insurance or an equivalent compensation arrangement to cover potential loss of client virtual assets resulting from theft, fraud, hacking, or other risks.',
      contentEn: 'Section 53ZRR requires VASPs to maintain insurance or compensation arrangements covering 50% of cold storage assets and 100% of hot wallet assets. Acceptable arrangements include traditional crime and specie insurance from reputable underwriters, captive insurance arrangements, or third-party guarantees backed by liquid assets held in trust. Self-insurance through retained earnings is permitted only for the cold storage portion and subject to SFC approval. Coverage must be reviewed at least annually and adjusted for changes in client asset values.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 19,
      tags: ['insurance', 'compensation', 'client-protection'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Section 53ZRS',
      articleTitle: 'Market manipulation and misconduct',
      content: 'Licensed VASPs and their representatives must not engage in market manipulation, insider dealing, false trading, wash trading, spoofing, layering, or other forms of market misconduct in respect of virtual assets traded on or through the platform.',
      contentEn: 'Section 53ZRS extends market misconduct prohibitions analogous to those in Part XIII of the SFO to virtual asset markets. VASPs must implement automated surveillance systems to detect suspicious trading patterns, maintain Chinese walls between proprietary trading and client-facing functions, prohibit employees from trading in tokens listed on the platform other than under strict pre-clearance rules, and report suspected misconduct to the SFC promptly. Penalties include license revocation, fines and criminal prosecution.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 20,
      tags: ['market-manipulation', 'misconduct', 'wash-trading', 'surveillance'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Section 53ZRT',
      articleTitle: 'Disclosure requirements',
      content: 'Licensed VASPs must provide clear, accurate and balanced disclosure to clients regarding the platform, the virtual assets available for trading, fees and charges, risks, and the VASPs financial soundness and complaint mechanisms.',
      contentEn: 'Section 53ZRT requires extensive ongoing disclosures including platform terms and conditions, conflict of interest policies, detailed risk warnings about the volatility and irreversibility of VA transactions, fee schedules, listed token whitepapers and due diligence summaries, monthly proof-of-reserves attestations, annual audited financial statements, and any material changes in business or ownership. Marketing materials must be fair and balanced and may not guarantee returns or downplay risks.',
      chapter: 'Part 5A: VASP Regulation',
      sortOrder: 21,
      tags: ['disclosure', 'transparency', 'proof-of-reserves'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'token-issuer'],
    },

    // Part 6: AML/CFT offences
    {
      articleNum: 'Section 25',
      articleTitle: 'Dealing with property known or believed to represent proceeds of an indictable offence',
      content: 'A person who deals with any property knowing or having reasonable grounds to believe that the property in whole or in part directly or indirectly represents any persons proceeds of an indictable offence commits an offence.',
      contentEn: 'Section 25 (read with Section 25 of the Drug Trafficking (Recovery of Proceeds) Ordinance Cap. 405 and the Organized and Serious Crimes Ordinance Cap. 455) creates the principal money laundering offence in Hong Kong. The maximum penalty on conviction on indictment is a fine of HK$5 million and imprisonment for 14 years. The "reasonable grounds to believe" test imposes an objective standard meaning institutions cannot turn a blind eye to suspicious circumstances, and applies fully to virtual asset transactions involving suspicious source wallets.',
      chapter: 'Part 6: Offences',
      sortOrder: 22,
      tags: ['money-laundering', 'offence', 'proceeds-of-crime'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Section 25A',
      articleTitle: 'Disclosure of knowledge or suspicion - STR',
      content: 'Where a person knows or suspects that any property represents proceeds of an indictable offence or is intended to be used in connection with an indictable offence, the person shall as soon as it is reasonable for them to do so disclose that knowledge or suspicion to an authorized officer.',
      contentEn: 'Section 25A imposes the suspicious transaction reporting (STR) obligation. Reports must be filed with the Joint Financial Intelligence Unit (JFIU) operated by the Hong Kong Police Force and Customs and Excise Department. Filing an STR provides a defence to the substantive money laundering offence and protects the discloser from civil liability. Tipping-off the customer about the existence of an STR is itself a separate criminal offence under Section 25A(5) punishable by 3 years imprisonment.',
      chapter: 'Part 6: Offences',
      sortOrder: 23,
      tags: ['str', 'suspicious-transaction', 'reporting', 'jfiu'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider', 'payment-service'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'HK', lawNumber: 'HK-Cap615-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'HK',
      lawType: 'ordinance',
      title: 'Anti-Money Laundering and Counter-Terrorist Financing Ordinance (Cap. 615)',
      titleEn: 'Anti-Money Laundering and Counter-Terrorist Financing Ordinance',
      shortName: 'AMLO / Cap 615',
      lawNumber: 'HK-Cap615-EXPANDED',
      enactedDate: new Date('2012-04-01'),
      effectiveDate: new Date('2012-04-01'),
      lastAmendedDate: new Date('2023-06-01'),
      status: 'amended',
      regulator: 'SFC / HKMA',
      sourceUrl: 'https://www.elegislation.gov.hk/hk/cap615',
      totalArticles: cap615Articles.length,
      articles: { create: cap615Articles },
    },
  });

  // ============================================================
  // 2. Cap 571 - SFO
  // ============================================================
  const cap571Articles = [
    {
      articleNum: 'Section 1',
      articleTitle: 'Short title and commencement',
      content: 'Securities and Futures Ordinance (Cap. 571), short title and commencement provisions.',
      contentEn: 'The Securities and Futures Ordinance came into operation on 1 April 2003, consolidating ten previous ordinances into a single comprehensive statute regulating Hong Kongs securities and futures markets. The SFO has been amended numerous times to reflect market developments, with significant amendments in 2014 (uncertificated securities), 2018 (over-the-counter derivatives), and ongoing updates to address tokenized securities and digital asset products.',
      chapter: 'Part I: Preliminary',
      sortOrder: 1,
      tags: ['sfo', 'commencement'],
      appliesToBiz: ['sto-issuer', 'exchange', 'fund-manager'],
    },
    {
      articleNum: 'Section 2 / Schedule 1',
      articleTitle: 'Interpretation - Definition of securities',
      content: 'Securities include shares, stocks, debentures, loan stocks, funds, bonds or notes of, or issued by, a body, whether incorporated or unincorporated, or a government or municipal government authority; and rights, options or interests in respect of any such items.',
      contentEn: 'Schedule 1 of the SFO contains the broad definition of "securities" which has been interpreted by the SFC in its 2019 and 2023 statements to include security tokens (STOs) where the underlying instrument has the characteristics of a traditional security. Tokenized representations of shares, bonds, fund interests and structured products are treated as securities, bringing them fully within the licensing, prospectus and conduct requirements of the SFO regardless of the underlying blockchain technology used to issue or transfer them.',
      chapter: 'Part I: Preliminary',
      sortOrder: 2,
      tags: ['definition', 'securities', 'sto', 'tokenization'],
      appliesToBiz: ['sto-issuer', 'rwa-issuer', 'token-issuer'],
    },
    {
      articleNum: 'Section 114',
      articleTitle: 'License requirement - Type 1 Dealing in Securities',
      content: 'No person shall, without a license, carry on a business in a regulated activity, or hold themselves out as carrying on a business in a regulated activity. Type 1 covers dealing in securities including security tokens.',
      contentEn: 'Section 114 read with Schedule 5 establishes the licensing regime for ten types of regulated activity. Type 1 (dealing in securities) is required for any platform or person making or offering to make agreements with another person to enter into transactions in securities, including security tokens. Operating an unlicensed business in a regulated activity is an offence punishable by a HK$5 million fine and 7 years imprisonment, plus daily default fines.',
      chapter: 'Part IV: Licensing',
      sortOrder: 3,
      tags: ['license', 'type-1', 'dealing'],
      appliesToBiz: ['sto-issuer', 'exchange'],
    },
    {
      articleNum: 'Section 115',
      articleTitle: 'Type 7 - Providing Automated Trading Services',
      content: 'Type 7 regulated activity covers the provision of automated trading services (ATS), being electronic facilities through which offers to deal in securities or futures contracts are regularly made or accepted in a way that forms or results in a binding transaction.',
      contentEn: 'Section 115 and Part III of Schedule 5 cover ATS providers, which is the licensing category used for SFC-regulated virtual asset trading platforms that trade security tokens. Operators must demonstrate fair and orderly trading, market surveillance, transparent rules, equivalent investor protection to traditional exchanges, and may be authorized as either a licensed ATS provider or, for larger venues, as a recognized exchange company under Part III of the SFO.',
      chapter: 'Part IV: Licensing',
      sortOrder: 4,
      tags: ['type-7', 'ats', 'automated-trading', 'sto-exchange'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 116',
      articleTitle: 'Fit and proper test',
      content: 'The SFC shall not grant a license unless the applicant satisfies the SFC that they are a fit and proper person to be licensed for the regulated activity for which the application is made.',
      contentEn: 'Section 116 establishes the cornerstone fit and proper test, with detailed criteria set out in the SFCs Fit and Proper Guidelines. Considerations include financial status and solvency, educational qualifications and experience, ability to carry on the regulated activity competently and honestly, reputation, character, reliability and financial integrity, and any criminal or regulatory record. For digital asset licensees, additional considerations apply regarding technology expertise and cybersecurity capability.',
      chapter: 'Part IV: Licensing',
      sortOrder: 5,
      tags: ['fit-and-proper', 'license'],
      appliesToBiz: ['exchange', 'sto-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 122',
      articleTitle: 'Principal place of business',
      content: 'A licensed corporation must have its principal place of business in Hong Kong, with appropriate physical premises, staff and infrastructure to conduct the regulated activity.',
      contentEn: 'Section 122 prevents purely offshore operations from holding SFC licenses. Licensed corporations must maintain a permanent place of business in Hong Kong where books and records are kept, key decisions are made, and senior management including responsible officers are physically present a substantial portion of working time. The SFC has been particularly strict on this requirement for VASP and digital asset licensees to ensure effective on-site supervision.',
      chapter: 'Part IV: Licensing',
      sortOrder: 6,
      tags: ['place-of-business', 'substance'],
      appliesToBiz: ['exchange', 'fund-manager'],
    },
    {
      articleNum: 'Section 125',
      articleTitle: 'Capital requirements',
      content: 'Licensed corporations must maintain minimum paid-up share capital and liquid capital as prescribed by the Securities and Futures (Financial Resources) Rules.',
      contentEn: 'Section 125 read with the Financial Resources Rules sets minimum capital by license type. Type 1 dealers holding client assets must maintain HK$5 million paid-up capital and HK$3 million liquid capital. Type 7 ATS operators must maintain HK$5 million paid-up capital. SFC-licensed virtual asset trading platforms are subject to enhanced capital requirements equivalent to Type 1 plus additional buffers reflecting operational and technology risks.',
      chapter: 'Part IV: Licensing',
      sortOrder: 7,
      tags: ['capital', 'frr', 'liquid-capital'],
      appliesToBiz: ['exchange', 'sto-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 270',
      articleTitle: 'Insider dealing',
      content: 'A person engages in insider dealing in relation to a listed corporation when the person, being connected with the corporation and having relevant information, deals in the listed securities or derivatives of the corporation, or counsels or procures another person to deal.',
      contentEn: 'Section 270 prohibits insider dealing in listed securities, with civil and criminal liability under the dual-track regime in Parts XIII and XIV. The prohibition extends to security tokens that represent listed securities or that themselves become listed on regulated venues. Penalties include fines up to HK$10 million, imprisonment up to 10 years, disgorgement of profits, and disqualification from acting as a director.',
      chapter: 'Part XIII: Market Misconduct',
      sortOrder: 8,
      tags: ['insider-dealing', 'misconduct'],
      appliesToBiz: ['sto-issuer', 'exchange', 'fund-manager'],
    },
    {
      articleNum: 'Section 271',
      articleTitle: 'False trading',
      content: 'A person engages in false trading if, in Hong Kong or elsewhere, they do anything or cause anything to be done with the intention of creating, or which is likely to create, a false or misleading appearance of active trading in securities or futures contracts.',
      contentEn: 'Section 271 criminalizes wash trades, matched orders, and other forms of fictitious trading designed to create artificial activity. The provision is technology-neutral and applies equally to security tokens traded on licensed VA platforms. The SFC has explicitly warned that wash trading on virtual asset platforms, even if conducted by the platform itself to create the appearance of liquidity, falls within the scope of false trading prohibitions.',
      chapter: 'Part XIII: Market Misconduct',
      sortOrder: 9,
      tags: ['false-trading', 'wash-trading', 'misconduct'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 274',
      articleTitle: 'Price rigging',
      content: 'A person engages in price rigging if they enter into transactions that have the effect of maintaining, increasing, reducing, stabilizing or causing fluctuations in the price of securities, otherwise than for legitimate purposes.',
      contentEn: 'Section 274 prohibits price manipulation through artificial transactions. This includes pump-and-dump schemes, spoofing, layering, marking the close, and other manipulative trading strategies. The provision applies to security tokens and to virtual assets traded on SFC-licensed platforms by virtue of Section 53ZRS of the AMLO. Civil sanctions include disgorgement and bans, while criminal prosecution can lead to 10 years imprisonment.',
      chapter: 'Part XIII: Market Misconduct',
      sortOrder: 10,
      tags: ['price-rigging', 'manipulation', 'misconduct'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Section 295',
      articleTitle: 'Stock market manipulation',
      content: 'A person engages in stock market manipulation if they enter into 2 or more transactions in securities of a corporation that by themselves or in conjunction with any other transaction increase, reduce, maintain or stabilize the price of securities with intent to induce others to deal.',
      contentEn: 'Section 295 captures coordinated manipulation strategies and is the principal criminal market manipulation offence. The penalty on conviction on indictment is a fine of HK$10 million and imprisonment for 10 years. The SFC has used Section 295 against ramp-and-dump operators using social media to promote thinly traded stocks, and similar enforcement is anticipated against pump-and-dump schemes targeting tokenized securities and crypto assets traded on regulated venues.',
      chapter: 'Part XIII: Market Misconduct',
      sortOrder: 11,
      tags: ['manipulation', 'pump-and-dump', 'misconduct'],
      appliesToBiz: ['exchange', 'sto-issuer', 'token-issuer'],
    },
    {
      articleNum: 'Section 300A (SFC Circular)',
      articleTitle: 'STO specific guidance - tokenized securities treatment',
      content: 'Where a token has the features of a traditional security such as equity, debt or fund interest, the token is a security under the SFO and all licensing, prospectus and conduct requirements apply equally regardless of the use of distributed ledger technology.',
      contentEn: 'The SFCs November 2023 Circular on Tokenisation of SFC-authorised Investment Products and the parallel Circular on Intermediaries Engaging in Tokenised Securities-Related Activities clarify that tokenization is a wrapper, not a transformation. Existing rules apply to the underlying security, plus additional requirements addressing tokenization-specific risks including smart contract security, ownership recordation, settlement finality, fork and airdrop handling, and interoperability with traditional CSD infrastructure.',
      chapter: 'SFC Digital Asset Circulars',
      sortOrder: 12,
      tags: ['sto', 'tokenization', 'sfc-circular', 'guidance'],
      appliesToBiz: ['sto-issuer', 'rwa-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 301A (SFC Circular)',
      articleTitle: 'Virtual Asset Fund Management - Type 9',
      content: 'Fund managers managing portfolios that invest 10% or more in virtual assets must obtain Type 9 (asset management) licensing with the additional VA fund manager terms and conditions imposed by the SFC.',
      contentEn: 'The SFCs Proforma Terms and Conditions for VA Fund Managers (October 2019, updated 2023) require enhanced standards including: only professional investor clients (with retail access being introduced selectively), use of SFC-licensed VA trading platforms or qualified custodians, segregation of fund assets, daily NAV calculation with independent verification, comprehensive risk management addressing liquidity, valuation, custody and cybersecurity risks, and quarterly reporting to the SFC. Approval of the responsible officer competence in digital assets is critical.',
      chapter: 'SFC Digital Asset Circulars',
      sortOrder: 13,
      tags: ['type-9', 'fund-management', 'va-fund'],
      appliesToBiz: ['fund-manager'],
    },
    {
      articleNum: 'Section 302A (SFC Circular)',
      articleTitle: 'Dealing in VA - requirements under SFO',
      content: 'Intermediaries dealing in or advising on virtual assets must comply with the SFCs January 2022 Joint Circular requirements including suitability, knowledge assessment, governance and risk disclosures.',
      contentEn: 'The Joint HKMA-SFC Circular on intermediaries virtual asset-related activities, updated October 2023, requires that all VA-related services be conducted only by intermediaries that meet enhanced competence requirements. Distribution of VA products is generally restricted to professional investors except for VA spot ETFs and VA derivatives traded on SFC-recognized exchanges. Knowledge assessments must be conducted before onboarding clients to VA services, and concentration limits and risk warnings must be applied.',
      chapter: 'SFC Digital Asset Circulars',
      sortOrder: 14,
      tags: ['va-dealing', 'joint-circular', 'intermediary'],
      appliesToBiz: ['exchange', 'fund-manager', 'wallet-provider'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'HK', lawNumber: 'HK-Cap571-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'HK',
      lawType: 'ordinance',
      title: 'Securities and Futures Ordinance (Cap. 571)',
      titleEn: 'Securities and Futures Ordinance',
      shortName: 'SFO / Cap 571',
      lawNumber: 'HK-Cap571-EXPANDED',
      enactedDate: new Date('2003-04-01'),
      effectiveDate: new Date('2003-04-01'),
      lastAmendedDate: new Date('2023-06-01'),
      status: 'amended',
      regulator: 'SFC',
      sourceUrl: 'https://www.elegislation.gov.hk/hk/cap571',
      totalArticles: cap571Articles.length,
      articles: { create: cap571Articles },
    },
  });

  // ============================================================
  // 3. Cap 155 - Banking Ordinance
  // ============================================================
  const cap155Articles = [
    {
      articleNum: 'Section 2',
      articleTitle: 'Interpretation',
      content: 'Definitions of "authorized institution", "bank", "deposit-taking company", "restricted licence bank", "deposit", and other key terms used throughout the Banking Ordinance.',
      contentEn: 'Section 2 establishes the three-tier banking system in Hong Kong: licensed banks, restricted licence banks, and deposit-taking companies, collectively referred to as authorized institutions (AIs). A "deposit" is broadly defined as a sum of money paid on terms of repayment with or without interest. The HKMA has clarified that fiat-referenced stablecoins issued by AIs may fall within deposit-taking and require separate analysis under the Stablecoins Ordinance.',
      chapter: 'Part I',
      sortOrder: 1,
      tags: ['definition', 'authorized-institution', 'deposit'],
      appliesToBiz: ['stablecoin-issuer', 'payment-service'],
    },
    {
      articleNum: 'Section 11',
      articleTitle: 'Prohibition on taking deposits without authorization',
      content: 'Subject to specified exemptions, no person other than an authorized institution shall carry on a business of taking deposits in Hong Kong.',
      contentEn: 'Section 11 establishes the deposit-taking monopoly of authorized institutions. The offence is punishable by a fine of HK$5 million and imprisonment for 7 years on conviction on indictment. Taking customer fiat for the purpose of issuing stablecoins or operating an exchange may potentially fall within deposit-taking, which is one reason VASP licensing requires that client fiat be held in segregated trust accounts at AIs rather than commingled with the operators own funds.',
      chapter: 'Part IV',
      sortOrder: 2,
      tags: ['deposit-taking', 'prohibition', 'license'],
      appliesToBiz: ['stablecoin-issuer', 'exchange', 'payment-service'],
    },
    {
      articleNum: 'Section 12',
      articleTitle: 'Fit and proper criteria for authorization',
      content: 'The HKMA shall not authorize any institution unless satisfied that the institution and its controllers, directors and chief executive are fit and proper persons.',
      contentEn: 'Section 12 read with the Seventh Schedule sets out detailed authorization criteria including minimum capital, fit and proper management, adequate systems and controls, sound business plan, and ability to comply with prudential standards. The HKMA conducts thorough background checks and ongoing supervision to ensure standards are continuously met. For AIs engaging in digital asset activities, additional technology and risk management standards apply.',
      chapter: 'Part IV',
      sortOrder: 3,
      tags: ['fit-and-proper', 'authorization'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 16',
      articleTitle: 'Minimum capital requirement',
      content: 'A licensed bank must maintain a minimum paid-up share capital of HK$300 million. A restricted licence bank must maintain HK$100 million. A deposit-taking company must maintain HK$25 million.',
      contentEn: 'Section 16 establishes minimum capital tiered by license category. The HK$300 million floor for full licensed banks reflects the higher risks of accepting public deposits and operating across the full range of banking activities. These figures are minimums only - actual capital requirements depend on the risk profile of the AIs activities and are determined by the HKMA based on the Basel III framework as implemented through the Banking (Capital) Rules.',
      chapter: 'Part IV',
      sortOrder: 4,
      tags: ['capital', 'minimum-capital', '300-million'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 52',
      articleTitle: 'Minimum liquidity requirements',
      content: 'Authorized institutions must maintain liquidity at levels prescribed by the HKMA through the Banking (Liquidity) Rules, including the Liquidity Coverage Ratio and Net Stable Funding Ratio.',
      contentEn: 'Section 52 implements Basel III liquidity standards. Category 1 institutions (internationally active) must maintain LCR of at least 100% and NSFR of at least 100%. Category 2 institutions are subject to a simpler Liquidity Maintenance Ratio of 25%. AIs offering crypto custody or stablecoin services must hold additional high-quality liquid assets to cover potential redemption surges and operational liquidity needs.',
      chapter: 'Part XVII',
      sortOrder: 5,
      tags: ['liquidity', 'lcr', 'nsfr'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 53',
      articleTitle: 'Capital adequacy ratio',
      content: 'Authorized institutions must maintain a minimum capital adequacy ratio as prescribed by the HKMA under the Banking (Capital) Rules, currently set at minimum 8% with additional buffers.',
      contentEn: 'Section 53 implements the Basel III capital framework with minimum CET1 ratio of 4.5%, Tier 1 ratio of 6%, and Total Capital ratio of 8%, plus a Capital Conservation Buffer of 2.5% and Countercyclical Capital Buffer set by the HKMA. Digital asset exposures are subject to the Basel Committees prudential treatment of crypto-asset exposures (December 2022), with Group 2 unbacked crypto subject to a 1250% risk weight effectively requiring dollar-for-dollar capital backing.',
      chapter: 'Part XVII',
      sortOrder: 6,
      tags: ['car', 'capital-adequacy', 'basel'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 70',
      articleTitle: 'Power to revoke authorization',
      content: 'The HKMA may revoke the authorization of an institution where the institution no longer meets the criteria for authorization, has breached prudential standards, or where revocation is in the interest of depositors or the financial system.',
      contentEn: 'Section 70 gives the HKMA broad supervisory powers to revoke or suspend authorization, attach conditions, or require remedial action. Revocation can be based on insolvency, fit and proper failures, persistent rule breaches, or systemic concerns. The HKMA also has power to apply for the appointment of a Manager under Part X to take over management of a troubled AI, and resolution powers under the Financial Institutions (Resolution) Ordinance Cap. 628.',
      chapter: 'Part V',
      sortOrder: 7,
      tags: ['revocation', 'enforcement', 'supervision'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 100A (HKMA Circular)',
      articleTitle: 'Crypto-asset exposures - prudential treatment',
      content: 'AIs with crypto-asset exposures must apply the prudential treatment set out in the HKMAs January 2024 circular implementing the Basel Committees Standard on prudential treatment of crypto-asset exposures.',
      contentEn: 'The HKMA circular implements the Basel Standard from 1 January 2025. Group 1a tokenized traditional assets receive treatment equivalent to the underlying. Group 1b qualifying stablecoins receive a modified treatment based on the underlying reserves. Group 2a cryptos meeting hedging effectiveness criteria receive modified market risk treatment, while Group 2b unbacked cryptos including Bitcoin and Ether receive a 1250% risk weight. AIs must also report exposures quarterly to the HKMA.',
      chapter: 'HKMA Circulars',
      sortOrder: 8,
      tags: ['crypto-exposure', 'basel', 'prudential', 'risk-weight'],
      appliesToBiz: ['stablecoin-issuer', 'exchange'],
    },
    {
      articleNum: 'Section 101A (HKMA Circular)',
      articleTitle: 'Custody of digital assets by banks',
      content: 'Authorized institutions providing custody services for digital assets to clients must comply with the HKMAs February 2024 circular on the provision of custodial services for digital assets.',
      contentEn: 'The HKMA circular requires AIs offering digital asset custody to apply substantially the same standards as SFC-licensed VASPs including segregation of client assets in dedicated wallets, predominant use of cold storage, multi-signature controls, comprehensive insurance, robust cybersecurity, and clear disclosure to clients. AIs must also ensure that custody activities do not impair the safety and soundness of their core banking operations and must seek HKMA non-objection before launching such services.',
      chapter: 'HKMA Circulars',
      sortOrder: 9,
      tags: ['custody', 'digital-asset', 'bank-custody'],
      appliesToBiz: ['stablecoin-issuer', 'wallet-provider'],
    },
    {
      articleNum: 'Section 102A (HKMA Circular)',
      articleTitle: 'Stablecoin dealings by authorized institutions',
      content: 'AIs intending to issue, hold, or facilitate dealings in stablecoins must obtain HKMA non-objection and comply with the requirements of the Stablecoins Ordinance and HKMA supervisory expectations.',
      contentEn: 'AIs may apply for licenses under the Stablecoins Ordinance to act as FRS issuers, in which case both Banking Ordinance and Stablecoins Ordinance requirements apply on a consolidated basis. AIs that distribute or facilitate trading of stablecoins issued by third parties must conduct due diligence on the issuer, monitor concentration risks, ensure consumer protection in marketing materials, and report material exposures to the HKMA.',
      chapter: 'HKMA Circulars',
      sortOrder: 10,
      tags: ['stablecoin', 'frs', 'distribution'],
      appliesToBiz: ['stablecoin-issuer', 'payment-service'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'HK', lawNumber: 'HK-Cap155-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'HK',
      lawType: 'ordinance',
      title: 'Banking Ordinance (Cap. 155)',
      titleEn: 'Banking Ordinance',
      shortName: 'Banking Ordinance / Cap 155',
      lawNumber: 'HK-Cap155-EXPANDED',
      enactedDate: new Date('1986-09-01'),
      effectiveDate: new Date('1986-09-01'),
      status: 'amended',
      regulator: 'HKMA',
      sourceUrl: 'https://www.elegislation.gov.hk/hk/cap155',
      totalArticles: cap155Articles.length,
      articles: { create: cap155Articles },
    },
  });

  // ============================================================
  // 4. HK Stablecoins Ordinance (2024/2025)
  // ============================================================
  const stablecoinArticles = [
    {
      articleNum: 'Section 1',
      articleTitle: 'Short title and commencement',
      content: 'Stablecoins Ordinance, short title and commencement provisions. Enacted 6 December 2024 and brought into operation on 1 August 2025.',
      contentEn: 'The Stablecoins Ordinance was passed by the Legislative Council on 6 December 2024 following extensive consultation by the HKMA and Financial Services and the Treasury Bureau. The Ordinance commenced operation on 1 August 2025 with a transitional period for existing market participants. Hong Kong becomes one of the first major financial centres globally to implement a comprehensive licensing regime specifically for fiat-referenced stablecoins.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 1,
      tags: ['stablecoin', 'commencement', '2024'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 2',
      articleTitle: 'Definition of fiat-referenced stablecoin (FRS)',
      content: 'Fiat-referenced stablecoin means a cryptographically secured digital representation of value that purports to maintain a stable value with reference to a single fiat currency or a specified pool of fiat currencies, and that is or is intended to be used as a means of payment or exchange.',
      contentEn: 'Section 2 narrowly defines the regulated product as fiat-referenced stablecoins. Algorithmic stablecoins, commodity-referenced stablecoins, and stablecoins referenced to baskets including non-fiat assets fall outside the scope of this Ordinance but may be regulated under other regimes. The definition captures both single-currency stablecoins (e.g. HKD-pegged) and multi-currency stablecoins, but only where the reference is to fiat currencies issued by recognized governments or monetary authorities.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 2,
      tags: ['frs', 'definition', 'fiat-referenced'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 3',
      articleTitle: 'Regulated stablecoin activities',
      content: 'The activities regulated under this Ordinance are: (a) issuing an FRS in Hong Kong; (b) issuing an FRS that purports to maintain a stable value with reference to the Hong Kong dollar wherever issued; and (c) actively marketing the issuance of an FRS to the public of Hong Kong.',
      contentEn: 'Section 3 has both territorial and product-specific scope. Any HKD-referenced stablecoin requires a Hong Kong license regardless of where the issuer is located. Any stablecoin (HKD or otherwise) issued in Hong Kong requires a license. And any stablecoin marketed to Hong Kong persons requires a license. This broad scope captures both onshore and offshore issuers and ensures Hong Kong cannot be used as an unregulated marketing channel for foreign stablecoin issuers.',
      chapter: 'Part 2: Regulated Activities',
      sortOrder: 3,
      tags: ['regulated-activity', 'scope', 'jurisdiction'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 5',
      articleTitle: 'License requirement',
      content: 'No person shall carry on a regulated stablecoin activity unless the person holds a license granted by the Monetary Authority under this Ordinance.',
      contentEn: 'Section 5 establishes the criminal offence of unlicensed stablecoin issuance. The offence carries severe penalties reflecting the systemic and consumer protection risks of unregulated stablecoins. Only Hong Kong incorporated companies, or authorized institutions under the Banking Ordinance, may apply for FRS issuer licenses. Foreign issuers wishing to serve the Hong Kong market must establish a Hong Kong subsidiary.',
      chapter: 'Part 3: Licensing',
      sortOrder: 4,
      tags: ['license-requirement', 'offence'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 7',
      articleTitle: 'Application for license',
      content: 'An application for an FRS issuer license must be made to the HKMA in the specified form, accompanied by the prescribed fee and detailed information on the proposed business model, governance, technology, reserve management, and risk management arrangements.',
      contentEn: 'Section 7 sets out the application process. The HKMA expects applicants to demonstrate clear and credible use cases, sustainable business models, robust technology including smart contract security audits, comprehensive risk management addressing operational, cyber, liquidity and market risks, and qualified senior management with relevant experience. The HKMA aims to process complete applications within a reasonable timeframe but complex applications may take 6-12 months.',
      chapter: 'Part 3: Licensing',
      sortOrder: 5,
      tags: ['application', 'license'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 9',
      articleTitle: 'Capital requirement',
      content: 'A licensed FRS issuer must maintain at all times paid-up share capital and reserves of not less than HK$25 million or 1% of the par value of all FRS in circulation issued by the licensee, whichever is higher.',
      contentEn: 'Section 9 establishes the dual capital floor. The HK$25 million minimum ensures even small issuers have meaningful skin in the game. The 1% scaling requirement means that as the stablecoin grows in circulation, capital scales proportionally to absorb operational losses, technology incidents, or de-peg events. The HKMA has discretion to require additional capital based on the issuers risk profile, including for issuers with concentrated holders, complex reserve assets, or aggressive growth plans.',
      chapter: 'Part 3: Licensing',
      sortOrder: 6,
      tags: ['capital', '25-million', '1-percent'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 11',
      articleTitle: 'Reserve requirements',
      content: 'A licensed FRS issuer must hold reserve assets with an aggregate market value at least equal to the par value of all FRS in circulation, comprising only high-quality liquid assets denominated in the reference currency.',
      contentEn: 'Section 11 implements full 100% reserve backing, with reserves restricted to coins and banknotes of the reference currency, deposits with authorized institutions, short-term government securities of the reference currency jurisdiction with maturity not exceeding 90 days, and reverse repos collateralized by such government securities. Riskier assets such as commercial paper, corporate bonds, equities, and other crypto-assets are explicitly prohibited as reserve assets, addressing the well-known weaknesses of pre-regulation stablecoins.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 7,
      tags: ['reserves', '100-percent', 'hqla'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 13',
      articleTitle: 'Segregation of reserves',
      content: 'Reserve assets must be held in segregated accounts separate from the issuers own assets, on trust for the benefit of FRS holders, with appropriate legal arrangements to ensure bankruptcy remoteness.',
      contentEn: 'Section 13 ensures that in the event of issuer insolvency, reserve assets are ring-fenced and available exclusively for redemption of outstanding stablecoins. Trust arrangements must use independent qualified custodians (typically authorized institutions in Hong Kong) and be governed by trust deeds approved by the HKMA. Co-mingling reserves with operating funds, or pledging reserves as collateral for any other obligation, is strictly prohibited and carries criminal penalties.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 8,
      tags: ['segregation', 'trust', 'bankruptcy-remote'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 15',
      articleTitle: 'Redemption at par value',
      content: 'A licensed FRS issuer must, on demand from a holder of the FRS, redeem the FRS at par value in the reference currency without unreasonable delay or excessive fees.',
      contentEn: 'Section 15 establishes the fundamental redemption right that distinguishes regulated stablecoins from speculative crypto. Redemption requests must be honored within one business day in normal market conditions. Fees may only recover reasonable processing costs and may not be punitive. Suspending or limiting redemption is permitted only in exceptional circumstances such as a verified technology failure or systemic market disruption, and requires immediate notification to the HKMA. Persistent failure to honour redemptions is grounds for license revocation.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 9,
      tags: ['redemption', 'par-value', 'consumer-protection'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 17',
      articleTitle: 'Prohibition on interest payment',
      content: 'A licensed FRS issuer shall not pay any interest, yield, or similar financial return to holders of its FRS, whether directly or indirectly through related arrangements.',
      contentEn: 'Section 17 prohibits interest payments to prevent stablecoins from competing with bank deposits and to avoid creating incentives for runs in stress scenarios. The prohibition extends to indirect benefits such as airdrops, fee rebates conditional on holding, loyalty programs, and yield-bearing wrapped versions of the stablecoin issued by the same group. The aim is to keep FRS as pure payment instruments rather than investment products subject to entirely different regulatory considerations.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 10,
      tags: ['no-interest', 'payment-instrument'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 19',
      articleTitle: 'Disclosure requirements',
      content: 'A licensed FRS issuer must publish monthly attestation reports on the composition and value of reserve assets, and must disclose at all times the total amount of FRS in circulation and the redemption arrangements available to holders.',
      contentEn: 'Section 19 implements transparency standards comparable to leading global frameworks. Monthly attestations must be performed by an independent registered auditor and disclose reserve composition by asset type, custodian and jurisdiction, the par value of outstanding FRS, and any discrepancies. Real-time dashboards showing FRS in circulation are encouraged. Material changes including reserve composition changes, custodian changes, or smart contract modifications must be disclosed promptly to holders and the HKMA.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 11,
      tags: ['disclosure', 'attestation', 'transparency'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 21',
      articleTitle: 'Audit requirements',
      content: 'A licensed FRS issuer must have its annual financial statements audited by a registered public auditor and submit the audited statements to the HKMA together with a report on internal controls.',
      contentEn: 'Section 21 requires full annual audits in addition to monthly attestations. The annual audit must cover financial statements prepared in accordance with HKFRS, the adequacy of internal controls over financial reporting and reserve management, compliance with the Stablecoins Ordinance and license conditions, and any material weaknesses or recommendations. The auditor must be approved by the HKMA and rotation requirements apply to ensure independence.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 12,
      tags: ['audit', 'annual', 'financial-statements'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 23',
      articleTitle: 'AML/CFT obligations',
      content: 'Licensed FRS issuers are designated as financial institutions for the purposes of the Anti-Money Laundering and Counter-Terrorist Financing Ordinance and must comply with all CDD, record-keeping, reporting and internal controls requirements.',
      contentEn: 'Section 23 brings FRS issuers fully within the AMLO regime. Issuers must perform CDD on direct purchasers and redeemers, monitor transactions for suspicious activity, maintain Travel Rule compliance for transfers, implement screening against international sanctions lists, and file STRs with the JFIU. Where stablecoins circulate on permissionless blockchains, issuers must implement on-chain analytics and may be required to freeze or blacklist wallets associated with illicit activity through smart contract controls.',
      chapter: 'Part 4: Operating Requirements',
      sortOrder: 13,
      tags: ['aml', 'cft', 'amlo', 'travel-rule'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 25',
      articleTitle: 'Cross-border offering to Hong Kong persons',
      content: 'Offering, marketing or actively promoting an FRS to the public of Hong Kong is prohibited unless the issuer is licensed under this Ordinance, regardless of where the issuer is incorporated or based.',
      contentEn: 'Section 25 closes the cross-border loophole. Active marketing includes targeted advertising, Hong Kong language promotional content, partnership with Hong Kong distributors, sponsorship of Hong Kong events, and use of Hong Kong-based payment rails. Reverse solicitation by Hong Kong investors approaching offshore issuers entirely on their own initiative remains permitted but the burden of proving reverse solicitation rests with the offshore issuer in any enforcement action.',
      chapter: 'Part 5: Cross-border',
      sortOrder: 14,
      tags: ['cross-border', 'marketing', 'reverse-solicitation'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Section 40',
      articleTitle: 'Penalties for offences',
      content: 'A person who contravenes the licensing requirement, the prohibition on cross-border marketing, or other key obligations under this Ordinance commits an offence and is liable on conviction on indictment to a fine of HK$10 million and to imprisonment for 7 years, with daily default fines of HK$100,000.',
      contentEn: 'Section 40 sets out the penalty structure. The HK$10 million fine and 7 year imprisonment for principal offences reflect the systemic importance of stablecoin regulation. Senior officers including directors and the chief executive may be held personally liable where offences are committed with their consent or connivance. The HKMA may also impose civil penalties, license suspensions or revocations, and may publish details of disciplinary actions to deter misconduct and protect the public.',
      chapter: 'Part 6: Enforcement',
      sortOrder: 15,
      tags: ['penalty', 'offence', 'enforcement'],
      appliesToBiz: ['stablecoin-issuer'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'HK', lawNumber: 'HK-StablecoinsOrd-2024-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'HK',
      lawType: 'ordinance',
      title: 'Stablecoins Ordinance',
      titleEn: 'Stablecoins Ordinance',
      shortName: 'Stablecoins Ordinance',
      lawNumber: 'HK-StablecoinsOrd-2024-EXPANDED',
      enactedDate: new Date('2024-12-06'),
      effectiveDate: new Date('2025-08-01'),
      status: 'enacted',
      regulator: 'HKMA',
      sourceUrl: 'https://www.hkma.gov.hk/eng/key-functions/international-financial-centre/regulatory-regime-for-stablecoin-issuers/',
      totalArticles: stablecoinArticles.length,
      articles: { create: stablecoinArticles },
    },
  });

  // ============================================================
  // 5. Cap 622 - Companies Ordinance
  // ============================================================
  const cap622Articles = [
    {
      articleNum: 'Section 5',
      articleTitle: 'Definition of company',
      content: 'A company means a company formed and registered under this Ordinance or an existing company. Existing company means a company formed and registered under a former Companies Ordinance.',
      contentEn: 'Section 5 defines the basic concept of a Hong Kong company. The Companies Ordinance recognizes private companies limited by shares, public companies limited by shares, companies limited by guarantee, and unlimited companies. Token issuers and VASPs almost universally use private or public companies limited by shares due to the limited liability protection. A Hong Kong company is the prerequisite for VASP licensing under AMLO Part 5A and FRS issuer licensing under the Stablecoins Ordinance.',
      chapter: 'Part 1: Preliminary',
      sortOrder: 1,
      tags: ['definition', 'company'],
      appliesToBiz: ['token-issuer', 'exchange', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 9',
      articleTitle: 'Application for incorporation',
      content: 'An application for incorporation of a company must be delivered to the Registrar of Companies in the specified form, accompanied by the articles of association and the prescribed fee.',
      contentEn: 'Section 9 sets out the incorporation process. Applications include Form NNC1 (or NNC1G for guarantee companies), the proposed articles of association, and identification details for founder members, directors and the company secretary. Hong Kong incorporation typically completes within 4-7 working days for online applications. Token issuers and VASPs should ensure their articles include appropriate provisions for share classes, transfer restrictions, and director powers necessary for their regulated business.',
      chapter: 'Part 2: Incorporation',
      sortOrder: 2,
      tags: ['incorporation', 'registration'],
      appliesToBiz: ['token-issuer', 'exchange', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 379',
      articleTitle: 'Prospectus requirements for shares and debentures',
      content: 'A prospectus must be issued in respect of shares or debentures offered to the public, and must contain all material information to enable investors to make an informed assessment of the issuer and the securities being offered.',
      contentEn: 'Section 379 read with Part XII of the Companies (Winding Up and Miscellaneous Provisions) Ordinance Cap. 32 sets out detailed prospectus content requirements. The prospectus must be authorized for registration by the Companies Registry. Where tokens constitute shares or debentures (i.e. STOs), full prospectus requirements apply unless an exemption such as professional investors only is available. Failure to comply with prospectus requirements is a criminal offence and gives rise to civil liability.',
      chapter: 'Part 12: Prospectus',
      sortOrder: 3,
      tags: ['prospectus', 'public-offer', 'sto'],
      appliesToBiz: ['sto-issuer', 'token-issuer', 'ico-issuer'],
    },
    {
      articleNum: 'Section 405',
      articleTitle: 'Restrictions on offers to the public',
      content: 'A company must not offer shares or debentures to the public unless a prospectus has been issued and registered in compliance with the Ordinance, or an applicable exemption applies.',
      contentEn: 'Section 405 prohibits unregistered public offers, with the principal exemptions being offers to professional investors only, offers to no more than 50 persons, offers where the minimum subscription is HK$500,000 or more, and offers of total value below HK$5 million in any 12-month period. Token issuers structuring private STOs to avoid prospectus requirements typically rely on the professional investors exemption combined with private placement memoranda providing voluntary disclosures.',
      chapter: 'Part 12: Prospectus',
      sortOrder: 4,
      tags: ['public-offer', 'exemption', 'private-placement'],
      appliesToBiz: ['sto-issuer', 'token-issuer', 'ico-issuer'],
    },
    {
      articleNum: 'Section 432',
      articleTitle: 'Directors duties',
      content: 'A director of a company must exercise reasonable care, skill and diligence, and must act in good faith in the best interests of the company. The duty includes both a subjective standard based on the directors actual knowledge, and an objective standard based on what a reasonable person in the same position would do.',
      contentEn: 'Section 432 codifies the directors duty of care, skill and diligence. The objective standard means even non-executive directors are held to the standards of a reasonable director with the general knowledge expected of someone in their position. For directors of token issuers and VASPs, this includes reasonable understanding of the risks of digital assets, AML/CFT obligations, cybersecurity, and the regulatory framework. Breach can give rise to civil liability and disqualification.',
      chapter: 'Part 11: Fair Dealing',
      sortOrder: 5,
      tags: ['directors-duties', 'fiduciary'],
      appliesToBiz: ['token-issuer', 'exchange', 'stablecoin-issuer', 'fund-manager'],
    },
    {
      articleNum: 'Section 459',
      articleTitle: 'General meetings of members',
      content: 'A company must hold an annual general meeting in respect of each financial year, except where dispensed with by unanimous shareholder agreement in the case of single-member companies or by written resolution.',
      contentEn: 'Section 459 establishes shareholder governance requirements. AGMs must consider the financial statements, directors and auditors reports, and any business specified in the notice. Hong Kong has progressively allowed virtual and hybrid meetings, which is particularly useful for token issuer and VASP groups with international shareholders. Notice periods of 21 days for AGMs and 14 days for other general meetings apply unless waived by required majorities.',
      chapter: 'Part 12: Members and Administration',
      sortOrder: 6,
      tags: ['general-meeting', 'agm', 'governance'],
      appliesToBiz: ['token-issuer', 'exchange', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Section 622',
      articleTitle: 'Annual financial statements',
      content: 'A company must prepare for each financial year financial statements that comply with sections 380 to 383, give a true and fair view of the financial position and financial performance of the company, and be audited in accordance with this Ordinance.',
      contentEn: 'Section 622 requires Hong Kong companies to prepare annual audited financial statements in accordance with HKFRS or HKFRS for Private Entities. Statements must be laid before members at the AGM and filed with the Companies Registry (for public companies and guarantee companies) or simply maintained at the registered office (for private companies). For licensed VASPs and FRS issuers, additional regulatory financial reporting to the SFC or HKMA is required on top of Companies Ordinance requirements.',
      chapter: 'Part 9: Accounts and Audit',
      sortOrder: 7,
      tags: ['financial-statements', 'audit', 'annual'],
      appliesToBiz: ['token-issuer', 'exchange', 'stablecoin-issuer', 'fund-manager'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'HK', lawNumber: 'HK-Cap622-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'HK',
      lawType: 'ordinance',
      title: 'Companies Ordinance (Cap. 622)',
      titleEn: 'Companies Ordinance',
      shortName: 'Companies Ordinance / Cap 622',
      lawNumber: 'HK-Cap622-EXPANDED',
      enactedDate: new Date('2014-03-03'),
      effectiveDate: new Date('2014-03-03'),
      status: 'amended',
      regulator: 'Companies Registry',
      sourceUrl: 'https://www.elegislation.gov.hk/hk/cap622',
      totalArticles: cap622Articles.length,
      articles: { create: cap622Articles },
    },
  });

  console.log('HK expanded laws seeded');
}

main().catch(console.error).finally(() => prisma.$disconnect());
