import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('📚 Seeding EU expanded laws...');

  // ============================================================
  // 1. MiCA - Regulation (EU) 2023/1114
  // ============================================================
  const micaArticles = [
    {
      articleNum: 'Article 1',
      articleTitle: 'Subject matter',
      content: 'This Regulation lays down uniform requirements for the offer to the public and admission to trading on a trading platform of crypto-assets other than asset-referenced tokens and e-money tokens, of asset-referenced tokens and of e-money tokens, as well as requirements for crypto-asset service providers. It establishes rules to ensure consumer and investor protection, market integrity and financial stability. It seeks to support innovation and fair competition while addressing risks associated with crypto-assets. The Regulation forms a cornerstone of the EU Digital Finance Strategy.',
      chapter: 'Title I - General Provisions',
      sortOrder: 1,
      tags: ['scope', 'definitions', 'general'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'token-issuer', 'wallet-provider'],
    },
    {
      articleNum: 'Article 2',
      articleTitle: 'Scope',
      content: 'This Regulation applies to natural and legal persons and certain other undertakings that are engaged in the issuance, offer to the public and admission to trading of crypto-assets or that provide services related to crypto-assets in the Union. It does not apply to crypto-assets that qualify as financial instruments under MiFID II, deposits, structured deposits, securitisation, or insurance products. NFTs that are unique and not fungible are generally excluded, except where they are issued in a large series or collection. Central banks and public international bodies are excluded when acting in their monetary authority capacity.',
      chapter: 'Title I - General Provisions',
      sortOrder: 2,
      tags: ['scope', 'exclusions'],
      appliesToBiz: ['exchange', 'token-issuer', 'nft-platform'],
    },
    {
      articleNum: 'Article 3',
      articleTitle: 'Definitions',
      content: 'For the purposes of this Regulation, crypto-asset means a digital representation of a value or of a right that is able to be transferred and stored electronically using distributed ledger technology or similar technology. Asset-referenced token (ART) means a type of crypto-asset that is not an electronic money token and that purports to maintain a stable value by referencing another value or right or a combination thereof, including one or several official currencies. E-money token (EMT) means a type of crypto-asset that purports to maintain a stable value by referencing the value of one official currency. Crypto-asset service provider (CASP) means a legal person whose occupation or business is the provision of one or more crypto-asset services to clients on a professional basis.',
      chapter: 'Title I - General Provisions',
      sortOrder: 3,
      tags: ['definitions', 'art', 'emt', 'casp'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'token-issuer'],
    },
    {
      articleNum: 'Article 16',
      articleTitle: 'Authorisation for issuance of asset-referenced tokens',
      content: 'No person shall offer to the public or seek admission to trading of an asset-referenced token within the Union unless that person is the issuer of that token and has been authorised in accordance with Article 21 by the competent authority of its home Member State, or is a credit institution complying with Article 17. The applicant must be a legal person established in the Union. The authorisation requirement does not apply where the average outstanding value of the ART does not exceed EUR 5 million over 12 months and is offered solely to qualified investors. Issuers must publish a crypto-asset white paper approved by the competent authority before offering ARTs.',
      chapter: 'Title II - ART',
      sortOrder: 4,
      tags: ['authorization', 'art', 'stablecoin'],
      appliesToBiz: ['stablecoin-issuer', 'token-issuer'],
    },
    {
      articleNum: 'Article 17',
      articleTitle: 'Reserve of assets',
      content: 'Issuers of asset-referenced tokens shall constitute and at all times maintain a reserve of assets. The reserve of assets shall be composed and managed in such a way that the risks associated with the assets referenced by the asset-referenced tokens are covered, and the liquidity risks associated with the permanent rights of redemption of the holders are addressed. The reserve must be legally segregated from the issuer\'s own estate and protected from claims by other creditors. At least 30% of EMTs and 60% of ARTs referencing official currencies must be held as deposits in credit institutions, with daily redemption rights at par value.',
      chapter: 'Title II - ART',
      sortOrder: 5,
      tags: ['reserve', 'art', 'liquidity'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 22',
      articleTitle: 'Own funds requirements',
      content: 'Issuers of asset-referenced tokens shall, at all times, have own funds equal to an amount of at least the highest of: EUR 350,000; 2% of the average amount of the reserve of assets; or a quarter of the fixed overheads of the preceding year. The own funds shall consist of Common Equity Tier 1 items and instruments referred to in Articles 26 to 30 of Regulation (EU) No 575/2013 (CRR). Competent authorities may require issuers of significant ARTs to hold up to 3% of the reserve. Own funds must be unencumbered and immediately available to absorb losses.',
      chapter: 'Title II - ART',
      sortOrder: 6,
      tags: ['capital', 'own-funds', 'art'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 23',
      articleTitle: 'Governance arrangements',
      content: 'Issuers of asset-referenced tokens shall have robust governance arrangements, including a clear organisational structure with well-defined, transparent and consistent lines of responsibility, effective processes to identify, manage, monitor and report the risks they are or might be exposed to, and adequate internal control mechanisms. Members of the management body shall be of sufficiently good repute and possess sufficient knowledge, skills and experience to perform their duties. The issuer shall have policies and procedures sufficient to ensure compliance with this Regulation, including compliance by its managers and employees.',
      chapter: 'Title II - ART',
      sortOrder: 7,
      tags: ['governance', 'art', 'risk-management'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 31',
      articleTitle: 'Complaints handling procedures',
      content: 'Issuers of asset-referenced tokens shall establish and maintain effective and transparent procedures for the prompt, fair and consistent handling of complaints received from holders of asset-referenced tokens and other interested parties, including consumer associations that represent holders, and shall publish descriptions of those procedures. Holders shall be allowed to file complaints free of charge. Issuers must inform complainants of the outcome of their investigations within a reasonable period and in any case within the timeframes established by ESMA technical standards.',
      chapter: 'Title II - ART',
      sortOrder: 8,
      tags: ['complaints', 'consumer-protection', 'art'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 32',
      articleTitle: 'Conflicts of interest',
      content: 'Issuers of asset-referenced tokens shall implement and maintain effective policies and procedures to identify, prevent, manage and disclose conflicts of interest between themselves and their shareholders or members, holders of asset-referenced tokens, third parties providing services, custodians of the reserve assets, and any natural person who has direct or indirect control over the issuer. Where organisational or administrative arrangements are not sufficient to ensure that risks of damage to the interests of holders are prevented, issuers must clearly disclose the general nature and sources of conflicts before doing business.',
      chapter: 'Title II - ART',
      sortOrder: 9,
      tags: ['conflicts-of-interest', 'art'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 36',
      articleTitle: 'Significant asset-referenced tokens',
      content: 'EBA shall classify asset-referenced tokens as significant where they meet at least three of the following criteria: number of holders exceeding 10 million; value of issued ARTs exceeding EUR 5 billion; average number and average aggregate value of transactions per day exceeding 2.5 million and EUR 500 million respectively; issuer is a gatekeeper under DMA; significance of cross-border activities; interconnectedness with the financial system. Significant ARTs are subject to additional requirements including direct supervision by EBA, higher own funds (3%), enhanced liquidity, interoperability and recovery plans.',
      chapter: 'Title II - ART',
      sortOrder: 10,
      tags: ['significant', 'art', 'eba-supervision'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 48',
      articleTitle: 'Authorisation for issuance of e-money tokens',
      content: 'No person shall offer to the public or seek admission to trading of an e-money token within the Union unless that person is the issuer of that e-money token and is authorised as a credit institution or as an electronic money institution. E-money tokens are deemed to be electronic money under Directive 2009/110/EC. Issuers must draw up and notify their crypto-asset white paper to the competent authority at least 20 working days before publication. EMT issuers are subject to the prudential and conduct requirements applicable to electronic money institutions.',
      chapter: 'Title III - EMT',
      sortOrder: 11,
      tags: ['emt', 'authorization', 'e-money'],
      appliesToBiz: ['stablecoin-issuer', 'payment-service'],
    },
    {
      articleNum: 'Article 49',
      articleTitle: 'Issuance and redeemability of e-money tokens',
      content: 'Holders of e-money tokens shall be granted a claim against the issuers of those e-money tokens. Any e-money token that is issued at a value that is not equal to the funds received shall be prohibited. Holders shall, at any moment and at par value, be granted the right of redemption of the monetary value of the e-money token held, in funds other than electronic money, from the issuer. Issuers must clearly state the conditions of redemption in the white paper. No interest may be granted by issuers in relation to the length of time during which a holder of an e-money token holds those tokens.',
      chapter: 'Title III - EMT',
      sortOrder: 12,
      tags: ['emt', 'redemption', 'par-value'],
      appliesToBiz: ['stablecoin-issuer', 'payment-service'],
    },
    {
      articleNum: 'Article 51',
      articleTitle: 'Reserve of assets for EMT',
      content: 'Issuers of e-money tokens shall ensure that funds received in exchange for e-money tokens are invested in secure, low-risk assets denominated in the same official currency as the one referenced by the e-money token. At least 30% of the funds received shall always be deposited in separate accounts in credit institutions. The remaining funds shall be invested in highly liquid financial instruments with minimal market and credit risk that can be liquidated rapidly with minimal adverse price effect. Reserve assets must be segregated from the issuer\'s own assets and protected against insolvency.',
      chapter: 'Title III - EMT',
      sortOrder: 13,
      tags: ['emt', 'reserve', 'segregation'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 58',
      articleTitle: 'Significant e-money tokens',
      content: 'EBA shall classify e-money tokens as significant on the basis of similar criteria as for ARTs, including number of holders, value of issuance, transaction volumes, gatekeeper status, and interconnectedness. Issuers of significant EMTs that are not credit institutions become subject to additional requirements substantially similar to those applicable to ART issuers, including direct supervision by EBA, enhanced own funds, liquidity management, recovery and redemption plans. EBA may require interoperability standards and additional reporting from significant EMT issuers.',
      chapter: 'Title III - EMT',
      sortOrder: 14,
      tags: ['emt', 'significant', 'eba'],
      appliesToBiz: ['stablecoin-issuer'],
    },
    {
      articleNum: 'Article 59',
      articleTitle: 'Authorisation of crypto-asset service providers',
      content: 'No person shall provide crypto-asset services within the Union unless that person is a legal person or other undertaking that has been authorised as a crypto-asset service provider in accordance with Article 63, or is a credit institution, central securities depository, investment firm, market operator, electronic money institution, UCITS management company, or alternative investment fund manager that is allowed to provide crypto-asset services pursuant to Article 60. The authorisation shall be valid for the entire Union and shall allow CASPs to provide the services for which they have been authorised throughout the Union via passporting.',
      chapter: 'Title V - CASP',
      sortOrder: 15,
      tags: ['casp', 'authorization', 'passporting'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 60',
      articleTitle: 'Prudential requirements for CASPs',
      content: 'Crypto-asset service providers shall, at all times, have in place prudential safeguards equal to an amount of at least the highest of: the amount of permanent minimum capital requirements indicated in Annex IV depending on the nature of the crypto-asset services provided (EUR 50,000 to EUR 150,000); or one-quarter of the fixed overheads of the preceding year, reviewed annually. The prudential safeguards shall take the form of either own funds or an insurance policy covering the territories of the Union where crypto-asset services are actively provided, or a comparable guarantee.',
      chapter: 'Title V - CASP',
      sortOrder: 16,
      tags: ['casp', 'capital', 'prudential'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 68',
      articleTitle: 'Safekeeping and administration of crypto-assets on behalf of clients',
      content: 'Crypto-asset service providers that provide custody and administration of crypto-assets on behalf of clients shall conclude an agreement with their clients to specify their duties and responsibilities. They shall keep a register of positions opened in the name of each client, corresponding to each client\'s rights to the crypto-assets, and shall update that register without delay. CASPs shall establish a custody policy with internal rules and procedures to ensure the safekeeping or control of such crypto-assets. The means of accessing the crypto-assets, including cryptographic keys, must be safeguarded against loss, fraud, hacking and unauthorised access.',
      chapter: 'Title V - CASP',
      sortOrder: 17,
      tags: ['custody', 'casp', 'safekeeping'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 75',
      articleTitle: 'Complaints handling for CASPs',
      content: 'Crypto-asset service providers shall establish and maintain effective and transparent procedures for the prompt, fair and consistent handling of complaints received from clients and shall publish descriptions of those procedures. Clients shall be able to file complaints free of charge with the CASP. CASPs shall inform clients of the possibility of filing a complaint and shall make available to clients a complaint template and shall keep a record of all complaints received and any measures taken to address them. CASPs shall investigate complaints in a timely and fair manner and communicate the outcome to complainants within a reasonable period.',
      chapter: 'Title V - CASP',
      sortOrder: 18,
      tags: ['complaints', 'casp', 'consumer-protection'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 76',
      articleTitle: 'Conflicts of interest for CASPs',
      content: 'Crypto-asset service providers shall implement and maintain effective policies and procedures, taking into account the scale, the nature and the range of crypto-asset services provided, to identify, prevent, manage and disclose conflicts of interest between themselves, including their managers, employees, and any person directly or indirectly linked to them by control, and their clients, or between two clients. CASPs shall disclose to their clients and potential clients the general nature and sources of conflicts of interest and the steps taken to mitigate them, before undertaking business on their behalf.',
      chapter: 'Title V - CASP',
      sortOrder: 19,
      tags: ['conflicts-of-interest', 'casp'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 79',
      articleTitle: 'Operation of a trading platform for crypto-assets',
      content: 'Crypto-asset service providers operating a trading platform for crypto-assets shall lay down, maintain and implement clear and transparent operating rules for the trading platform. They shall have effective systems, procedures and arrangements to ensure that their trading systems are resilient, have sufficient capacity to deal with peak orders and message volumes, are able to ensure orderly trading under conditions of severe market stress, are subject to effective business continuity arrangements, and are able to reject orders that exceed pre-determined volume and price thresholds. Settlement of crypto-asset transactions executed on the trading platform shall be initiated within 24 hours.',
      chapter: 'Title V - CASP',
      sortOrder: 20,
      tags: ['trading-platform', 'casp', 'settlement'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 80',
      articleTitle: 'Exchange of crypto-assets for funds or other crypto-assets',
      content: 'Crypto-asset service providers exchanging crypto-assets for funds or for other crypto-assets shall establish a non-discriminatory commercial policy that indicates, in particular, the type of clients with whom they agree to enter into transactions and the conditions that must be met by clients. CASPs shall publish a firm price of crypto-assets or a method for determining the price of the crypto-assets they propose for exchange. They shall execute the orders of clients at the prices displayed at the time when the orders are received and shall publish details of any orders placed and transactions concluded, including transaction volumes and prices.',
      chapter: 'Title V - CASP',
      sortOrder: 21,
      tags: ['exchange', 'casp', 'transparency'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 86',
      articleTitle: 'Prohibition of insider dealing',
      content: 'Any person possessing inside information in relation to crypto-assets shall not use that information by acquiring or disposing of, for own account or for the account of a third party, directly or indirectly, those crypto-assets to which that information relates. Any person possessing inside information shall also not recommend or induce another person to engage in insider dealing or disclose that inside information to any other person except where such disclosure is made in the normal exercise of an employment, profession or duties. The prohibition applies to any person possessing inside information by virtue of being a member of the administrative, management or supervisory bodies of the issuer or offeror.',
      chapter: 'Title VI - Market Abuse',
      sortOrder: 22,
      tags: ['market-abuse', 'insider-dealing'],
      appliesToBiz: ['exchange', 'token-issuer'],
    },
    {
      articleNum: 'Article 87',
      articleTitle: 'Prohibition of market manipulation',
      content: 'No person shall engage in or attempt to engage in market manipulation, which shall comprise the following activities: entering into a transaction, placing an order to trade or any other behaviour relating to one or several crypto-assets which gives or is likely to give false or misleading signals as to supply, demand or price; entering into a transaction which secures the price at an abnormal or artificial level; or the dissemination of information through media which gives false or misleading signals as to crypto-assets, including spreading rumours, where the person who made the dissemination knew or ought to have known that the information was false or misleading. Wash trading and pump-and-dump schemes are explicitly prohibited.',
      chapter: 'Title VI - Market Abuse',
      sortOrder: 23,
      tags: ['market-abuse', 'manipulation'],
      appliesToBiz: ['exchange', 'token-issuer'],
    },
    {
      articleNum: 'Article 88',
      articleTitle: 'Public disclosure of inside information',
      content: 'Issuers of crypto-assets, offerors and persons seeking admission to trading shall inform the public as soon as possible of inside information which concerns them, in a manner that enables fast access and complete, correct and timely assessment of the information by the public. The issuer, offeror or person seeking admission to trading shall ensure that the inside information is made public in a manner which enables fast access, free of charge and simultaneous dissemination throughout the Union. They may delay the public disclosure of inside information provided that immediate disclosure is likely to prejudice their legitimate interests, the delay is not likely to mislead the public, and confidentiality can be ensured.',
      chapter: 'Title VI - Market Abuse',
      sortOrder: 24,
      tags: ['disclosure', 'inside-information'],
      appliesToBiz: ['token-issuer', 'exchange'],
    },
    {
      articleNum: 'Article 92',
      articleTitle: 'Administrative penalties and other administrative measures',
      content: 'Member States shall provide that competent authorities have the power to impose administrative penalties and take other administrative measures in relation to infringements of this Regulation. Maximum administrative pecuniary penalties shall be at least: for legal persons, EUR 15 million or 15% of total annual turnover; for breaches of market abuse provisions, up to EUR 5 million or 12.5% of total annual turnover; for natural persons, up to EUR 5 million. Member States may provide for criminal penalties in addition to administrative penalties. Competent authorities also have powers to issue cease-and-desist orders, withdraw authorisations, impose temporary bans, and publicly disclose violations.',
      chapter: 'Title VI - Market Abuse',
      sortOrder: 25,
      tags: ['penalties', 'sanctions', 'enforcement'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'token-issuer'],
    },
    {
      articleNum: 'Article 111',
      articleTitle: 'Transitional measures (grandfathering)',
      content: 'Crypto-asset service providers that provided their services in accordance with applicable law before 30 December 2024 may continue to do so until 1 July 2026 or until they are granted or refused an authorisation pursuant to Article 63, whichever is sooner. Member States may decide not to apply this transitional regime or to reduce its duration where they consider that their applicable national regulatory framework before 30 December 2024 is less strict than this Regulation. Issuers of asset-referenced tokens, other than credit institutions, that have been issuing such tokens before 30 June 2024 may continue to do so until they are granted or refused authorisation, provided they apply for authorisation before 30 July 2024.',
      chapter: 'Title VIII - Transitional',
      sortOrder: 26,
      tags: ['transitional', 'grandfathering'],
      appliesToBiz: ['exchange', 'stablecoin-issuer', 'wallet-provider'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-MiCA-2023-1114-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawNumber: 'EU-MiCA-2023-1114-EXPANDED',
      lawType: 'regulation',
      regulator: 'European Parliament / ESMA / EBA',
      title: 'Regulation (EU) 2023/1114 on Markets in Crypto-Assets (MiCA) - Expanded',
      titleEn: 'Regulation (EU) 2023/1114 on Markets in Crypto-Assets (MiCA) - Expanded',
      enactedDate: new Date('2023-06-09'),
      effectiveDate: new Date('2024-12-30'),
      totalArticles: micaArticles.length,
      articles: { create: micaArticles.map(a => ({ ...a, contentEn: a.content })) },
    },
  });

  // ============================================================
  // 2. DORA - Regulation (EU) 2022/2554
  // ============================================================
  const doraArticles = [
    {
      articleNum: 'Article 5',
      articleTitle: 'Governance and organisation',
      content: 'Financial entities shall have in place an internal governance and control framework that ensures an effective and prudent management of ICT risk, in order to achieve a high level of digital operational resilience. The management body of the financial entity shall define, approve, oversee and be responsible for the implementation of all arrangements related to the ICT risk management framework. Members of the management body shall actively keep up to date with sufficient knowledge and skills to understand and assess ICT risk and its impact on the operations of the financial entity, including by following specific training on a regular basis.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 1,
      tags: ['governance', 'ict-risk', 'management'],
      appliesToBiz: ['exchange', 'payment-service', 'fund-manager'],
    },
    {
      articleNum: 'Article 6',
      articleTitle: 'ICT risk management framework',
      content: 'Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework as part of their overall risk management system. The framework shall include strategies, policies, procedures, ICT protocols and tools that are necessary to duly and effectively protect all information assets and ICT assets. The ICT risk management framework shall be documented and reviewed at least once a year, as well as upon the occurrence of major ICT-related incidents. It shall be subject to internal audit by auditors on a regular basis in line with the audit plan, with auditors possessing sufficient knowledge, skills and expertise in ICT risk.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 2,
      tags: ['ict-risk', 'framework', 'audit'],
      appliesToBiz: ['exchange', 'payment-service', 'fund-manager'],
    },
    {
      articleNum: 'Article 7',
      articleTitle: 'ICT systems, protocols and tools',
      content: 'In order to address and manage ICT risk, financial entities shall use and maintain updated ICT systems, protocols and tools that are appropriate to the magnitude of operations supporting the conduct of their activities, reliable, equipped with sufficient capacity to accurately process the data necessary for the performance of activities and the timely provision of services, and technologically resilient to adequately deal with additional information processing needs as required under stressed market conditions or other adverse situations. ICT systems must be regularly upgraded and patched to address vulnerabilities.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 3,
      tags: ['ict-systems', 'resilience'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 8',
      articleTitle: 'Identification',
      content: 'As part of the ICT risk management framework, financial entities shall identify, classify and adequately document all ICT supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their roles and dependencies in relation to ICT risk. Financial entities shall review as needed, and at least yearly, the adequacy of this classification and any relevant documentation. They shall identify all sources of ICT risk, in particular the risk exposure to and from other financial entities, and assess cyber threats and ICT vulnerabilities relevant to their ICT-supported business functions.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 4,
      tags: ['identification', 'classification', 'asset-management'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 9',
      articleTitle: 'Protection and prevention',
      content: 'For the purposes of adequately protecting ICT systems and with a view to organising response measures, financial entities shall continuously monitor and control the security and functioning of ICT systems and tools and shall minimise the impact of ICT risk on ICT systems through the deployment of appropriate ICT security tools, policies and procedures. Financial entities shall design, procure and implement ICT security policies, procedures, protocols and tools that aim to ensure the resilience, continuity and availability of ICT systems and to maintain high standards of availability, authenticity, integrity and confidentiality of data.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 5,
      tags: ['protection', 'security', 'cia-triad'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 10',
      articleTitle: 'Detection',
      content: 'Financial entities shall have in place mechanisms to promptly detect anomalous activities, including ICT network performance issues and ICT-related incidents, and to identify potential material single points of failure. All detection mechanisms referred to shall be regularly tested. The detection mechanisms shall enable multiple layers of control, define alert thresholds and criteria to trigger and initiate ICT-related incident response processes, including automatic alert mechanisms for relevant staff in charge of ICT-related incident response. Financial entities shall devote sufficient resources and capabilities to monitor user activity, the occurrence of ICT anomalies and ICT-related incidents.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 6,
      tags: ['detection', 'monitoring', 'incident'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 11',
      articleTitle: 'Response and recovery',
      content: 'As part of the ICT risk management framework, and based on the identification requirements, financial entities shall put in place a comprehensive ICT business continuity policy, which may be adopted as a dedicated specific policy, forming an integral part of the overall business continuity policy of the financial entity. Financial entities shall implement the ICT business continuity policy through dedicated, appropriate and documented arrangements, plans, procedures and mechanisms aiming to ensure the continuity of the financial entity\'s critical or important functions, quickly, appropriately and effectively respond to and resolve all ICT-related incidents.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 7,
      tags: ['response', 'recovery', 'business-continuity'],
      appliesToBiz: ['exchange', 'payment-service', 'fund-manager'],
    },
    {
      articleNum: 'Article 12',
      articleTitle: 'Backup policies and recovery methods',
      content: 'For the purposes of ensuring the restoration of ICT systems and data with minimum downtime, limited disruption and loss, as part of their ICT risk management framework, financial entities shall develop and document backup policies and procedures specifying the scope of the data that is subject to the backup and the minimum frequency of the backup, based on the criticality of information or the confidentiality level of the data; restoration and recovery procedures and methods. Backup systems shall begin processing without undue delay, unless such start would jeopardise the security of the network and information systems or the integrity or confidentiality of data.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 8,
      tags: ['backup', 'recovery', 'continuity'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 13',
      articleTitle: 'Learning and evolving',
      content: 'Financial entities shall have in place capabilities and staff to gather information on vulnerabilities and cyber threats, ICT-related incidents, in particular cyber-attacks, and analyse the impact they are likely to have on their digital operational resilience. Financial entities shall put in place post ICT-related incident reviews after a major ICT-related incident disrupts their core activities, analysing the causes of disruption and identifying required improvements to the ICT operations or within the ICT business continuity policy. Financial entities shall monitor the effectiveness of the implementation of their digital operational resilience strategy.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 9,
      tags: ['learning', 'post-incident', 'continuous-improvement'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 14',
      articleTitle: 'Communication',
      content: 'As part of the ICT risk management framework, financial entities shall have in place crisis communication plans enabling a responsible disclosure of, at least, major ICT-related incidents or vulnerabilities to clients and counterparts as well as to the public, as appropriate. As part of the ICT risk management framework, financial entities shall implement communication policies for staff and for external stakeholders. Communication policies for staff shall take into account the need to differentiate between staff involved in ICT risk management, in particular staff in charge of response and recovery, and staff that needs to be informed.',
      chapter: 'Chapter II - ICT Risk Management',
      sortOrder: 10,
      tags: ['communication', 'crisis-management', 'disclosure'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 17',
      articleTitle: 'ICT-related incident management process',
      content: 'Financial entities shall define, establish and implement an ICT-related incident management process to detect, manage and notify ICT-related incidents. Financial entities shall record all ICT-related incidents and significant cyber threats. Financial entities shall establish appropriate procedures and processes to ensure a consistent and integrated monitoring, handling and follow-up of ICT-related incidents, to make sure that root causes are identified, documented and addressed in order to prevent the occurrence of such incidents. The incident management process shall establish early warning indicators, procedures to identify, track, log, categorise and classify incidents according to their priority and severity.',
      chapter: 'Chapter III - Incident Management',
      sortOrder: 11,
      tags: ['incident-management', 'detection', 'response'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 18',
      articleTitle: 'Classification of ICT-related incidents and cyber threats',
      content: 'Financial entities shall classify ICT-related incidents and shall determine their impact based on the following criteria: the number and relevance of clients or financial counterparts affected and, where applicable, the amount or number of transactions affected by the ICT-related incident, and whether the ICT-related incident has caused reputational impact; the duration of the ICT-related incident; the geographical spread; the data losses that the ICT-related incident entails; the criticality of the services affected; the economic impact of the ICT-related incident in absolute and relative terms.',
      chapter: 'Chapter III - Incident Management',
      sortOrder: 12,
      tags: ['classification', 'incident', 'impact-assessment'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 19',
      articleTitle: 'Reporting of major ICT-related incidents',
      content: 'Financial entities shall report major ICT-related incidents to the relevant competent authority. Where a major ICT-related incident occurs and has an impact on the financial interests of clients, financial entities shall, without undue delay as soon as they become aware of it, inform their clients about the major ICT-related incident and about the measures that have been taken to mitigate the adverse effects of such incident. Financial entities shall submit to the competent authority an initial notification within 4 hours, intermediate report within 72 hours, and final report within one month after incident classification.',
      chapter: 'Chapter III - Incident Management',
      sortOrder: 13,
      tags: ['reporting', 'incident', 'notification'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 23',
      articleTitle: 'Digital operational resilience testing',
      content: 'For the purpose of assessing preparedness for handling ICT-related incidents, of identifying weaknesses, deficiencies and gaps in digital operational resilience, and of promptly implementing corrective measures, financial entities shall establish, maintain and review a sound and comprehensive digital operational resilience testing programme as an integral part of the ICT risk management framework. The testing programme shall include a range of assessments, tests, methodologies, practices and tools, including vulnerability assessments and scans, open source analyses, network security assessments, gap analyses, physical security reviews, questionnaires and scanning software solutions, source code reviews, scenario-based tests, compatibility testing, performance testing, end-to-end testing and penetration testing.',
      chapter: 'Chapter IV - Resilience Testing',
      sortOrder: 14,
      tags: ['testing', 'resilience', 'penetration-testing'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 24',
      articleTitle: 'Threat-led penetration testing (TLPT)',
      content: 'Financial entities, other than micro enterprises, that are identified pursuant to specific criteria shall carry out at least every 3 years advanced testing by means of TLPT. Each TLPT shall cover several or all critical or important functions of a financial entity, and shall be performed on live production systems supporting such functions. Financial entities shall identify all relevant underlying ICT systems, processes and technologies supporting critical or important functions and ICT services, including those supporting the critical or important functions which have been outsourced or contracted to ICT third-party service providers. Testers must be certified and external for at least every third TLPT.',
      chapter: 'Chapter IV - Resilience Testing',
      sortOrder: 15,
      tags: ['tlpt', 'penetration-testing', 'red-team'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 28',
      articleTitle: 'General principles for ICT third-party risk',
      content: 'Financial entities shall manage ICT third-party risk as an integral component of ICT risk within their ICT risk management framework. Financial entities shall maintain and update at entity level, and at sub-consolidated and consolidated levels, a register of information in relation to all contractual arrangements on the use of ICT services provided by ICT third-party service providers. Financial entities shall report at least yearly to the competent authorities on the number of new arrangements on the use of ICT services, the categories of ICT third-party service providers, the type of contractual arrangements and the ICT services and functions which are being provided.',
      chapter: 'Chapter V - Third-Party Risk',
      sortOrder: 16,
      tags: ['third-party', 'outsourcing', 'register'],
      appliesToBiz: ['exchange', 'payment-service', 'fund-manager'],
    },
    {
      articleNum: 'Article 30',
      articleTitle: 'Key contractual provisions',
      content: 'The rights and obligations of the financial entity and of the ICT third-party service provider shall be clearly allocated and set out in writing. The full contract shall include the service level agreements and shall be documented in one written document which shall be available to the parties on paper, or in a document with another downloadable, durable and accessible format. Contracts must include clear descriptions of services, locations of data processing, data protection provisions, accessibility, availability, integrity, security and protection of personal data, exit strategies, termination rights, audit and access rights, and cooperation with competent authorities.',
      chapter: 'Chapter V - Third-Party Risk',
      sortOrder: 17,
      tags: ['contract', 'third-party', 'sla'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
    {
      articleNum: 'Article 31',
      articleTitle: 'Designation of critical ICT third-party service providers',
      content: 'The ESAs, through the Joint Committee and upon recommendation from the Oversight Forum, shall designate the ICT third-party service providers that are critical for financial entities, following an assessment that takes into account the systemic impact on the stability, continuity or quality of the provision of financial services in the event that the relevant ICT third-party service provider would face a large scale operational failure to provide its services; the systemic character or importance of the financial entities that rely on the relevant ICT third-party service provider; the reliance of financial entities on the services provided by the relevant ICT third-party service provider; and the degree of substitutability of the ICT third-party service provider.',
      chapter: 'Chapter V - Third-Party Risk',
      sortOrder: 18,
      tags: ['critical-provider', 'oversight', 'systemic'],
      appliesToBiz: ['exchange', 'payment-service'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-DORA-2022-2554-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawNumber: 'EU-DORA-2022-2554-EXPANDED',
      lawType: 'regulation',
      regulator: 'European Parliament / ESMA / EBA',
      title: 'Regulation (EU) 2022/2554 on Digital Operational Resilience for the Financial Sector (DORA)',
      titleEn: 'Regulation (EU) 2022/2554 on Digital Operational Resilience for the Financial Sector (DORA)',
      enactedDate: new Date('2022-12-14'),
      effectiveDate: new Date('2025-01-17'),
      totalArticles: doraArticles.length,
      articles: { create: doraArticles.map(a => ({ ...a, contentEn: a.content })) },
    },
  });

  // ============================================================
  // 3. AMLR 2024 - Regulation (EU) 2024/1624
  // ============================================================
  const amlrArticles = [
    {
      articleNum: 'Article 3',
      articleTitle: 'Definitions - Obliged entities including CASPs',
      content: 'For the purposes of this Regulation, obliged entities means credit institutions, financial institutions, and crypto-asset service providers as defined in Regulation (EU) 2023/1114 (MiCA). The definition of obliged entities under AML scope includes all CASPs providing custody, exchange, transfer, trading platform operation, placing, and advisory services. CASPs are now fully integrated into the EU AML/CFT framework as obliged entities, subject to the same customer due diligence, record-keeping, suspicious transaction reporting and beneficial ownership requirements as traditional financial institutions.',
      chapter: 'Chapter I - General Provisions',
      sortOrder: 1,
      tags: ['definitions', 'casp', 'obliged-entities'],
      appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Article 14',
      articleTitle: 'Customer due diligence - General provisions',
      content: 'Obliged entities shall apply customer due diligence (CDD) measures when establishing a business relationship; when carrying out occasional transactions amounting to EUR 10,000 or more; when carrying out an occasional transfer of funds or crypto-assets exceeding EUR 1,000; when there is a suspicion of money laundering or terrorist financing; and when there are doubts about the veracity or adequacy of previously obtained customer identification data. CDD measures must be applied on a risk-sensitive basis depending on the type of customer, business relationship, product or transaction.',
      chapter: 'Chapter III - CDD',
      sortOrder: 2,
      tags: ['cdd', 'customer-identification'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Article 16',
      articleTitle: 'Standard customer due diligence measures',
      content: 'Standard customer due diligence shall comprise the following measures: identifying the customer and verifying the customer\'s identity on the basis of documents, data or information obtained from a reliable and independent source; identifying the beneficial owner and taking reasonable measures to verify that person\'s identity so that the obliged entity is satisfied that it knows who the beneficial owner is; assessing and, as appropriate, obtaining information on the purpose and intended nature of the business relationship; conducting ongoing monitoring of the business relationship including scrutiny of transactions undertaken throughout the course of that relationship.',
      chapter: 'Chapter III - CDD',
      sortOrder: 3,
      tags: ['cdd', 'kyc', 'verification'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Article 19',
      articleTitle: 'Enhanced customer due diligence',
      content: 'Obliged entities shall apply enhanced customer due diligence measures in cases identified as presenting a higher risk of money laundering or terrorist financing, including business relationships involving high-risk third countries, politically exposed persons (PEPs), correspondent relationships, complex and unusually large transactions, and unusual patterns of transactions which have no apparent economic or lawful purpose. For crypto-asset transfers involving self-hosted wallets above EUR 1,000, CASPs must apply additional verification measures including verifying that the self-hosted wallet is owned or controlled by the customer.',
      chapter: 'Chapter III - CDD',
      sortOrder: 4,
      tags: ['edd', 'high-risk', 'pep'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 22',
      articleTitle: 'Beneficial ownership identification',
      content: 'Obliged entities shall identify the beneficial owner and take reasonable measures to verify the identity of beneficial owners so that they are satisfied that they know who the beneficial owners are. For corporate entities, beneficial ownership shall be presumed where a natural person holds, directly or indirectly, more than 25% of shares or voting rights, or otherwise exercises control. Obliged entities must consult central beneficial ownership registers and document their findings. Where no natural person can be identified after exhausting all means, the senior managing official may be recorded as the beneficial owner.',
      chapter: 'Chapter III - CDD',
      sortOrder: 5,
      tags: ['beneficial-ownership', 'ubo', 'transparency'],
      appliesToBiz: ['exchange', 'wallet-provider', 'fund-manager'],
    },
    {
      articleNum: 'Article 50',
      articleTitle: 'Application of Travel Rule to crypto-asset transfers',
      content: 'Crypto-asset service providers shall ensure that transfers of crypto-assets are accompanied by the name of the originator, the originator\'s account number where such an account exists and is used to process the transaction, or, in the absence of such an account, a unique transaction identifier; the originator\'s address, official personal document number, customer identification number or date and place of birth; the name of the beneficiary; and the beneficiary\'s account number where such an account exists. The Travel Rule applies to all crypto-asset transfers regardless of amount, removing the de minimis threshold previously applicable.',
      chapter: 'Chapter V - Transfers',
      sortOrder: 6,
      tags: ['travel-rule', 'crypto-transfers', 'aml'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 51',
      articleTitle: 'Information accompanying transfers of crypto-assets',
      content: 'CASPs of the originator shall ensure that transfers of crypto-assets are accompanied by complete information on the originator and beneficiary. CASPs of the beneficiary shall implement effective procedures, including, where appropriate, monitoring after or during the transfers, in order to detect whether the information on the originator or the beneficiary is missing. Information may be transmitted via secure messaging protocols separately from the on-chain transfer. CASPs must also assess transfers from or to self-hosted addresses with appropriate risk-based measures, particularly for amounts above EUR 1,000.',
      chapter: 'Chapter V - Transfers',
      sortOrder: 7,
      tags: ['travel-rule', 'information', 'self-hosted'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 57',
      articleTitle: 'Record-keeping requirements',
      content: 'Obliged entities shall retain the following documents and information for the purpose of preventing, detecting and investigating, by the FIU or by other competent authorities, possible money laundering or terrorist financing: in the case of customer due diligence, a copy of the documents and information which are necessary to comply with the customer due diligence requirements, including, where available, information obtained through electronic identification means; the supporting evidence and records of transactions, consisting of the original documents or copies admissible in judicial proceedings under the applicable national law. Records must be kept for 5 years after the end of the business relationship or the date of the occasional transaction.',
      chapter: 'Chapter VI - Records',
      sortOrder: 8,
      tags: ['record-keeping', 'documentation', 'retention'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Article 58',
      articleTitle: 'Suspicious transaction reporting',
      content: 'Obliged entities and, where applicable, their directors and employees shall cooperate fully with the FIU by promptly informing the FIU, including by filing a report, on their own initiative, where the obliged entity knows, suspects or has reasonable grounds to suspect that funds or crypto-assets, regardless of the amount involved, are the proceeds of criminal activity or are related to terrorist financing. They shall also promptly respond to requests by the FIU for additional information. Obliged entities shall refrain from carrying out transactions which they know or suspect to be related to money laundering or terrorist financing until they have completed reporting actions.',
      chapter: 'Chapter VII - Reporting',
      sortOrder: 9,
      tags: ['str', 'suspicious-transaction', 'fiu'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Article 77',
      articleTitle: 'AMLA direct supervision',
      content: 'The Anti-Money Laundering Authority (AMLA) shall directly supervise selected obliged entities including credit institutions, financial institutions, and crypto-asset service providers that operate cross-border in multiple Member States and present the highest risk profiles. AMLA will periodically select up to 40 obliged entities for direct supervision based on risk assessments. Selected entities will be subject to AMLA\'s investigatory and supervisory powers, including on-site inspections, requests for information, imposition of administrative pecuniary sanctions, and imposition of periodic penalty payments. CASPs operating in 6 or more Member States are particularly likely to fall under AMLA direct supervision.',
      chapter: 'Chapter IX - Supervision',
      sortOrder: 10,
      tags: ['amla', 'supervision', 'cross-border'],
      appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer'],
    },
    {
      articleNum: 'Article 80',
      articleTitle: 'Cash payment limits',
      content: 'Member States shall ensure that natural or legal persons trading in goods or providing services may accept or make a payment in cash only up to an amount of EUR 10,000 or equivalent amount in national or foreign currency, whether the transaction is carried out in a single operation or in several operations which appear to be linked. The limit applies to all transactions including those involving precious metals, vehicles, art and antiques. Anonymous crypto-asset accounts and accounts allowing anonymisation of transactions are prohibited. Privacy coins and mixing services that obscure the audit trail are subject to enhanced scrutiny or prohibition.',
      chapter: 'Chapter X - Limits',
      sortOrder: 11,
      tags: ['cash-limits', 'anonymity', 'privacy-coins'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 81',
      articleTitle: 'Prohibition of anonymous crypto accounts',
      content: 'Credit institutions, financial institutions and crypto-asset service providers shall be prohibited from keeping anonymous accounts, anonymous passbooks, anonymous safe-deposit boxes or anonymous crypto-asset accounts as well as any account otherwise allowing for the anonymisation of the customer account holder. CASPs are prohibited from providing services for crypto-assets that have inbuilt anonymisation functions, unless the originator and beneficiary can be identified by the CASP. Existing anonymous accounts must undergo customer due diligence as a matter of priority and in any event before any use is made of them.',
      chapter: 'Chapter X - Limits',
      sortOrder: 12,
      tags: ['anonymity', 'privacy-coins', 'prohibition'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-AMLR-2024-1624-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawNumber: 'EU-AMLR-2024-1624-EXPANDED',
      lawType: 'regulation',
      regulator: 'European Parliament / AMLA',
      title: 'Regulation (EU) 2024/1624 on Anti-Money Laundering (AMLR)',
      titleEn: 'Regulation (EU) 2024/1624 on Anti-Money Laundering (AMLR)',
      enactedDate: new Date('2024-05-30'),
      effectiveDate: new Date('2027-07-01'),
      totalArticles: amlrArticles.length,
      articles: { create: amlrArticles.map(a => ({ ...a, contentEn: a.content })) },
    },
  });

  // ============================================================
  // 4. EU TFR - Regulation (EU) 2023/1113
  // ============================================================
  const tfrArticles = [
    {
      articleNum: 'Article 1',
      articleTitle: 'Subject matter and scope',
      content: 'This Regulation lays down rules on the information on payers and payees, accompanying transfers of funds, in any currency, and the information on originators and beneficiaries, accompanying transfers of crypto-assets, for the purposes of preventing, detecting and investigating money laundering and terrorist financing, where at least one of the payment service providers or crypto-asset service providers involved in the transfer of funds or crypto-assets is established or has its registered office in the Union. The Regulation extends FATF Recommendation 16 (Travel Rule) to crypto-asset transfers in the EU.',
      chapter: 'Chapter I - General',
      sortOrder: 1,
      tags: ['scope', 'travel-rule'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Article 3',
      articleTitle: 'Definitions',
      content: 'For the purposes of this Regulation: transfer of crypto-assets means any transaction aimed at moving crypto-assets from one distributed ledger address, crypto-asset account or other device allowing the storage of crypto-assets, to another, carried out by at least one CASP acting on behalf of either an originator or a beneficiary; originator means a person that holds a crypto-asset account with a CASP, or a distributed ledger address, and allows a transfer of crypto-assets from that account or that distributed ledger address; beneficiary means a person that is the intended recipient of the transfer of crypto-assets; self-hosted address means a distributed ledger address that is not linked to a CASP or to an entity not established in the Union providing services similar to those of a CASP.',
      chapter: 'Chapter I - General',
      sortOrder: 2,
      tags: ['definitions', 'self-hosted', 'casp'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 14',
      articleTitle: 'Information accompanying transfers of funds',
      content: 'The payment service provider of the payer shall ensure that transfers of funds are accompanied by the following information on the payer: name of the payer; payer\'s payment account number; payer\'s address, official personal document number, customer identification number or date and place of birth. The payment service provider shall also ensure that transfers of funds are accompanied by the name of the payee and the payee\'s payment account number. Before transferring the funds, the PSP of the payer shall verify the accuracy of the information on the payer on the basis of documents, data or information obtained from a reliable and independent source.',
      chapter: 'Chapter II - Funds',
      sortOrder: 3,
      tags: ['travel-rule', 'funds', 'psp'],
      appliesToBiz: ['payment-service'],
    },
    {
      articleNum: 'Article 14a',
      articleTitle: 'Information on transfers of crypto-assets',
      content: 'The crypto-asset service provider of the originator shall ensure that transfers of crypto-assets are accompanied by the following information on the originator: name; distributed ledger address, where a transfer of crypto-assets is registered on a network using DLT, and the originator\'s crypto-asset account number, where such an account exists and is used to process the transaction; address, official personal document number, customer identification number, or date and place of birth. The CASP shall also ensure transfers are accompanied by the name and account number/DLT address of the beneficiary. Unlike traditional wire transfers, NO de minimis threshold applies to crypto-asset transfers - the Travel Rule applies to ALL transfers regardless of value.',
      chapter: 'Chapter II - Crypto',
      sortOrder: 4,
      tags: ['travel-rule', 'crypto', 'no-threshold'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 15',
      articleTitle: 'Verification of originator information',
      content: 'Before transferring crypto-assets, the CASP of the originator shall verify the accuracy of the information on the originator on the basis of documents, data or information obtained from a reliable and independent source. Verification shall be deemed to have taken place where the originator\'s identity has been verified in accordance with the AML Regulation and the information obtained from such verification has been stored. The CASP shall not execute any transfer of crypto-assets before ensuring full compliance with this Regulation.',
      chapter: 'Chapter II - Crypto',
      sortOrder: 5,
      tags: ['verification', 'originator', 'casp'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 16',
      articleTitle: 'Obligations of beneficiary CASP',
      content: 'The crypto-asset service provider of the beneficiary shall implement effective procedures, including, where appropriate, monitoring after or during the transfers, to detect whether the information on the originator and the beneficiary is included in, or follows, the transfer of crypto-assets. The CASP of the beneficiary shall, before making the crypto-assets available to the beneficiary, verify the accuracy of the information on the beneficiary on the basis of documents, data or information obtained from a reliable and independent source. Where information is missing or incomplete, the beneficiary CASP must take risk-based measures.',
      chapter: 'Chapter II - Crypto',
      sortOrder: 6,
      tags: ['beneficiary', 'verification', 'monitoring'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 17',
      articleTitle: 'Transfers with missing or incomplete information',
      content: 'The crypto-asset service provider of the beneficiary shall implement effective risk-based procedures, including procedures based on the risk-sensitive basis to determine whether to execute, reject or suspend a transfer of crypto-assets lacking the required complete information on the originator and the beneficiary, and to determine the appropriate follow-up action. Where the CASP of the beneficiary becomes aware that an originator CASP repeatedly fails to provide the required information, the beneficiary CASP shall take steps which may initially include the issuing of warnings and setting of deadlines, before either rejecting any future transfers from that CASP, restricting business relations, or terminating the business relationship.',
      chapter: 'Chapter II - Crypto',
      sortOrder: 7,
      tags: ['missing-information', 'risk-based', 'sanctions'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 19',
      articleTitle: 'Transfers involving self-hosted addresses',
      content: 'Where a transfer of crypto-assets is made to or from a self-hosted address, the crypto-asset service provider shall collect and retain the required information on its customer (originator or beneficiary), and shall ensure that the transfer can be individually identified. For transfers exceeding EUR 1,000 to or from self-hosted addresses, the CASP shall verify whether the self-hosted address is owned or controlled by the customer through appropriate technical means including cryptographic signature verification, micro-transaction verification, or other satoshi-test methods. The CASP shall apply enhanced monitoring and may report transfers from self-hosted addresses as suspicious where appropriate.',
      chapter: 'Chapter II - Crypto',
      sortOrder: 8,
      tags: ['self-hosted', 'unhosted-wallet', 'verification'],
      appliesToBiz: ['exchange', 'wallet-provider'],
    },
    {
      articleNum: 'Article 21',
      articleTitle: 'Sanctions and measures',
      content: 'Member States shall lay down the rules on administrative sanctions and measures applicable to infringements of the provisions of this Regulation and shall take all measures necessary to ensure that they are implemented. The sanctions and measures shall be effective, proportionate and dissuasive and shall be in line with those laid down in accordance with Chapter VI, Section 4, of Directive (EU) 2015/849. Maximum administrative pecuniary sanctions shall be at least EUR 5 million or 10% of the total annual turnover for legal persons, and at least EUR 5 million for natural persons. Competent authorities have powers including public statements, cease and desist orders, withdrawal of authorisation, and temporary bans.',
      chapter: 'Chapter III - Sanctions',
      sortOrder: 9,
      tags: ['sanctions', 'penalties', 'enforcement'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
    {
      articleNum: 'Article 26',
      articleTitle: 'Data protection',
      content: 'The processing of personal data under this Regulation shall be subject to Regulation (EU) 2016/679 (GDPR). Personal data processed under this Regulation by the Commission or by the EBA shall be subject to Regulation (EU) 2018/1725. Payment service providers and crypto-asset service providers shall provide new clients, before establishing a business relationship or carrying out an occasional transaction, with the information required pursuant to Article 13 of the GDPR. Personal data on the basis of this Regulation shall be processed by PSPs and CASPs only on the basis of this Regulation and shall not be further processed in a way incompatible with that purpose.',
      chapter: 'Chapter IV - Data Protection',
      sortOrder: 10,
      tags: ['gdpr', 'data-protection', 'privacy'],
      appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-TFR-2023-1113-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawNumber: 'EU-TFR-2023-1113-EXPANDED',
      lawType: 'regulation',
      regulator: 'European Parliament / EBA',
      title: 'Regulation (EU) 2023/1113 on Information Accompanying Transfers of Funds and Crypto-Assets (TFR)',
      titleEn: 'Regulation (EU) 2023/1113 on Information Accompanying Transfers of Funds and Crypto-Assets (TFR)',
      enactedDate: new Date('2023-05-31'),
      effectiveDate: new Date('2024-12-30'),
      totalArticles: tfrArticles.length,
      articles: { create: tfrArticles.map(a => ({ ...a, contentEn: a.content })) },
    },
  });

  // ============================================================
  // 5. DLT Pilot Regime - Regulation (EU) 2022/858
  // ============================================================
  const dltArticles = [
    {
      articleNum: 'Article 1',
      articleTitle: 'Subject matter and scope',
      content: 'This Regulation lays down requirements in relation to DLT market infrastructures and their operators concerning: granting and withdrawing specific permissions to operate DLT market infrastructures; granting, modifying and withdrawing exemptions related to those specific permissions; the imposition, modification and withdrawal of conditions attached to exemptions and the imposition, modification and withdrawal of compensatory or corrective measures; the operation of DLT market infrastructures; and the supervision of DLT market infrastructures and cooperation between operators of DLT market infrastructures, competent authorities and ESMA. The pilot regime allows experimentation with tokenized financial instruments under temporary exemptions.',
      chapter: 'Chapter I - General',
      sortOrder: 1,
      tags: ['dlt', 'pilot-regime', 'scope'],
      appliesToBiz: ['exchange', 'sto-issuer', 'rwa-issuer'],
    },
    {
      articleNum: 'Article 3',
      articleTitle: 'Restrictions on DLT financial instruments',
      content: 'Only DLT financial instruments that meet the following conditions shall be admitted to trading on or recorded on a DLT market infrastructure: shares whose issuer has a market capitalisation, or a tentative market capitalisation, of less than EUR 500 million; bonds, other forms of securitised debt, including depositary receipts in respect of such securities, or money market instruments, with an issue size of less than EUR 1 billion (excluding sovereign bonds); units in collective investment undertakings whose market value of the assets under management is less than EUR 500 million. The total market value of all DLT financial instruments admitted to trading on a DLT MTF or recorded on a DLT SS shall not exceed EUR 6 billion at the moment of admission of new DLT financial instruments.',
      chapter: 'Chapter II - Requirements',
      sortOrder: 2,
      tags: ['dlt', 'thresholds', 'restrictions'],
      appliesToBiz: ['exchange', 'sto-issuer'],
    },
    {
      articleNum: 'Article 4',
      articleTitle: 'Requirements for DLT MTFs',
      content: 'A DLT multilateral trading facility shall be subject to the requirements applicable to an MTF under MiFID II and MiFIR, except where granted exemptions. The operator of a DLT MTF shall have in place a clear and detailed business plan describing how it intends to provide its services and conduct its activities, which shall include a description of the critical staff, the technical aspects and use of DLT, and the information required pursuant to the regulatory technical standards. The operator must establish detailed rules on the functioning of the DLT used, including rules to access the DLT, the participation of the validating nodes, the addressing of potential conflicts of interest, and risk management measures.',
      chapter: 'Chapter II - Requirements',
      sortOrder: 3,
      tags: ['dlt-mtf', 'mifid', 'requirements'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 5',
      articleTitle: 'Requirements for DLT settlement systems',
      content: 'A DLT settlement system shall be subject to the requirements applicable to a securities settlement system under Regulation (EU) No 909/2014 (CSDR) and to the operator thereof, except where granted exemptions. The operator of a DLT SS shall establish clear and detailed business plans describing the use of DLT, technical arrangements, settlement procedures, and operational risk management. The DLT SS shall have arrangements to ensure the safekeeping of DLT financial instruments and any cash, including against loss of access to or use of the DLT, including via cryptographic key management.',
      chapter: 'Chapter II - Requirements',
      sortOrder: 4,
      tags: ['dlt-ss', 'csdr', 'settlement'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 7',
      articleTitle: 'Exemptions from CSDR for DLT settlement systems',
      content: 'The operator of a DLT settlement system may request the competent authority to be exempted from the application of certain provisions of Regulation (EU) No 909/2014, in particular: the requirement for intermediation by a CSD participant; the requirement to use book-entry form; the requirement for transfer orders to be entered into the system; cash settlement requirements; certain participant requirements. Each exemption shall be subject to conditions imposed by the competent authority to ensure investor protection, market integrity and financial stability, including compensatory measures to address the risks that the exempted requirements were intended to mitigate.',
      chapter: 'Chapter III - Exemptions',
      sortOrder: 5,
      tags: ['exemptions', 'csdr', 'dlt-ss'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 8',
      articleTitle: 'Specific permission to operate a DLT MTF',
      content: 'A legal person that is authorised as an investment firm or that is authorised to operate a regulated market under MiFID II may apply for a specific permission to operate a DLT multilateral trading facility under this Regulation. The application for specific permission shall include a business plan, the rules of the DLT MTF, the legal terms governing the relationship with members or participants, the use and functioning of the DLT, the operational risk management framework, IT and cyber arrangements, evidence of sufficient prudential safeguards, and arrangements for safekeeping of clients\' DLT financial instruments and funds. The competent authority shall assess the application within 6 months.',
      chapter: 'Chapter IV - Authorisation',
      sortOrder: 6,
      tags: ['authorization', 'dlt-mtf', 'permission'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 9',
      articleTitle: 'Specific permission for DLT settlement systems',
      content: 'A legal person that is authorised as a CSD under Regulation (EU) No 909/2014 may apply for a specific permission to operate a DLT settlement system under this Regulation. The competent authority shall assess the application within 6 months from the receipt of a complete application. The specific permission shall be valid throughout the Union and for a period of up to 6 years from the date of issue. The pilot regime allows entities not currently authorised as CSDs to operate DLT SSs under specific conditions and exemptions, fostering innovation in post-trade infrastructure.',
      chapter: 'Chapter IV - Authorisation',
      sortOrder: 7,
      tags: ['authorization', 'dlt-ss', 'permission'],
      appliesToBiz: ['exchange'],
    },
    {
      articleNum: 'Article 16',
      articleTitle: 'Cooperation with competent authorities and ESMA',
      content: 'Operators of DLT market infrastructures shall cooperate with competent authorities, which are entrusted with the granting of specific permissions under this Regulation, and with ESMA. In particular, operators of DLT market infrastructures shall, immediately upon becoming aware of any of the following events, inform those competent authorities and ESMA: any proposed material change to their business plan, including in relation to critical staff, evidence of prudential safeguards, the rules of the DLT market infrastructure and the legal terms; any evidence of unauthorised access, material malfunction, loss, cyber attacks or other cyber threats, fraud, theft or other serious malpractice; any material changes to the information set out in the application.',
      chapter: 'Chapter V - Cooperation',
      sortOrder: 8,
      tags: ['cooperation', 'reporting', 'esma'],
      appliesToBiz: ['exchange'],
    },
  ];

  await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-DLT-2022-858-EXPANDED' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawNumber: 'EU-DLT-2022-858-EXPANDED',
      lawType: 'regulation',
      regulator: 'European Parliament / ESMA',
      title: 'Regulation (EU) 2022/858 on a Pilot Regime for Market Infrastructures Based on Distributed Ledger Technology',
      titleEn: 'Regulation (EU) 2022/858 on a Pilot Regime for Market Infrastructures Based on Distributed Ledger Technology',
      enactedDate: new Date('2022-06-09'),
      effectiveDate: new Date('2023-03-23'),
      totalArticles: dltArticles.length,
      articles: { create: dltArticles.map(a => ({ ...a, contentEn: a.content })) },
    },
  });

  console.log('✅ EU expanded laws seeded');
}

main().catch(console.error).finally(() => prisma.$disconnect());
