// prisma/seed-law-archive-eu2.ts
// Run: npx tsx prisma/seed-law-archive-eu2.ts
// Seeds the law archive with additional EU digital asset regulations

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('📚 Seeding EU additional laws...');

  // ═══════════════════════════════════════════════════════════
  // EU: MiCA Additional Articles (Regulation 2023/1114)
  // Markets in Crypto-Assets Regulation — supplementary articles
  // ═══════════════════════════════════════════════════════════
  const micaAdditional = await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-2023/1114' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawType: 'regulation',
      title: 'Regulation (EU) 2023/1114 — Markets in Crypto-Assets (MiCA)',
      titleEn: 'Regulation (EU) 2023/1114 — Markets in Crypto-Assets (MiCA)',
      shortName: 'MiCA',
      lawNumber: 'EU-2023/1114',
      enactedDate: new Date('2023-06-09'),
      effectiveDate: new Date('2024-12-30'),
      status: 'enacted',
      regulator: 'European Parliament / EBA / ESMA',
      sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2023/1114/oj',
      totalArticles: 15,
      articles: {
        create: [
          {
            articleNum: 'Article 16',
            articleTitle: 'Obligations of issuers of asset-referenced tokens — Authorisation',
            content: 'Issuers of asset-referenced tokens (ARTs) must obtain authorisation from the competent authority of their home Member State before offering such tokens to the public or seeking their admission to trading. The application for authorisation must include a detailed crypto-asset white paper, a description of the governance arrangements, the reserve of assets mechanism, and the custody arrangements. The competent authority shall assess the application within three months and may refuse authorisation if the applicant does not meet the requirements of this Regulation or if the management body poses risks to the sound and prudent management of the issuer.',
            contentEn: 'Issuers of asset-referenced tokens (ARTs) must obtain authorisation from the competent authority of their home Member State before offering such tokens to the public or seeking their admission to trading. The application for authorisation must include a detailed crypto-asset white paper, a description of the governance arrangements, the reserve of assets mechanism, and the custody arrangements. The competent authority shall assess the application within three months and may refuse authorisation if the applicant does not meet the requirements of this Regulation or if the management body poses risks to the sound and prudent management of the issuer.',
            chapter: 'Title III — Asset-Referenced Tokens',
            sortOrder: 1,
            tags: ['art', 'authorisation', 'competent-authority', 'white-paper', 'governance'],
            appliesToBiz: ['stablecoin-issuer', 'token-issuer'],
          },
          {
            articleNum: 'Article 17',
            articleTitle: 'Obligations of issuers of asset-referenced tokens — Reserve of assets',
            content: 'Issuers of asset-referenced tokens shall constitute and maintain at all times a reserve of assets corresponding to the outstanding value of the tokens issued. The reserve must be composed of highly liquid assets with minimal market and credit risk, must be segregated from the issuer\'s own assets, and shall not be encumbered or pledged as collateral. The custody of reserve assets must be entrusted to credit institutions or authorised crypto-asset service providers, and the issuer must ensure adequate diversification of custodians to avoid concentration risk. An independent audit of the reserve must be conducted at least every six months.',
            contentEn: 'Issuers of asset-referenced tokens shall constitute and maintain at all times a reserve of assets corresponding to the outstanding value of the tokens issued. The reserve must be composed of highly liquid assets with minimal market and credit risk, must be segregated from the issuer\'s own assets, and shall not be encumbered or pledged as collateral. The custody of reserve assets must be entrusted to credit institutions or authorised crypto-asset service providers, and the issuer must ensure adequate diversification of custodians to avoid concentration risk. An independent audit of the reserve must be conducted at least every six months.',
            chapter: 'Title III — Asset-Referenced Tokens',
            sortOrder: 2,
            tags: ['art', 'reserve', 'custody', 'segregation', 'audit', 'liquid-assets'],
            appliesToBiz: ['stablecoin-issuer', 'token-issuer'],
          },
          {
            articleNum: 'Article 19',
            articleTitle: 'Rights of holders of asset-referenced tokens',
            content: 'Holders of asset-referenced tokens shall have a permanent right of redemption against the issuer at market value. The issuer must establish clear and detailed policies on the conditions and procedures for redemption, including the applicable timeframes. The redemption right ensures that holders can at any time request the issuer to redeem their tokens in exchange for funds denominated in the fiat currency referenced by the token or in the assets used as a reference. The issuer shall not charge excessive fees for redemption, and the redemption process shall be completed without undue delay.',
            contentEn: 'Holders of asset-referenced tokens shall have a permanent right of redemption against the issuer at market value. The issuer must establish clear and detailed policies on the conditions and procedures for redemption, including the applicable timeframes. The redemption right ensures that holders can at any time request the issuer to redeem their tokens in exchange for funds denominated in the fiat currency referenced by the token or in the assets used as a reference. The issuer shall not charge excessive fees for redemption, and the redemption process shall be completed without undue delay.',
            chapter: 'Title III — Asset-Referenced Tokens',
            sortOrder: 3,
            tags: ['art', 'redemption', 'holder-rights', 'market-value', 'consumer-protection'],
            appliesToBiz: ['stablecoin-issuer', 'token-issuer', 'exchange'],
          },
          {
            articleNum: 'Article 36',
            articleTitle: 'Classification of asset-referenced tokens as significant',
            content: 'An asset-referenced token shall be classified as significant where it meets at least three of the following criteria: the size of the customer base exceeds 10 million holders, the market capitalisation exceeds EUR 5 billion, the number and value of daily transactions exceed specified thresholds, or the issuer is classified as a gatekeeper under the Digital Markets Act. Issuers of significant ARTs are subject to additional requirements including higher own funds (at least EUR 500,000 or 3% of the average reserve), enhanced liquidity management policies, interoperability requirements, and direct supervision by the European Banking Authority (EBA) rather than national competent authorities.',
            contentEn: 'An asset-referenced token shall be classified as significant where it meets at least three of the following criteria: the size of the customer base exceeds 10 million holders, the market capitalisation exceeds EUR 5 billion, the number and value of daily transactions exceed specified thresholds, or the issuer is classified as a gatekeeper under the Digital Markets Act. Issuers of significant ARTs are subject to additional requirements including higher own funds (at least EUR 500,000 or 3% of the average reserve), enhanced liquidity management policies, interoperability requirements, and direct supervision by the European Banking Authority (EBA) rather than national competent authorities.',
            chapter: 'Title III — Asset-Referenced Tokens',
            sortOrder: 4,
            tags: ['art', 'significant-token', 'eba-supervision', 'own-funds', 'thresholds'],
            appliesToBiz: ['stablecoin-issuer', 'token-issuer'],
          },
          {
            articleNum: 'Article 48',
            articleTitle: 'E-money token — Authorisation',
            content: 'Only entities authorised as credit institutions under the Capital Requirements Regulation or as electronic money institutions under the E-Money Directive (2009/110/EC) may issue e-money tokens (EMTs) to the public within the EU. The issuer must publish a crypto-asset white paper and notify the competent authority at least 40 working days before issuance. The white paper must describe the token, the issuer, the rights and obligations attached, the underlying technology, and the risks. No authorisation under MiCA is required in addition to the existing e-money or credit institution licence, but the issuer must comply with all applicable MiCA obligations for EMTs.',
            contentEn: 'Only entities authorised as credit institutions under the Capital Requirements Regulation or as electronic money institutions under the E-Money Directive (2009/110/EC) may issue e-money tokens (EMTs) to the public within the EU. The issuer must publish a crypto-asset white paper and notify the competent authority at least 40 working days before issuance. The white paper must describe the token, the issuer, the rights and obligations attached, the underlying technology, and the risks. No authorisation under MiCA is required in addition to the existing e-money or credit institution licence, but the issuer must comply with all applicable MiCA obligations for EMTs.',
            chapter: 'Title IV — E-Money Tokens',
            sortOrder: 5,
            tags: ['emt', 'authorisation', 'credit-institution', 'e-money-institution', 'white-paper'],
            appliesToBiz: ['stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: 'Article 49',
            articleTitle: 'E-money token — Issuance and redeemability at par value',
            content: 'Issuers of e-money tokens must issue the tokens at par value upon receipt of funds and must redeem them at par value in the official currency referenced by the token at any time and upon request by the holder. The conditions of redemption must be clearly stated in the crypto-asset white paper. Issuers are strictly prohibited from granting interest or any other benefit related to the length of time a holder holds the e-money tokens, as this would fundamentally alter the nature of the token from a payment instrument to an investment product. The no-interest rule applies to both the issuer and any third party acting on its behalf.',
            contentEn: 'Issuers of e-money tokens must issue the tokens at par value upon receipt of funds and must redeem them at par value in the official currency referenced by the token at any time and upon request by the holder. The conditions of redemption must be clearly stated in the crypto-asset white paper. Issuers are strictly prohibited from granting interest or any other benefit related to the length of time a holder holds the e-money tokens, as this would fundamentally alter the nature of the token from a payment instrument to an investment product. The no-interest rule applies to both the issuer and any third party acting on its behalf.',
            chapter: 'Title IV — E-Money Tokens',
            sortOrder: 6,
            tags: ['emt', 'par-value', 'redemption', 'no-interest', 'payment-instrument'],
            appliesToBiz: ['stablecoin-issuer', 'payment-service', 'exchange'],
          },
          {
            articleNum: 'Article 51',
            articleTitle: 'E-money token — Investment of funds received in exchange for EMTs',
            content: 'Funds received by the issuer in exchange for e-money tokens must be invested in secure, low-risk assets denominated in the same official currency as that referenced by the e-money token. The reserve assets must consist of bank deposits, highly liquid financial instruments with minimal market and credit risk, or government bonds with a residual maturity of no more than 2.5 years. At least 30% of the funds shall be held in bank deposits spread across credit institutions. The investment policy must be clearly disclosed and the reserve must at all times match or exceed the total value of outstanding e-money tokens. These restrictions are designed to ensure the issuer can always honour redemption requests promptly.',
            contentEn: 'Funds received by the issuer in exchange for e-money tokens must be invested in secure, low-risk assets denominated in the same official currency as that referenced by the e-money token. The reserve assets must consist of bank deposits, highly liquid financial instruments with minimal market and credit risk, or government bonds with a residual maturity of no more than 2.5 years. At least 30% of the funds shall be held in bank deposits spread across credit institutions. The investment policy must be clearly disclosed and the reserve must at all times match or exceed the total value of outstanding e-money tokens. These restrictions are designed to ensure the issuer can always honour redemption requests promptly.',
            chapter: 'Title IV — E-Money Tokens',
            sortOrder: 7,
            tags: ['emt', 'reserve', 'investment-restrictions', 'bank-deposits', 'government-bonds'],
            appliesToBiz: ['stablecoin-issuer', 'payment-service'],
          },
          {
            articleNum: 'Article 76',
            articleTitle: 'CASP — Outsourcing',
            content: 'Crypto-asset service providers (CASPs) that outsource operational functions to third parties remain fully responsible and liable for the performance of those functions. CASPs must ensure that outsourcing arrangements do not impair the quality of their internal controls or the ability of competent authorities to supervise them. The outsourcing of critical or important functions requires prior notification to the competent authority and must not result in the delegation of the CASP\'s senior management responsibilities. CASPs must conduct thorough due diligence on third-party providers, include appropriate termination clauses and data access rights in their contracts, and maintain contingency plans in case the outsourced service is disrupted.',
            contentEn: 'Crypto-asset service providers (CASPs) that outsource operational functions to third parties remain fully responsible and liable for the performance of those functions. CASPs must ensure that outsourcing arrangements do not impair the quality of their internal controls or the ability of competent authorities to supervise them. The outsourcing of critical or important functions requires prior notification to the competent authority and must not result in the delegation of the CASP\'s senior management responsibilities. CASPs must conduct thorough due diligence on third-party providers, include appropriate termination clauses and data access rights in their contracts, and maintain contingency plans in case the outsourced service is disrupted.',
            chapter: 'Title V — Crypto-Asset Service Providers',
            sortOrder: 8,
            tags: ['casp', 'outsourcing', 'third-party', 'internal-controls', 'due-diligence'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'data-analytics'],
          },
          {
            articleNum: 'Article 79',
            articleTitle: 'CASP — Custody and administration of crypto-assets',
            content: 'CASPs providing custody and administration of crypto-assets on behalf of clients must establish and implement a custody policy that sets out the internal rules and procedures to ensure the safekeeping of clients\' crypto-assets or the means of access thereto. CASPs are liable for losses arising from ICT-related incidents, including cyber-attacks, unless they can prove the loss arose from an event beyond their reasonable control. They must segregate clients\' crypto-assets from their own holdings, maintain accurate records of positions for each client, and ensure that clients\' crypto-assets are not used for the CASP\'s own account without prior explicit written consent. CASPs must also provide clients with regular statements of the crypto-assets held.',
            contentEn: 'CASPs providing custody and administration of crypto-assets on behalf of clients must establish and implement a custody policy that sets out the internal rules and procedures to ensure the safekeeping of clients\' crypto-assets or the means of access thereto. CASPs are liable for losses arising from ICT-related incidents, including cyber-attacks, unless they can prove the loss arose from an event beyond their reasonable control. They must segregate clients\' crypto-assets from their own holdings, maintain accurate records of positions for each client, and ensure that clients\' crypto-assets are not used for the CASP\'s own account without prior explicit written consent. CASPs must also provide clients with regular statements of the crypto-assets held.',
            chapter: 'Title V — Crypto-Asset Service Providers',
            sortOrder: 9,
            tags: ['casp', 'custody', 'segregation', 'client-assets', 'liability', 'record-keeping'],
            appliesToBiz: ['exchange', 'wallet-provider'],
          },
          {
            articleNum: 'Article 80',
            articleTitle: 'CASP — Exchange of crypto-assets for funds or other crypto-assets',
            content: 'CASPs providing exchange services between crypto-assets and fiat currencies, or between different crypto-assets, must establish a non-discriminatory commercial policy that indicates the methodology used to determine the prices of the crypto-assets they propose to exchange. CASPs must publish a firm price or the method for determining the price before execution and must provide clients with clear information about all applicable fees and costs. They must execute exchange orders at the quoted price and provide the client with a confirmation of the exchange including the types of crypto-assets exchanged, the quantities, the unit price, the total cost, and the fees charged. CASPs must not engage in trading against clients\' interests.',
            contentEn: 'CASPs providing exchange services between crypto-assets and fiat currencies, or between different crypto-assets, must establish a non-discriminatory commercial policy that indicates the methodology used to determine the prices of the crypto-assets they propose to exchange. CASPs must publish a firm price or the method for determining the price before execution and must provide clients with clear information about all applicable fees and costs. They must execute exchange orders at the quoted price and provide the client with a confirmation of the exchange including the types of crypto-assets exchanged, the quantities, the unit price, the total cost, and the fees charged. CASPs must not engage in trading against clients\' interests.',
            chapter: 'Title V — Crypto-Asset Service Providers',
            sortOrder: 10,
            tags: ['casp', 'exchange', 'pricing', 'transparency', 'execution', 'fees'],
            appliesToBiz: ['exchange', 'payment-service'],
          },
          {
            articleNum: 'Article 86',
            articleTitle: 'Market abuse — Prohibition of insider dealing',
            content: 'Any person who possesses inside information relating to a crypto-asset shall not use that information to acquire or dispose of that crypto-asset, either directly or indirectly, for their own account or for the account of a third party. Inside information means information of a precise nature that has not been made public, relates directly or indirectly to one or more crypto-assets, and would, if made public, be likely to have a significant effect on the prices of those crypto-assets. The prohibition extends to recommending or inducing another person to engage in insider dealing, as well as the unlawful disclosure of inside information. Attempted insider dealing is also prohibited under this article.',
            contentEn: 'Any person who possesses inside information relating to a crypto-asset shall not use that information to acquire or dispose of that crypto-asset, either directly or indirectly, for their own account or for the account of a third party. Inside information means information of a precise nature that has not been made public, relates directly or indirectly to one or more crypto-assets, and would, if made public, be likely to have a significant effect on the prices of those crypto-assets. The prohibition extends to recommending or inducing another person to engage in insider dealing, as well as the unlawful disclosure of inside information. Attempted insider dealing is also prohibited under this article.',
            chapter: 'Title VI — Market Abuse',
            sortOrder: 11,
            tags: ['market-abuse', 'insider-dealing', 'inside-information', 'prohibition'],
            appliesToBiz: ['exchange', 'token-issuer', 'stablecoin-issuer', 'fund-manager'],
          },
          {
            articleNum: 'Article 87',
            articleTitle: 'Market abuse — Prohibition of market manipulation',
            content: 'Market manipulation in the crypto-asset market is strictly prohibited. Manipulation includes entering into transactions, placing orders, or engaging in any other activity that gives or is likely to give false or misleading signals as to the supply of, demand for, or price of a crypto-asset. It also covers transactions that secure the price of a crypto-asset at an abnormal or artificial level, and the dissemination of false or misleading information through the media, including the internet, which gives or is likely to give false signals about the price or supply. Wash trading, layering, spoofing, and pump-and-dump schemes are explicitly covered. The prohibition applies to any person regardless of whether they hold any crypto-assets.',
            contentEn: 'Market manipulation in the crypto-asset market is strictly prohibited. Manipulation includes entering into transactions, placing orders, or engaging in any other activity that gives or is likely to give false or misleading signals as to the supply of, demand for, or price of a crypto-asset. It also covers transactions that secure the price of a crypto-asset at an abnormal or artificial level, and the dissemination of false or misleading information through the media, including the internet, which gives or is likely to give false signals about the price or supply. Wash trading, layering, spoofing, and pump-and-dump schemes are explicitly covered. The prohibition applies to any person regardless of whether they hold any crypto-assets.',
            chapter: 'Title VI — Market Abuse',
            sortOrder: 12,
            tags: ['market-abuse', 'manipulation', 'wash-trading', 'spoofing', 'pump-and-dump'],
            appliesToBiz: ['exchange', 'token-issuer', 'stablecoin-issuer', 'defi-protocol'],
          },
          {
            articleNum: 'Article 88',
            articleTitle: 'Market abuse — Prevention and detection / PDMR obligations',
            content: 'Persons discharging managerial responsibilities (PDMRs) within an issuer of crypto-assets or a CASP, and persons closely associated with them, must notify the competent authority of every transaction conducted on their own account relating to the crypto-assets of that issuer within two business days. PDMRs include members of the management body, senior executives who have regular access to inside information and the power to make managerial decisions affecting the future development of the entity. The issuer must maintain an insider list of all persons who have access to inside information and must update and provide this list to the competent authority upon request. Issuers must also publicly disclose inside information as soon as possible.',
            contentEn: 'Persons discharging managerial responsibilities (PDMRs) within an issuer of crypto-assets or a CASP, and persons closely associated with them, must notify the competent authority of every transaction conducted on their own account relating to the crypto-assets of that issuer within two business days. PDMRs include members of the management body, senior executives who have regular access to inside information and the power to make managerial decisions affecting the future development of the entity. The issuer must maintain an insider list of all persons who have access to inside information and must update and provide this list to the competent authority upon request. Issuers must also publicly disclose inside information as soon as possible.',
            chapter: 'Title VI — Market Abuse',
            sortOrder: 13,
            tags: ['market-abuse', 'pdmr', 'insider-list', 'disclosure', 'notification'],
            appliesToBiz: ['exchange', 'token-issuer', 'stablecoin-issuer'],
          },
          {
            articleNum: 'Article 92',
            articleTitle: 'Administrative sanctions and measures',
            content: 'Member States shall ensure that competent authorities have the power to impose administrative sanctions and measures for infringements of MiCA, including the withdrawal of authorisation, a public statement identifying the person and the nature of the infringement, an order requiring the person to cease the conduct, and administrative pecuniary sanctions. For legal persons, the maximum administrative fine shall be at least EUR 15,000,000 or up to 12.5% of the total annual turnover as determined by the most recent available financial statements approved by the management body, whichever is higher. For natural persons, the maximum fine shall be at least EUR 5,000,000. Competent authorities shall publish all decisions imposing sanctions on their websites without undue delay.',
            contentEn: 'Member States shall ensure that competent authorities have the power to impose administrative sanctions and measures for infringements of MiCA, including the withdrawal of authorisation, a public statement identifying the person and the nature of the infringement, an order requiring the person to cease the conduct, and administrative pecuniary sanctions. For legal persons, the maximum administrative fine shall be at least EUR 15,000,000 or up to 12.5% of the total annual turnover as determined by the most recent available financial statements approved by the management body, whichever is higher. For natural persons, the maximum fine shall be at least EUR 5,000,000. Competent authorities shall publish all decisions imposing sanctions on their websites without undue delay.',
            chapter: 'Title VII — Competent Authorities, EBA and ESMA',
            sortOrder: 14,
            tags: ['sanctions', 'penalties', 'fine', 'turnover-percentage', 'authorisation-withdrawal'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'token-issuer', 'payment-service'],
          },
          {
            articleNum: 'Article 111',
            articleTitle: 'Transitional provisions — Grandfathering',
            content: 'Crypto-asset service providers that were providing their services in accordance with applicable national law before the date of application of MiCA may continue to do so until 1 July 2026 or until they are granted or refused authorisation under MiCA, whichever is earlier. Member States may decide not to apply this transitional period or to reduce its duration. During the transitional period, existing CASPs must submit an application for authorisation under MiCA. This grandfathering clause ensures business continuity and prevents market disruption while the new regulatory framework is phased in. CASPs that do not apply for MiCA authorisation within the transitional period must cease their activities.',
            contentEn: 'Crypto-asset service providers that were providing their services in accordance with applicable national law before the date of application of MiCA may continue to do so until 1 July 2026 or until they are granted or refused authorisation under MiCA, whichever is earlier. Member States may decide not to apply this transitional period or to reduce its duration. During the transitional period, existing CASPs must submit an application for authorisation under MiCA. This grandfathering clause ensures business continuity and prevents market disruption while the new regulatory framework is phased in. CASPs that do not apply for MiCA authorisation within the transitional period must cease their activities.',
            chapter: 'Title IX — Transitional and Final Provisions',
            sortOrder: 15,
            tags: ['transitional', 'grandfathering', 'existing-casp', 'deadline', 'business-continuity'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'token-issuer', 'payment-service'],
          },
        ],
      },
    },
  });

  console.log(`  ✓ ${micaAdditional.title} — ${micaAdditional.totalArticles} articles archived`);

  // ═══════════════════════════════════════════════════════════
  // EU: DORA (Regulation 2022/2554)
  // Digital Operational Resilience Act
  // ═══════════════════════════════════════════════════════════
  const dora = await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-2022/2554' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawType: 'regulation',
      title: 'Regulation (EU) 2022/2554 — Digital Operational Resilience Act (DORA)',
      titleEn: 'Regulation (EU) 2022/2554 — Digital Operational Resilience Act (DORA)',
      shortName: 'DORA',
      lawNumber: 'EU-2022/2554',
      enactedDate: new Date('2022-12-14'),
      effectiveDate: new Date('2025-01-17'),
      status: 'enacted',
      regulator: 'European Parliament / ESAs',
      sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2022/2554/oj',
      totalArticles: 13,
      articles: {
        create: [
          {
            articleNum: 'Article 5',
            articleTitle: 'Governance and organisation',
            content: 'The management body of a financial entity, including crypto-asset service providers under MiCA, bears ultimate responsibility for managing ICT risk. The management body must define, approve, oversee, and be accountable for the implementation of the ICT risk management framework. Members of the management body are required to maintain sufficient knowledge and skills to understand and assess ICT risks and their impact on the operations of the entity. They must actively engage in the management and oversight of ICT risk on an ongoing basis and allocate adequate budget for ICT security and digital operational resilience needs.',
            contentEn: 'The management body of a financial entity, including crypto-asset service providers under MiCA, bears ultimate responsibility for managing ICT risk. The management body must define, approve, oversee, and be accountable for the implementation of the ICT risk management framework. Members of the management body are required to maintain sufficient knowledge and skills to understand and assess ICT risks and their impact on the operations of the entity. They must actively engage in the management and oversight of ICT risk on an ongoing basis and allocate adequate budget for ICT security and digital operational resilience needs.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 1,
            tags: ['governance', 'management-body', 'ict-risk', 'accountability', 'budget'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 6',
            articleTitle: 'ICT risk management framework',
            content: 'Financial entities must establish and maintain a sound, comprehensive, and well-documented ICT risk management framework that enables them to address ICT risk quickly, efficiently, and comprehensively. The framework must include strategies, policies, procedures, ICT protocols, and tools necessary to adequately protect all information assets and ICT assets, including computer software, hardware, and servers. The framework shall be documented and reviewed at least annually, or upon the occurrence of major ICT-related incidents, and must be continuously improved based on lessons learned from testing and incidents. It must be subject to internal audit on a regular basis.',
            contentEn: 'Financial entities must establish and maintain a sound, comprehensive, and well-documented ICT risk management framework that enables them to address ICT risk quickly, efficiently, and comprehensively. The framework must include strategies, policies, procedures, ICT protocols, and tools necessary to adequately protect all information assets and ICT assets, including computer software, hardware, and servers. The framework shall be documented and reviewed at least annually, or upon the occurrence of major ICT-related incidents, and must be continuously improved based on lessons learned from testing and incidents. It must be subject to internal audit on a regular basis.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 2,
            tags: ['ict-risk-framework', 'documentation', 'annual-review', 'internal-audit'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 7',
            articleTitle: 'ICT systems, protocols and tools',
            content: 'Financial entities shall use and maintain updated ICT systems, protocols, and tools that are appropriate to the scale of their operations and adequate to support the performance of their activities and the provision of services. These systems must be reliable, have sufficient capacity, and be technologically resilient to adequately process the data and information necessary for the performance of activities and the timely provision of services. The entity must implement security-by-design and security-by-default principles, ensure the confidentiality, integrity, and availability of data, and employ state-of-the-art security mechanisms for authentication, infrastructure management, and data transfers.',
            contentEn: 'Financial entities shall use and maintain updated ICT systems, protocols, and tools that are appropriate to the scale of their operations and adequate to support the performance of their activities and the provision of services. These systems must be reliable, have sufficient capacity, and be technologically resilient to adequately process the data and information necessary for the performance of activities and the timely provision of services. The entity must implement security-by-design and security-by-default principles, ensure the confidentiality, integrity, and availability of data, and employ state-of-the-art security mechanisms for authentication, infrastructure management, and data transfers.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 3,
            tags: ['ict-systems', 'security-by-design', 'confidentiality', 'integrity', 'availability'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'data-analytics'],
          },
          {
            articleNum: 'Article 8',
            articleTitle: 'Identification',
            content: 'Financial entities must identify, classify, and adequately document all ICT-supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their roles and dependencies. They must identify all sources of ICT risk, including risk from ICT third-party providers, and assess the cyber threats and ICT vulnerabilities relevant to their ICT-supported business functions and information assets. Entities must maintain an up-to-date inventory of all ICT assets (hardware, software, and network resources) and perform a risk assessment at least annually or whenever a major change occurs in the network and information system infrastructure.',
            contentEn: 'Financial entities must identify, classify, and adequately document all ICT-supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their roles and dependencies. They must identify all sources of ICT risk, including risk from ICT third-party providers, and assess the cyber threats and ICT vulnerabilities relevant to their ICT-supported business functions and information assets. Entities must maintain an up-to-date inventory of all ICT assets (hardware, software, and network resources) and perform a risk assessment at least annually or whenever a major change occurs in the network and information system infrastructure.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 4,
            tags: ['identification', 'asset-inventory', 'risk-assessment', 'classification', 'documentation'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'data-analytics'],
          },
          {
            articleNum: 'Article 9',
            articleTitle: 'Protection and prevention',
            content: 'Financial entities must develop and document an information security policy defining rules to protect the confidentiality, integrity, and availability of their data and ICT assets. They must implement strong access control mechanisms based on the least-privilege principle and the need-to-know basis, including multi-factor authentication for all critical systems. Entities shall deploy robust encryption for data at rest and in transit, maintain up-to-date patch management processes, implement network segmentation, and establish comprehensive identity and access management procedures. Physical security measures must also be in place to protect ICT assets from unauthorised access, damage, and interference.',
            contentEn: 'Financial entities must develop and document an information security policy defining rules to protect the confidentiality, integrity, and availability of their data and ICT assets. They must implement strong access control mechanisms based on the least-privilege principle and the need-to-know basis, including multi-factor authentication for all critical systems. Entities shall deploy robust encryption for data at rest and in transit, maintain up-to-date patch management processes, implement network segmentation, and establish comprehensive identity and access management procedures. Physical security measures must also be in place to protect ICT assets from unauthorised access, damage, and interference.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 5,
            tags: ['protection', 'encryption', 'access-control', 'mfa', 'patch-management', 'network-segmentation'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'data-analytics'],
          },
          {
            articleNum: 'Article 10',
            articleTitle: 'Detection',
            content: 'Financial entities must establish mechanisms to promptly detect anomalous activities, including ICT network performance issues and ICT-related incidents. All detection mechanisms must be regularly tested. Entities shall implement multiple layers of controls, including the definition of alert thresholds and criteria to trigger ICT-related incident detection and response processes. They must deploy automated tools for real-time monitoring of network traffic and system activities, capable of identifying unusual patterns, suspicious transactions, and potential cyber-attacks. Log data must be retained for a sufficient period to enable post-incident analysis and must be protected from tampering.',
            contentEn: 'Financial entities must establish mechanisms to promptly detect anomalous activities, including ICT network performance issues and ICT-related incidents. All detection mechanisms must be regularly tested. Entities shall implement multiple layers of controls, including the definition of alert thresholds and criteria to trigger ICT-related incident detection and response processes. They must deploy automated tools for real-time monitoring of network traffic and system activities, capable of identifying unusual patterns, suspicious transactions, and potential cyber-attacks. Log data must be retained for a sufficient period to enable post-incident analysis and must be protected from tampering.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 6,
            tags: ['detection', 'monitoring', 'anomaly-detection', 'real-time', 'log-retention'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'data-analytics'],
          },
          {
            articleNum: 'Article 11',
            articleTitle: 'Response and recovery',
            content: 'Financial entities must establish a comprehensive ICT business continuity policy and associated disaster recovery plans. These must be tested at least annually through appropriate scenario-based exercises that simulate severe but plausible disruption scenarios, including cyber-attacks. The entity must implement an ICT-related incident response plan with clear procedures for identifying, tracking, logging, categorising, and communicating ICT-related incidents. Backup policies and procedures must ensure that data can be restored with minimal downtime and limited disruption. Entities must maintain redundant ICT capacities with resources sufficient to ensure service continuity and must regularly review and update their response and recovery plans.',
            contentEn: 'Financial entities must establish a comprehensive ICT business continuity policy and associated disaster recovery plans. These must be tested at least annually through appropriate scenario-based exercises that simulate severe but plausible disruption scenarios, including cyber-attacks. The entity must implement an ICT-related incident response plan with clear procedures for identifying, tracking, logging, categorising, and communicating ICT-related incidents. Backup policies and procedures must ensure that data can be restored with minimal downtime and limited disruption. Entities must maintain redundant ICT capacities with resources sufficient to ensure service continuity and must regularly review and update their response and recovery plans.',
            chapter: 'Chapter II — ICT Risk Management',
            sortOrder: 7,
            tags: ['response', 'recovery', 'bcp', 'disaster-recovery', 'backup', 'incident-response'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 17',
            articleTitle: 'ICT-related incident reporting process',
            content: 'Financial entities must establish and implement a management process to monitor, handle, and follow up on ICT-related incidents. They must classify ICT-related incidents based on criteria including the number of clients affected, the duration of the incident, the geographical spread, the data losses involved, the criticality of the services affected, and the economic impact. Major ICT-related incidents must be reported to the relevant competent authority using standardised reporting templates. The initial notification must be submitted within four hours of classifying the incident as major and no later than 24 hours after detection. An intermediate report must follow within 72 hours, and a final report within one month of the incident.',
            contentEn: 'Financial entities must establish and implement a management process to monitor, handle, and follow up on ICT-related incidents. They must classify ICT-related incidents based on criteria including the number of clients affected, the duration of the incident, the geographical spread, the data losses involved, the criticality of the services affected, and the economic impact. Major ICT-related incidents must be reported to the relevant competent authority using standardised reporting templates. The initial notification must be submitted within four hours of classifying the incident as major and no later than 24 hours after detection. An intermediate report must follow within 72 hours, and a final report within one month of the incident.',
            chapter: 'Chapter III — ICT-Related Incident Reporting',
            sortOrder: 8,
            tags: ['incident-reporting', 'classification', 'notification-timeline', 'major-incident'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 19',
            articleTitle: 'Reporting of major ICT-related incidents and significant cyber threats',
            content: 'Financial entities shall report major ICT-related incidents to the relevant competent authority in accordance with the timelines and templates established by the European Supervisory Authorities. The report must include a description of the incident, its root cause (where identified), the impact on clients and financial markets, the remedial actions taken, and any cross-border implications. Entities may also voluntarily report significant cyber threats that they deem could materialise into a major incident. Competent authorities shall share anonymised incident data with other relevant authorities and ENISA to promote a collective understanding of the cyber threat landscape. Where an incident has or is likely to have an impact on the financial interests of clients, the entity shall inform affected clients without undue delay.',
            contentEn: 'Financial entities shall report major ICT-related incidents to the relevant competent authority in accordance with the timelines and templates established by the European Supervisory Authorities. The report must include a description of the incident, its root cause (where identified), the impact on clients and financial markets, the remedial actions taken, and any cross-border implications. Entities may also voluntarily report significant cyber threats that they deem could materialise into a major incident. Competent authorities shall share anonymised incident data with other relevant authorities and ENISA to promote a collective understanding of the cyber threat landscape. Where an incident has or is likely to have an impact on the financial interests of clients, the entity shall inform affected clients without undue delay.',
            chapter: 'Chapter III — ICT-Related Incident Reporting',
            sortOrder: 9,
            tags: ['major-incident-reporting', 'cyber-threats', 'client-notification', 'cross-border', 'enisa'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 23',
            articleTitle: 'Digital operational resilience testing — General requirements',
            content: 'Financial entities must establish, maintain, and review a sound and comprehensive digital operational resilience testing programme as an integral part of their ICT risk management framework. The testing programme must include a range of assessments, tests, methodologies, practices, and tools, such as vulnerability assessments and scans, open-source analyses, network security assessments, gap analyses, physical security reviews, source code reviews, scenario-based tests, compatibility testing, performance testing, end-to-end testing, and penetration testing. Testing must be undertaken at least annually for all critical ICT systems and applications. Entities must ensure that tests are conducted by independent parties, whether internal or external, to avoid conflicts of interest.',
            contentEn: 'Financial entities must establish, maintain, and review a sound and comprehensive digital operational resilience testing programme as an integral part of their ICT risk management framework. The testing programme must include a range of assessments, tests, methodologies, practices, and tools, such as vulnerability assessments and scans, open-source analyses, network security assessments, gap analyses, physical security reviews, source code reviews, scenario-based tests, compatibility testing, performance testing, end-to-end testing, and penetration testing. Testing must be undertaken at least annually for all critical ICT systems and applications. Entities must ensure that tests are conducted by independent parties, whether internal or external, to avoid conflicts of interest.',
            chapter: 'Chapter IV — Digital Operational Resilience Testing',
            sortOrder: 10,
            tags: ['resilience-testing', 'penetration-testing', 'vulnerability-assessment', 'annual-testing'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 24',
            articleTitle: 'Threat-led penetration testing (TLPT)',
            content: 'Financial entities identified by competent authorities as significant shall carry out threat-led penetration testing (TLPT) at least every three years. TLPT must be performed by external testers who are independent, certified, and use the latest threat intelligence. The scope of TLPT must cover critical or important functions of the financial entity and must be performed on live production systems. The testing must simulate the tactics, techniques, and procedures of real threat actors, including advanced persistent threats. Upon completion, the entity must submit a summary of the findings and the remediation plan to the competent authority. Testers must hold professional indemnity insurance and the entity must ensure that participation in TLPT does not excessively disrupt the continuity of services.',
            contentEn: 'Financial entities identified by competent authorities as significant shall carry out threat-led penetration testing (TLPT) at least every three years. TLPT must be performed by external testers who are independent, certified, and use the latest threat intelligence. The scope of TLPT must cover critical or important functions of the financial entity and must be performed on live production systems. The testing must simulate the tactics, techniques, and procedures of real threat actors, including advanced persistent threats. Upon completion, the entity must submit a summary of the findings and the remediation plan to the competent authority. Testers must hold professional indemnity insurance and the entity must ensure that participation in TLPT does not excessively disrupt the continuity of services.',
            chapter: 'Chapter IV — Digital Operational Resilience Testing',
            sortOrder: 11,
            tags: ['tlpt', 'penetration-testing', 'threat-intelligence', 'production-testing', 'significant-entity'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 28',
            articleTitle: 'General principles of ICT third-party risk management',
            content: 'Financial entities must manage ICT third-party risk as an integral component of their ICT risk management framework. They must adopt and regularly review a strategy on ICT third-party risk that includes a policy on the use of ICT services supporting critical or important functions provided by ICT third-party service providers. Before entering into a contractual arrangement, the entity must identify and assess all relevant risks, including concentration risk where a single provider supports multiple critical functions. The entity must maintain a register of all contractual arrangements with ICT third-party service providers, distinguishing between those that support critical or important functions and others. The competent authority must be able to access this register at any time upon request.',
            contentEn: 'Financial entities must manage ICT third-party risk as an integral component of their ICT risk management framework. They must adopt and regularly review a strategy on ICT third-party risk that includes a policy on the use of ICT services supporting critical or important functions provided by ICT third-party service providers. Before entering into a contractual arrangement, the entity must identify and assess all relevant risks, including concentration risk where a single provider supports multiple critical functions. The entity must maintain a register of all contractual arrangements with ICT third-party service providers, distinguishing between those that support critical or important functions and others. The competent authority must be able to access this register at any time upon request.',
            chapter: 'Chapter V — Managing of ICT Third-Party Risk',
            sortOrder: 12,
            tags: ['third-party-risk', 'concentration-risk', 'vendor-management', 'register', 'critical-functions'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager', 'data-analytics'],
          },
          {
            articleNum: 'Article 30',
            articleTitle: 'Key contractual provisions for ICT third-party providers',
            content: 'Contractual arrangements with ICT third-party service providers must include at a minimum: a clear and complete description of all functions and ICT services to be provided, the locations where the contracted functions will be provided and data will be processed, provisions on availability, authenticity, integrity, and confidentiality of data, provisions ensuring access and recovery of data in the case of insolvency or resolution of the ICT third-party provider, service-level descriptions with quantitative and qualitative performance targets, notice periods and reporting obligations of the ICT third-party provider, and the right to audit the provider. For services supporting critical or important functions, contracts must also include exit strategies and transition periods to enable the entity to migrate to another provider or revert to in-house solutions without service disruption.',
            contentEn: 'Contractual arrangements with ICT third-party service providers must include at a minimum: a clear and complete description of all functions and ICT services to be provided, the locations where the contracted functions will be provided and data will be processed, provisions on availability, authenticity, integrity, and confidentiality of data, provisions ensuring access and recovery of data in the case of insolvency or resolution of the ICT third-party provider, service-level descriptions with quantitative and qualitative performance targets, notice periods and reporting obligations of the ICT third-party provider, and the right to audit the provider. For services supporting critical or important functions, contracts must also include exit strategies and transition periods to enable the entity to migrate to another provider or revert to in-house solutions without service disruption.',
            chapter: 'Chapter V — Managing of ICT Third-Party Risk',
            sortOrder: 13,
            tags: ['contract-provisions', 'sla', 'audit-rights', 'exit-strategy', 'data-recovery'],
            appliesToBiz: ['exchange', 'wallet-provider', 'stablecoin-issuer', 'payment-service', 'fund-manager', 'data-analytics'],
          },
        ],
      },
    },
  });

  console.log(`  ✓ ${dora.title} — ${dora.totalArticles} articles archived`);

  // ═══════════════════════════════════════════════════════════
  // EU: AML Regulation (2024/1624)
  // Anti-Money Laundering Regulation — crypto provisions
  // ═══════════════════════════════════════════════════════════
  const euAml = await prisma.lawArchive.upsert({
    where: { jurisdiction_lawNumber: { jurisdiction: 'EU', lawNumber: 'EU-2024/1624' } },
    update: {},
    create: {
      jurisdiction: 'EU',
      lawType: 'regulation',
      title: 'Regulation (EU) 2024/1624 — Anti-Money Laundering Regulation (AMLR)',
      titleEn: 'Regulation (EU) 2024/1624 — Anti-Money Laundering Regulation (AMLR)',
      shortName: 'EU AMLR',
      lawNumber: 'EU-2024/1624',
      enactedDate: new Date('2024-05-30'),
      effectiveDate: new Date('2027-07-01'),
      status: 'enacted',
      regulator: 'European Parliament / AMLA',
      sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2024/1624/oj',
      totalArticles: 8,
      articles: {
        create: [
          {
            articleNum: 'Article 3',
            articleTitle: 'Definitions — Crypto-asset service provider under AML',
            content: 'For the purposes of this Regulation, a crypto-asset service provider (CASP) means any entity authorised under Regulation (EU) 2023/1114 (MiCA) to provide one or more crypto-asset services. CASPs are classified as obliged entities under the EU anti-money laundering framework, placing them on par with traditional financial institutions regarding AML/CFT obligations. The definition encompasses exchanges, custodial wallet providers, platforms facilitating the transfer of crypto-assets, and entities providing advice or portfolio management in crypto-assets. Self-hosted wallets and decentralised protocols without a controlling entity are not classified as CASPs, but transactions involving them are subject to enhanced scrutiny.',
            contentEn: 'For the purposes of this Regulation, a crypto-asset service provider (CASP) means any entity authorised under Regulation (EU) 2023/1114 (MiCA) to provide one or more crypto-asset services. CASPs are classified as obliged entities under the EU anti-money laundering framework, placing them on par with traditional financial institutions regarding AML/CFT obligations. The definition encompasses exchanges, custodial wallet providers, platforms facilitating the transfer of crypto-assets, and entities providing advice or portfolio management in crypto-assets. Self-hosted wallets and decentralised protocols without a controlling entity are not classified as CASPs, but transactions involving them are subject to enhanced scrutiny.',
            chapter: 'Chapter I — General Provisions',
            sortOrder: 1,
            tags: ['definition', 'casp', 'obliged-entity', 'aml-scope', 'self-hosted-wallet'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'fund-manager'],
          },
          {
            articleNum: 'Article 16',
            articleTitle: 'Customer due diligence measures',
            content: 'CASPs and other obliged entities must apply customer due diligence (CDD) measures when establishing a business relationship, carrying out an occasional transaction above the prescribed threshold, or when there is a suspicion of money laundering or terrorist financing regardless of any derogation, exemption, or threshold. CDD measures include identifying the customer and verifying their identity on the basis of documents, data, or information obtained from a reliable and independent source. For crypto-asset transfers, CASPs must verify the identity of the customer before executing the first transaction. The entity must also identify the purpose and intended nature of the business relationship and conduct ongoing monitoring of the business relationship, including scrutiny of transactions to ensure consistency with the entity\'s knowledge of the customer.',
            contentEn: 'CASPs and other obliged entities must apply customer due diligence (CDD) measures when establishing a business relationship, carrying out an occasional transaction above the prescribed threshold, or when there is a suspicion of money laundering or terrorist financing regardless of any derogation, exemption, or threshold. CDD measures include identifying the customer and verifying their identity on the basis of documents, data, or information obtained from a reliable and independent source. For crypto-asset transfers, CASPs must verify the identity of the customer before executing the first transaction. The entity must also identify the purpose and intended nature of the business relationship and conduct ongoing monitoring of the business relationship, including scrutiny of transactions to ensure consistency with the entity\'s knowledge of the customer.',
            chapter: 'Chapter III — Customer Due Diligence',
            sortOrder: 2,
            tags: ['cdd', 'kyc', 'identity-verification', 'ongoing-monitoring', 'business-relationship'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'fund-manager', 'stablecoin-issuer'],
          },
          {
            articleNum: 'Article 19',
            articleTitle: 'Enhanced customer due diligence',
            content: 'Obliged entities, including CASPs, must apply enhanced customer due diligence (EDD) measures in situations that by their nature present a higher risk of money laundering or terrorist financing. EDD is mandatory for transactions involving high-risk third countries, politically exposed persons (PEPs), complex or unusually large transactions, and any transaction that has no apparent economic or lawful purpose. For crypto-asset services specifically, EDD must be applied to transactions involving self-hosted wallets (unhosted wallets) where the beneficial owner cannot be readily identified, privacy-enhancing crypto-assets or mixing/tumbling services, and cross-border transactions above EUR 1,000. EDD measures include obtaining additional information on the customer, the beneficial owner, the source of funds, and the purpose of the transaction.',
            contentEn: 'Obliged entities, including CASPs, must apply enhanced customer due diligence (EDD) measures in situations that by their nature present a higher risk of money laundering or terrorist financing. EDD is mandatory for transactions involving high-risk third countries, politically exposed persons (PEPs), complex or unusually large transactions, and any transaction that has no apparent economic or lawful purpose. For crypto-asset services specifically, EDD must be applied to transactions involving self-hosted wallets (unhosted wallets) where the beneficial owner cannot be readily identified, privacy-enhancing crypto-assets or mixing/tumbling services, and cross-border transactions above EUR 1,000. EDD measures include obtaining additional information on the customer, the beneficial owner, the source of funds, and the purpose of the transaction.',
            chapter: 'Chapter III — Customer Due Diligence',
            sortOrder: 3,
            tags: ['enhanced-due-diligence', 'high-risk', 'pep', 'self-hosted-wallet', 'privacy-coins', 'mixer'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'fund-manager', 'defi-protocol'],
          },
          {
            articleNum: 'Article 22',
            articleTitle: 'Beneficial ownership identification',
            content: 'Obliged entities must identify the beneficial owner of any customer that is a legal person, trust, or similar legal arrangement, and take reasonable measures to verify their identity. The beneficial owner is defined as any natural person who ultimately owns or controls the customer through direct or indirect ownership of a sufficient percentage of shares, voting rights, or ownership interest, or through other means. A shareholding or ownership interest of more than 25% is an indication of direct ownership. For crypto-asset transactions, this obligation applies equally: CASPs must identify the beneficial owner behind corporate accounts and must not establish or maintain a business relationship where the beneficial ownership structure cannot be determined. Member States must ensure that beneficial ownership information is held in a central register accessible to competent authorities.',
            contentEn: 'Obliged entities must identify the beneficial owner of any customer that is a legal person, trust, or similar legal arrangement, and take reasonable measures to verify their identity. The beneficial owner is defined as any natural person who ultimately owns or controls the customer through direct or indirect ownership of a sufficient percentage of shares, voting rights, or ownership interest, or through other means. A shareholding or ownership interest of more than 25% is an indication of direct ownership. For crypto-asset transactions, this obligation applies equally: CASPs must identify the beneficial owner behind corporate accounts and must not establish or maintain a business relationship where the beneficial ownership structure cannot be determined. Member States must ensure that beneficial ownership information is held in a central register accessible to competent authorities.',
            chapter: 'Chapter III — Customer Due Diligence',
            sortOrder: 4,
            tags: ['beneficial-ownership', 'ubo', 'transparency', 'central-register', '25-percent-threshold'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'fund-manager', 'stablecoin-issuer', 'token-issuer'],
          },
          {
            articleNum: 'Article 50',
            articleTitle: 'Transfer of funds and crypto-assets — Travel Rule',
            content: 'CASPs of the originator must ensure that transfers of crypto-assets are accompanied by the name and account number of the originator, the originator\'s address or national identity number or customer identification number or date and place of birth, and the name and account number of the beneficiary. Unlike the traditional travel rule for wire transfers which has a EUR 1,000 threshold, the crypto-asset travel rule applies to ALL transfers regardless of amount (EUR 0 threshold). For transfers between two CASPs, the originator\'s CASP must transmit this information to the beneficiary\'s CASP simultaneously with the transfer. For transfers to self-hosted wallets exceeding EUR 1,000, the CASP must verify whether the self-hosted address is effectively owned or controlled by its customer. This zero-threshold approach reflects the higher ML/TF risks associated with crypto-asset transfers.',
            contentEn: 'CASPs of the originator must ensure that transfers of crypto-assets are accompanied by the name and account number of the originator, the originator\'s address or national identity number or customer identification number or date and place of birth, and the name and account number of the beneficiary. Unlike the traditional travel rule for wire transfers which has a EUR 1,000 threshold, the crypto-asset travel rule applies to ALL transfers regardless of amount (EUR 0 threshold). For transfers between two CASPs, the originator\'s CASP must transmit this information to the beneficiary\'s CASP simultaneously with the transfer. For transfers to self-hosted wallets exceeding EUR 1,000, the CASP must verify whether the self-hosted address is effectively owned or controlled by its customer. This zero-threshold approach reflects the higher ML/TF risks associated with crypto-asset transfers.',
            chapter: 'Chapter V — Transfers of Funds and Crypto-Assets',
            sortOrder: 5,
            tags: ['travel-rule', 'zero-threshold', 'originator-info', 'beneficiary-info', 'self-hosted-wallet'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
          },
          {
            articleNum: 'Article 51',
            articleTitle: 'Information accompanying transfers of crypto-assets',
            content: 'The beneficiary\'s CASP must implement effective procedures to detect whether the required originator and beneficiary information is included with the crypto-asset transfer. For transfers exceeding EUR 1,000, the beneficiary\'s CASP must verify the accuracy of the information about the beneficiary before making the crypto-assets available. Where a CASP repeatedly fails to provide the required information, the beneficiary\'s CASP must reject the transfer, restrict or terminate the business relationship, and consider filing a suspicious transaction report. CASPs must retain records of all originator and beneficiary information for a period of five years after the end of the business relationship. The specific data fields required include the distributed ledger address, the crypto-asset account number, and any unique transaction identifier that allows traceability of the transaction.',
            contentEn: 'The beneficiary\'s CASP must implement effective procedures to detect whether the required originator and beneficiary information is included with the crypto-asset transfer. For transfers exceeding EUR 1,000, the beneficiary\'s CASP must verify the accuracy of the information about the beneficiary before making the crypto-assets available. Where a CASP repeatedly fails to provide the required information, the beneficiary\'s CASP must reject the transfer, restrict or terminate the business relationship, and consider filing a suspicious transaction report. CASPs must retain records of all originator and beneficiary information for a period of five years after the end of the business relationship. The specific data fields required include the distributed ledger address, the crypto-asset account number, and any unique transaction identifier that allows traceability of the transaction.',
            chapter: 'Chapter V — Transfers of Funds and Crypto-Assets',
            sortOrder: 6,
            tags: ['transfer-information', 'verification', 'record-retention', 'five-year-retention', 'traceability'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service'],
          },
          {
            articleNum: 'Article 58',
            articleTitle: 'Suspicious transaction reports (STRs)',
            content: 'CASPs and all other obliged entities must promptly report to their national Financial Intelligence Unit (FIU) where they know, suspect, or have reasonable grounds to suspect that funds or crypto-assets are the proceeds of criminal activity or are related to terrorist financing. The STR must be filed regardless of the amount of the transaction and regardless of whether a transaction was attempted, executed, or refused. CASPs must not carry out the transaction until they have filed the STR and received guidance from the FIU, unless refraining from executing the transaction is not possible or is likely to frustrate efforts to pursue the beneficiaries of the suspected criminal activity. Tipping off the customer that an STR has been or will be filed is strictly prohibited and constitutes a criminal offence.',
            contentEn: 'CASPs and all other obliged entities must promptly report to their national Financial Intelligence Unit (FIU) where they know, suspect, or have reasonable grounds to suspect that funds or crypto-assets are the proceeds of criminal activity or are related to terrorist financing. The STR must be filed regardless of the amount of the transaction and regardless of whether a transaction was attempted, executed, or refused. CASPs must not carry out the transaction until they have filed the STR and received guidance from the FIU, unless refraining from executing the transaction is not possible or is likely to frustrate efforts to pursue the beneficiaries of the suspected criminal activity. Tipping off the customer that an STR has been or will be filed is strictly prohibited and constitutes a criminal offence.',
            chapter: 'Chapter VI — Reporting Obligations',
            sortOrder: 7,
            tags: ['str', 'suspicious-transaction', 'fiu', 'reporting', 'no-tipping-off'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'fund-manager', 'stablecoin-issuer'],
          },
          {
            articleNum: 'Article 77',
            articleTitle: 'AMLA direct supervision of high-risk obliged entities',
            content: 'The Anti-Money Laundering Authority (AMLA) shall directly supervise selected obliged entities that operate across multiple Member States and present the highest ML/TF risk profile. For the crypto-asset sector specifically, AMLA may exercise direct supervision over CASPs that provide services in a significant number of Member States and whose transaction volumes or customer base indicate systemic relevance. AMLA\'s supervisory powers include the power to conduct on-site inspections, require the production of documents, impose binding decisions, and recommend to national competent authorities that they withdraw or suspend the authorisation of a CASP. AMLA shall select the entities subject to direct supervision based on a methodology that assesses inherent risk, the quality of internal controls, and the cross-border nature of activities. The selected entities must pay supervisory fees to AMLA.',
            contentEn: 'The Anti-Money Laundering Authority (AMLA) shall directly supervise selected obliged entities that operate across multiple Member States and present the highest ML/TF risk profile. For the crypto-asset sector specifically, AMLA may exercise direct supervision over CASPs that provide services in a significant number of Member States and whose transaction volumes or customer base indicate systemic relevance. AMLA\'s supervisory powers include the power to conduct on-site inspections, require the production of documents, impose binding decisions, and recommend to national competent authorities that they withdraw or suspend the authorisation of a CASP. AMLA shall select the entities subject to direct supervision based on a methodology that assesses inherent risk, the quality of internal controls, and the cross-border nature of activities. The selected entities must pay supervisory fees to AMLA.',
            chapter: 'Chapter VIII — Supervision',
            sortOrder: 8,
            tags: ['amla', 'direct-supervision', 'cross-border', 'high-risk', 'on-site-inspection', 'supervisory-fees'],
            appliesToBiz: ['exchange', 'wallet-provider', 'payment-service', 'stablecoin-issuer'],
          },
        ],
      },
    },
  });

  console.log(`  ✓ ${euAml.title} — ${euAml.totalArticles} articles archived`);

  console.log('\n✅ EU additional laws seeded');
}

main().catch(console.error).finally(() => prisma.$disconnect());
